"""r/AskReddit — "What's the most addictive book you've ever read?"

Counted by distinct redditor: naming a book, or endorsing it in a reply, counts
once. Quoting a line, arguing about the adaptation, or saying you bounced off it
doesn't count. Answers that name only an author ("anything by Steve Cavanagh")
or only a vibe are dropped, because there's no row to put them in.

Captured the same day the thread was posted, roughly eleven hours in, while it
was still taking answers — so this is a snapshot of a live thread, not a closed
one. Every other tally on this site was counted after the thread had gone quiet.
"""
import json

THREAD = {
    "q": "What's the most addictive book you've ever read? Like the kind that keeps you thinking about it non-stop until you finish?",
    "site": "Reddit · r/AskReddit",
    "year": 2026,
    "meta": "1,856 points · 1,337 comments · captured ~11 hours after posting",
    "url": "https://www.reddit.com/r/AskReddit/comments/1w3t348/whats_the_most_addictive_book_youve_ever_read/",
}

D = [
 ("Dungeon Crawler Carl","Matt Dinniman",31),
 ("Into Thin Air","Jon Krakauer",24),
 ("Lonesome Dove","Larry McMurtry",17),
 ("The Stand","Stephen King",14),
 ("Project Hail Mary","Andy Weir",14),
 ("The Count of Monte Cristo","Alexandre Dumas",13),
 ("House of Leaves","Mark Z. Danielewski",12),
 ("11/22/63","Stephen King",11),
 ("The Dark Tower","Stephen King",10),
 ("The Pillars of the Earth","Ken Follett",10),
 ("The Three-Body Problem","Liu Cixin",8),
 ("The Hot Zone","Richard Preston",7),
 ("Piranesi","Susanna Clarke",7),
 ("The Girl with the Dragon Tattoo","Stieg Larsson",6),
 ("Gone Girl","Gillian Flynn",6),
 ("The Name of the Wind","Patrick Rothfuss",6),
 ("There Is No Antimemetics Division","qntm",5),
 ("Red Rising","Pierce Brown",5),
 ("Dark Matter","Blake Crouch",4),
 ("The Library at Mount Char","Scott Hawkins",4),
 ("Ender's Game","Orson Scott Card",4),
 ("Harry Potter","J.K. Rowling",4),
 ("The Road","Cormac McCarthy",4),
 ("Ready Player One","Ernest Cline",4),
 ("The Liveship Traders","Robin Hobb",4),
 ("Under the Banner of Heaven","Jon Krakauer",3),
 ("Crime and Punishment","Fyodor Dostoevsky",3),
 ("Tender Is the Flesh","Agustina Bazterrica",3),
 ("Dune","Frank Herbert",3),
 ("It","Stephen King",3),
 ("The Hitchhiker's Guide to the Galaxy","Douglas Adams",3),
 ("The Da Vinci Code","Dan Brown",3),
 ("The Bourne Identity","Robert Ludlum",3),
 ("The Bible","",3),
 ("Blood Meridian","Cormac McCarthy",2),
 ("My Brilliant Friend","Elena Ferrante",2),
 ("The Secret History","Donna Tartt",2),
 ("Between Two Fires","Christopher Buehlman",2),
 ("Jurassic Park","Michael Crichton",2),
 ("The Devil in the White City","Erik Larson",2),
 ("The Power of One","Bryce Courtenay",2),
 ("Where the Red Fern Grows","Wilson Rawls",2),
 ("Sharp Objects","Gillian Flynn",2),
 ("Dark Places","Gillian Flynn",2),
 ("Leviathan Wakes","James S. A. Corey",2),
 ("Infinite Jest","David Foster Wallace",2),
 ("Les Misérables","Victor Hugo",2),
 ("Reaper Man","Terry Pratchett",2),
 ("The Exorcist","William Peter Blatty",2),
 ("Breakfast of Champions","Kurt Vonnegut",2),
 ("Cat's Cradle","Kurt Vonnegut",2),
 ("The Hunger Games","Suzanne Collins",2),
 ("Children of Time","Adrian Tchaikovsky",2),
 ("A Game of Thrones","George R. R. Martin",2),
 ("The Gormenghast Trilogy","Mervyn Peake",2),
 ("The Thousand Autumns of Jacob de Zoet","David Mitchell",2),
 ("The Martian","Andy Weir",2),
 ("A Short Stay in Hell","Steven L. Peck",2),
 ("Into the Wild","Jon Krakauer",1),
 ("Stoner","John Williams",1),
 ("The Vegetarian","Han Kang",1),
 ("Kafka on the Shore","Haruki Murakami",1),
 ("The Wind-Up Bird Chronicle","Haruki Murakami",1),
 ("One Flew Over the Cuckoo's Nest","Ken Kesey",1),
 ("The Haunting of Hill House","Shirley Jackson",1),
 ("The Lovely Bones","Alice Sebold",1),
 ("Rich Dad Poor Dad","Robert Kiyosaki",1),
 ("Withered Hill","David Barnett",1),
 ("Verity","Colleen Hoover",1),
 ("The City of Dreaming Books","Walter Moers",1),
 ("Foundation","Isaac Asimov",1),
 ("The Book of the Long Sun","Gene Wolfe",1),
 ("Bel Ami","Guy de Maupassant",1),
 ("The Call of Cthulhu","H. P. Lovecraft",1),
 ("Physics for Future Presidents","Richard A. Muller",1),
 ("The Giver","Lois Lowry",1),
 ("The Deluge","Henryk Sienkiewicz",1),
 ("Expeditionary Force","Craig Alanson",1),
 ("A Storm of Swords","George R. R. Martin",1),
 ("The Firm","John Grisham",1),
 ("Lilith's Brood","Octavia E. Butler",1),
 ("Captive Prince","C. S. Pacat",1),
 ("Under the Dome","Stephen King",1),
 ("Crank","Ellen Hopkins",1),
 ("Journey of Souls","Michael Newton",1),
 ("In the Lake of the Woods","Tim O'Brien",1),
 ("The Heroes","Joe Abercrombie",1),
 ("No Country for Old Men","Cormac McCarthy",1),
 ("The Berry Pickers","Amanda Peters",1),
 ("Atmosphere","Taylor Jenkins Reid",1),
 ("The Godfather","Mario Puzo",1),
 ("Zen and the Art of Motorcycle Maintenance","Robert M. Pirsig",1),
 ("The Indifferent Stars Above","Daniel James Brown",1),
 ("The Kite Runner","Khaled Hosseini",1),
 ("Ikigai","Héctor García",1),
 ("Do You Remember?","Freida McFadden",1),
 ("The God of the Woods","Liz Moore",1),
 ("Helter Skelter","Vincent Bugliosi",1),
 ("Albatross","Deborah Scaling Kiley",1),
 ("The Nightingale","Kristin Hannah",1),
 ("The Great Alone","Kristin Hannah",1),
 ("Storm Glass","Jeff Wheeler",1),
 ("All Quiet on the Western Front","Erich Maria Remarque",1),
 ("The Terror","Dan Simmons",1),
 ("Interview with the Vampire","Anne Rice",1),
 ("Mistborn","Brandon Sanderson",1),
 ("The Island","Adrian McKinty",1),
 ("Sapiens","Yuval Noah Harari",1),
 ("Cryptonomicon","Neal Stephenson",1),
 ("The Diamond Age","Neal Stephenson",1),
 ("The Essential Calvin and Hobbes","Bill Watterson",1),
 ("Mossflower","Brian Jacques",1),
 ("Theft of Swords","Michael J. Sullivan",1),
 ("Never Let Me Go","Kazuo Ishiguro",1),
 ("The Buried Giant","Kazuo Ishiguro",1),
 ("Lord of the Mysteries","Cuttlefish That Loves Diving",1),
 ("The Wandering Inn","pirateaba",1),
 ("Lock In","John Scalzi",1),
 ("The Silent Corner","Dean Koontz",1),
 ("Slaughterhouse-Five","Kurt Vonnegut",1),
 ("The Divine Comedy","Dante Alighieri",1),
 ("River God","Wilbur Smith",1),
 ("Captain Blood","Rafael Sabatini",1),
 ("Speaker for the Dead","Orson Scott Card",1),
 ("The Stranger","Albert Camus",1),
 ("Savages","Don Winslow",1),
 ("I Am Pilgrim","Terry Hayes",1),
 ("World War Z","Max Brooks",1),
 ("Regina's Song","David Eddings",1),
 ("A Deadly Education","Naomi Novik",1),
 ("Working Stiff","Judy Melinek",1),
 ("Geek Love","Katherine Dunn",1),
 ("Running with Scissors","Augusten Burroughs",1),
 ("House of Sand and Fog","Andre Dubus III",1),
 ("The Woman in the Window","A. J. Finn",1),
 ("No Longer Human","Osamu Dazai",1),
 ("Misery","Stephen King",1),
 ("The Power Broker","Robert A. Caro",1),
 ("Lone Survivor","Marcus Luttrell",1),
 ("Airframe","Michael Crichton",1),
 ("Sphere","Michael Crichton",1),
 ("The Graveyard Book","Neil Gaiman",1),
 ("Eleanor Oliphant Is Completely Fine","Gail Honeyman",1),
 ("Nowhere","Allison Gunn",1),
 ("The Good Earth","Pearl S. Buck",1),
 ("Don Quixote","Miguel de Cervantes",1),
 ("A Thousand Splendid Suns","Khaled Hosseini",1),
 ("The Poisonwood Bible","Barbara Kingsolver",1),
 ("The Magicians","Lev Grossman",1),
 ("Pachinko","Min Jin Lee",1),
 ("Kitchen Confidential","Anthony Bourdain",1),
 ("Gregor the Overlander","Suzanne Collins",1),
 ("The Time Traveler's Wife","Audrey Niffenegger",1),
 ("The Wager","David Grann",1),
 ("The Shards","Bret Easton Ellis",1),
 ("American Psycho","Bret Easton Ellis",1),
 ("Pet Sematary","Stephen King",1),
 ("Lord of the Barnyard","Tristan Egolf",1),
 ("Unsouled","Will Wight",1),
 ("The Wheel of Time","Robert Jordan",1),
 ("Tress of the Emerald Sea","Brandon Sanderson",1),
 ("Yellowface","R. F. Kuang",1),
 ("Shatter Me","Tahereh Mafi",1),
 ("A Court of Thorns and Roses","Sarah J. Maas",1),
 ("Hostage","Clare Mackintosh",1),
 ("A Simple Plan","Scott Smith",1),
 ("The Ruins","Scott Smith",1),
 ("The Names","Florence Knapp",1),
 ("Red Mars","Kim Stanley Robinson",1),
 ("Atlas Shrugged","Ayn Rand",1),
 ("Gates of Fire","Steven Pressfield",1),
 ("Wolfsong","TJ Klune",1),
 ("A Clockwork Orange","Anthony Burgess",1),
 ("Homeland","R. A. Salvatore",1),
 ("Pandora's Star","Peter F. Hamilton",1),
 ("Tomorrow, and Tomorrow, and Tomorrow","Gabrielle Zevin",1),
 ("Ninth House","Leigh Bardugo",1),
 ("Gödel, Escher, Bach","Douglas Hofstadter",1),
 ("A Confederacy of Dunces","John Kennedy Toole",1),
 ("The Shock Doctrine","Naomi Klein",1),
 ("Twenty Thousand Leagues Under the Sea","Jules Verne",1),
 ("Demon Copperhead","Barbara Kingsolver",1),
 ("14","Peter Clines",1),
 ("Doomsday Book","Connie Willis",1),
 ("The Lord of the Rings","J. R. R. Tolkien",1),
 ("The Alchemist","Paulo Coelho",1),
 ("Twilight","Stephenie Meyer",1),
 ("Shift","Hugh Howey",1),
 ("Song of Solomon","Toni Morrison",1),
 ("Palace Walk","Naguib Mahfouz",1),
 ("Sing Backwards and Weep","Mark Lanegan",1),
 ("I Who Have Never Known Men","Jacqueline Harpman",1),
 ("Alchemised","SenLin Yu",1),
 ("Shark Heart","Emily Habeck",1),
 ("In the Woods","Tana French",1),
 ("Shutter Island","Dennis Lehane",1),
 ("Going Home","A. American",1),
 ("First Blood","David Morrell",1),
 ("Invincible","Robert Kirkman",1),
 ("The Girl on the Train","Paula Hawkins",1),
 ("American Kingpin","Nick Bilton",1),
 ("Shantaram","Gregory David Roberts",1),
 ("Fourth Wing","Rebecca Yarros",1),
 ("The Blind Assassin","Margaret Atwood",1),
 ("The War Hound and the World's Pain","Michael Moorcock",1),
 ("From Below","Darcy Coates",1),
 ("Worm","Wildbow",1),
 ("Perfume","Patrick Süskind",1),
 ("Do Androids Dream of Electric Sheep?","Philip K. Dick",1),
 ("Ubik","Philip K. Dick",1),
 ("My Struggle","Karl Ove Knausgård",1),
 ("The Bride of the Duskwalker","Opal Reyne",1),
 ("Middlemarch","George Eliot",1),
 ("Everyone Poops","Taro Gomi",1),
 ("Feel the Fear and Do It Anyway","Susan Jeffers",1),
 ("The Gulag Archipelago","Aleksandr Solzhenitsyn",1),
 ("Trainspotting","Irvine Welsh",1),
 ("Red Queen","Victoria Aveyard",1),
 ("Underworld","Don DeLillo",1),
 ("The Unbearable Lightness of Being","Milan Kundera",1),
 ("The Hike","Drew Magary",1),
 ("Around the World in Eighty Days","Jules Verne",1),
 ("Vita Nostra","Marina & Sergey Dyachenko",1),
 ("A Practical Guide to Evil","ErraticErrata",1),
 ("Medicine Walk","Richard Wagamese",1),
 ("The Shadow of the Wind","Carlos Ruiz Zafón",1),
 ("Black Powder War","Naomi Novik",1),
 ("The Labyrinth Gate","Alis A. Rasmussen",1),
 ("Nausicaä of the Valley of the Wind","Hayao Miyazaki",1),
 ("My Teen Romantic Comedy SNAFU","Wataru Watari",1),
 ("Endurance","Alfred Lansing",1),
 ("Conclave","Robert Harris",1),
 ("The Magelands Epic","Christopher Mitchell",1),
 ("The Winter King","Bernard Cornwell",1),
 ("The Lords of Discipline","Pat Conroy",1),
 ("Shōgun","James Clavell",1),
 ("The Winds of War","Herman Wouk",1),
]

rows = sorted(({"title": t, "author": a, "mentions": m} for t, a, m in D),
              key=lambda r: (-r["mentions"], r["title"].lower()))
json.dump({"thread": THREAD, "rows": rows}, open("addictive.json", "w"),
          ensure_ascii=False, separators=(",", ":"))
print(len(rows), "books;", sum(r["mentions"] for r in rows), "recommendations")
