# -*- coding: utf-8 -*-
"""r/AskReddit — "What is the single best episode of television you've ever seen?"

Ranked by UPVOTES, not by how many people named it — the first list here counted
that way, and the reason is the thread. At 18,206 comments it cannot be read; but
`?depth=1` returns the top-level answers with their scores, and on a thread this
size the score *is* the crowd. 19,000 people pressed the arrow on Chernobyl. No
mention-count available from a partial read could be a better measure than that.

Where several people gave the same episode, the scores are added and the row says
how many separate answers it took.
"""
import json, re, collections, urllib.parse

THREAD = {
    "q": "What is the single best episode of television you've ever seen?",
    "url": "https://www.reddit.com/r/AskReddit/comments/13hkokt/what_is_the_single_best_episode_of_television/",
}

# pattern -> (episode, series). Order matters: first match wins.
M = [
 (r"vichnaya|memory eternal|chernobyl", "Vichnaya Pamyat", "Chernobyl"),
 (r"bastogne", "Bastogne", "Band of Brothers"),
 (r"ozymandias", "Ozymandias", "Breaking Bad"),
 (r"you only move twice|hank scorpio", "You Only Move Twice", "The Simpsons"),
 (r"make love,? not warcraft", "Make Love, Not Warcraft", "South Park"),
 (r"charlie work", "Charlie Work", "It's Always Sunny in Philadelphia"),
 (r"work outing", "The Work Outing", "The IT Crowd"),
 (r"who goes there|s1 ?e4 of true detective|true detective s01", "Who Goes There", "True Detective"),
 (r"zuko alone", "Zuko Alone", "Avatar: The Last Airbender"),
 (r"\bblink\b", "Blink", "Doctor Who"),
 (r"bent neck lady", "The Bent Neck Lady", "The Haunting of Hill House"),
 (r"two storms", "Two Storms", "The Haunting of Hill House"),
 (r"red wedding|rains of castamere", "The Rains of Castamere", "Game of Thrones"),
 (r"remedial chaos", "Remedial Chaos Theory", "Community"),
 (r"top banana", "Top Banana", "Arrested Development"),
 (r"paintball", "Modern Warfare", "Community"),
 (r"my lunch", "My Lunch", "Scrubs"),
 (r"my screw ?-?up|scrubs season 8 finale", "My Screw Up", "Scrubs"),
 (r"vincent and the doctor|vincent van gogh episode|vincent van gogh|van gogh", "Vincent and the Doctor", "Doctor Who"),
 (r"pine barrens", "Pine Barrens", "The Sopranos"),
 (r"monorail", "Marge vs. the Monorail", "The Simpsons"),
 (r"san junipero", "San Junipero", "Black Mirror"),
 (r"uss callister", "USS Callister", "Black Mirror"),
 (r"nosedive", "Nosedive", "Black Mirror"),
 (r"goodbye,? farewell|good bye, farewell|final (episode|show) of m\.?a\.?s\.?h|last episode of m\.?a\.?s\.?h|final epsode of mash|mash final", "Goodbye, Farewell and Amen", "M*A*S*H"),
 (r"band geeks", "Band Geeks", "SpongeBob SquarePants"),
 (r"out of gas", "Out of Gas", "Firefly"),
 (r"pale moon ?light", "In the Pale Moonlight", "Star Trek: Deep Space Nine"),
 (r"last of us|long,? long time|bill and frank|nick offerman|gay love story", "Long, Long Time", "The Last of Us"),
 (r"grandma simpson|mother simpson", "Mother Simpson", "The Simpsons"),
 (r"cpr episode", "Stress Relief", "The Office"),
 (r"stress relief", "Stress Relief", "The Office"),
 (r"\b33\b.?-?battlestar|\"33\" battlestar", "33", "Battlestar Galactica"),
 (r"where do you think we are", "My Screw Up", "Scrubs"),
 (r"janet\(s\)", "Janet(s)", "The Good Place"),
 (r"jeremy berimy|jeremy bearimy", "Jeremy Bearimy", "The Good Place"),
 (r"finale of the good place", "Whenever You're Ready", "The Good Place"),
 (r"two cathedrals|2 cathedrals", "Two Cathedrals", "The West Wing"),
 (r"407|proxy authentication", "407 Proxy Authentication Required", "Mr. Robot"),
 (r"mr\.? plow", "Mr. Plow", "The Simpsons"),
 (r"finale of severance|season 1 finale of severance", "The We We Are", "Severance"),
 (r"late phillip j fry|late philip j\.? fry", "The Late Philip J. Fry", "Futurama"),
 (r"kemper hug|mindhunter", "Episode 10", "Mindhunter"),
 (r"view from halfway down", "The View from Halfway Down", "BoJack Horseman"),
 (r"free churro", "Free Churro", "BoJack Horseman"),
 (r"clone wars|order 66", "Victory and Death", "Star Wars: The Clone Wars"),
 (r"three stories", "Three Stories", "House"),
 (r"six feet under finale|finale of six feet under|everyone's waiting", "Everyone's Waiting", "Six Feet Under"),
 (r"the visitor", "The Visitor", "Star Trek: Deep Space Nine"),
 (r"inner light", "The Inner Light", "Star Trek: The Next Generation"),
 (r"bluey.*rain\b|\brain\b.*bluey", "Rain", "Bluey"),
 (r"sleepytime", "Sleepytime", "Bluey"),
 (r"the constant", "The Constant", "Lost"),
 (r"pilot for westworld|bicameral mind", "The Original", "Westworld"),
 (r"kiksuya", "Kiksuya", "Westworld"),
 (r"connor'?s wedding|connors wedding", "Connor's Wedding", "Succession"),
 (r"pizza delivery", "Pizza Delivery", "SpongeBob SquarePants"),
 (r"pilot (episode )?(to|of) lost|first episode of lost", "Pilot", "Lost"),
 (r"through the looking glass", "Through the Looking Glass", "Lost"),
 (r"home\b.*x-?files|deformed guy from chernobyl", "Home", "The X-Files"),
 (r"blessing way", "The Blessing Way", "The X-Files"),
 (r"plan and execution", "Plan and Execution", "Better Call Saul"),
 (r"black ?adder", "Goodbyeee", "Blackadder Goes Forth"),
 (r"the suitcase", "The Suitcase", "Mad Men"),
 (r"derry girls", "The Agreement", "Derry Girls"),
 (r"nightman cometh", "The Nightman Cometh", "It's Always Sunny in Philadelphia"),
 (r"one way out", "One Way Out", "Andor"),
 (r"rix road", "Rix Road", "Andor"),
 (r"andor", "One Way Out", "Andor"),
 (r"rocinante|the pella", "Babylon's Ashes", "The Expanse"),
 (r"gaugamela", "Gaugamela", "The Expanse"),
 (r"fleabag", "Episode 1", "Fleabag"),
 (r"battle of the bastards", "Battle of the Bastards", "Game of Thrones"),
 (r"hardhome", "Hardhome", "Game of Thrones"),
 (r"blackwater", "Blackwater", "Game of Thrones"),
 (r"winds of winter|season 6 episode 10", "The Winds of Winter", "Game of Thrones"),
 (r"international assassin", "International Assassin", "The Leftovers"),
 (r"the box.*brooklyn|brooklyn nine", "The Box", "Brooklyn Nine-Nine"),
 (r"mizumono|second season of hannibal", "Mizumono", "Hannibal"),
 (r"twin peaks.*part 8|the return part 8", "Part 8", "Twin Peaks: The Return"),
 (r"peep show", "Wedding", "Peep Show"),
 (r"ronny|lily", "ronny/lily", "Barry"),
 (r"bowling", "Bowling", "Malcolm in the Middle"),
 (r"\breview\b.*bear|the bear", "Review", "The Bear"),
 (r"sound of her wings", "The Sound of Her Wings", "The Sandman"),
 (r"sandman.*episode 6|hope that's the way death", "The Sound of Her Wings", "The Sandman"),
 (r"marine biologist", "The Marine Biologist", "Seinfeld"),
 (r"the contest", "The Contest", "Seinfeld"),
 (r"chinese restaurant", "The Chinese Restaurant", "Seinfeld"),
 (r"library cop|the library", "The Library", "Seinfeld"),
 (r"no soup for you|the soup nazi", "The Soup Nazi", "Seinfeld"),
 (r"the strike|festivus", "The Strike", "Seinfeld"),
 (r"the limo", "The Limo", "Seinfeld"),
 (r"the opposite", "The Opposite", "Seinfeld"),
 (r"not that there'?s anything wrong|jerry and george are gay", "The Outing", "Seinfeld"),
 (r"final episode of the americans|last episode of the americans", "START", "The Americans"),
 (r"\bhush\b", "Hush", "Buffy the Vampire Slayer"),
 (r"once more with feeling|musical episode of buffy", "Once More, with Feeling", "Buffy the Vampire Slayer"),
 (r"the body.*buffy", "The Body", "Buffy the Vampire Slayer"),
 (r"prophecy girl", "Prophecy Girl", "Buffy the Vampire Slayer"),
 (r"becoming part 2", "Becoming, Part 2", "Buffy the Vampire Slayer"),
 (r"darmok", "Darmok", "Star Trek: The Next Generation"),
 (r"the drumhead", "The Drumhead", "Star Trek: The Next Generation"),
 (r"best of both worlds", "The Best of Both Worlds", "Star Trek: The Next Generation"),
 (r"all good things", "All Good Things...", "Star Trek: The Next Generation"),
 (r"trials and tribbl|trials and tribul", "Trials and Tribble-ations", "Star Trek: Deep Space Nine"),
 (r"trailer park boys", "The Bare Pimp Project", "Trailer Park Boys"),
 (r"first episode of the walking dead|days gone by", "Days Gone Bye", "The Walking Dead"),
 (r"tip to tip", "Optimal Tip-to-Tip Efficiency", "Silicon Valley"),
 (r"will'?s dad|fresh prince|how come he don'?t want me", "Papa's Got a Brand New Excuse", "The Fresh Prince of Bel-Air"),
 (r"nightmare at 20,?000", "Nightmare at 20,000 Feet", "The Twilight Zone"),
 (r"newhart", "The Last Newhart", "Newhart"),
 (r"broodwich", "The Broodwich", "Aqua Teen Hunger Force"),
 (r"fish called selma", "A Fish Called Selma", "The Simpsons"),
 (r"22 short|steamed hams", "22 Short Films About Springfield", "The Simpsons"),
 (r"clown college|krusty", "Homie the Clown", "The Simpsons"),
 (r"attack on titan season 3 episode 19|hero,? attack on titan|attack on titan", "Hero", "Attack on Titan"),
 (r"arcane", "The Monster You Created", "Arcane"),
 (r"titus pullo", "The Spoils", "Rome"),
 (r"study in pink", "A Study in Pink", "Sherlock"),
 (r"scandal in belgravia", "A Scandal in Belgravia", "Sherlock"),
 (r"first episode of sherlock", "A Study in Pink", "Sherlock"),
 (r"life on mars", "Episode 1", "Life on Mars"),
 (r"marshal'?s? dad|how i met your mother", "Bad News", "How I Met Your Mother"),
 (r"if-then-else", "If-Then-Else", "Person of Interest"),
 (r"white tulip", "White Tulip", "Fringe"),
 (r"sozin'?s comet", "Sozin's Comet", "Avatar: The Last Airbender"),
 (r"turkeys could fly|turkeys away|turkey giveaway", "Turkeys Away", "WKRP in Cincinnati"),
 (r"running up that hill|master of puppets|stranger things season 4|season 4 finale of stranger", "Dear Billy", "Stranger Things"),
 (r"french mistake", "The French Mistake", "Supernatural"),
 (r"swan song", "Swan Song", "Supernatural"),
 (r"first episode of the newsroom|newsroom", "We Just Decided To", "The Newsroom"),
 (r"pilot of ozark", "Sugarwood", "Ozark"),
 (r"heaven sent", "Heaven Sent", "Doctor Who"),
 (r"almost people", "The Almost People", "Doctor Who"),
 (r"eleventh hour", "The Eleventh Hour", "Doctor Who"),
 (r"midnight", "Midnight", "Doctor Who"),
 (r"wandavision", "The Series Finale", "WandaVision"),
 (r"bob'?s burgers.*christmas", "Christmas in the Car", "Bob's Burgers"),
 (r"art crawl", "Art Crawl", "Bob's Burgers"),
 (r"why we fight", "Why We Fight", "Band of Brothers"),
 (r"twin peaks: episode 1|twin peaks.*pilot", "Pilot", "Twin Peaks"),
 (r"pilot and the finale of justified|justified", "Fire in the Hole", "Justified"),
 (r"watchmen|extraordinary being", "This Extraordinary Being", "Watchmen"),
 (r"frasier.*bikes|learn to ride bikes", "The Two Mrs. Cranes", "Frasier"),
 (r"finale of house|series finale of house", "Everybody Dies", "House"),
 (r"red john|the mentalist", "Red John's Rules", "The Mentalist"),
 (r"jurassic bark", "Jurassic Bark", "Futurama"),
 (r"meanwhile", "Meanwhile", "Futurama"),
 (r"roswell that ends well", "Roswell That Ends Well", "Futurama"),
 (r"luck of the fryrish|game of tones", "The Luck of the Fryrish", "Futurama"),
 (r"sold under sin|deadwood", "Sold Under Sin", "Deadwood"),
 (r"chuckle'?s? funeral|mary tyler moore", "Chuckles Bites the Dust", "The Mary Tyler Moore Show"),
 (r"magnum pi|did you see the sun rise", "Did You See the Sunrise?", "Magnum, P.I."),
 (r"bad travelling|love, death", "Bad Travelling", "Love, Death & Robots"),
 (r"first episode of er|be still my heart|love'?s labor lost", "Love's Labor Lost", "ER"),
 (r"parks and rec|the fight", "The Fight", "Parks and Recreation"),
 (r"rick james|chappelle", "Charlie Murphy's True Hollywood Stories", "Chappelle's Show"),
 (r"season 2 finale mandalorian|mandalorian", "The Rescue", "The Mandalorian"),
 (r"teddy perkins", "Teddy Perkins", "Atlanta"),
 (r"follies of the living", "Follies of the Living — Concerns of the Dead", "M*A*S*H"),
 (r"peekaboo", "Peekaboo", "Breaking Bad"),
 (r"face off", "Face Off", "Breaking Bad"),
 (r"felina|finale of breaking bad|last 8 minutes of breaking bad", "Felina", "Breaking Bad"),
 (r"fawlty towers", "The Germans", "Fawlty Towers"),
 (r"the germans", "The Germans", "Fawlty Towers"),
 (r"cleaning up|the wire", "Cleaning Up", "The Wire"),
 (r"one where everyone finds out", "The One Where Everybody Finds Out", "Friends"),
 (r"one where no one is ready", "The One Where No One's Ready", "Friends"),
 (r"only murders", "The Boy from 6B", "Only Murders in the Building"),
 (r"a private life", "A Private Life", "Six Feet Under"),
 (r"murder house", "Pilot", "American Horror Story"),
 (r"dinner party", "Dinner Party", "The Office"),
 (r"office .*series finale|finale.*the office", "Finale", "The Office"),
 (r"the prisoner", "Once Upon a Time", "The Prisoner"),
 (r"bad batch", "Plan 99", "Star Wars: The Bad Batch"),
 (r"pilot episode of the shield|the shield", "Pilot", "The Shield"),
 (r"bob newhart show", "The Last Newhart", "Newhart"),
 (r"barney miller", "Hash", "Barney Miller"),
 (r"cliff is on jeopardy", "What Is... Cliff Clavin?", "Cheers"),
 (r"final episode of cheers", "One for the Road", "Cheers"),
 (r"as i have always been|agents of shield", "As I Have Always Been", "Agents of S.H.I.E.L.D."),
 (r"the cage|the menagerie", "The Menagerie", "Star Trek"),
 (r"adventure time", "Come Along with Me", "Adventure Time"),
 (r"19-2", "School", "19-2"),
 (r"roseanne", "Terms of Estrangement", "Roseanne"),
 (r"the pacific", "Okinawa", "The Pacific"),
 (r"taikwondo champ|barry", "710N", "Barry"),
 (r"here comes a thought|steven universe", "Mindful Education", "Steven Universe"),
 (r"pilot of firefly|firefly", "Serenity", "Firefly"),
 (r"ted lasso", "All Apologies", "Ted Lasso"),
 (r"peaky blinders", "Season 2 finale", "Peaky Blinders"),
 (r"dark - first|dark\b", "Enden ist der Anfang", "Dark"),
 (r"taxi!", "Reverend Jim: A Space Odyssey", "Taxi"),
]

rows = [l.rstrip("\n").split("\t", 2) for l in open("/tmp/tvans.tsv") if l.count("\t") >= 2]
RX = [(re.compile(p, re.I), e, s) for p, e, s in M]

agg = collections.defaultdict(lambda: {"votes": 0, "answers": 0})
unmatched = []
for u, p, b in rows:
    for rx, ep, se in RX:
        if rx.search(b):
            k = (se, ep)
            agg[k]["votes"] += int(p)
            agg[k]["answers"] += 1
            break
    else:
        unmatched.append((int(p), b))

D = sorted(((se, ep, v["votes"], v["answers"]) for (se, ep), v in agg.items()),
           key=lambda r: -r[2])
print(len(D), "episodes;", sum(r[2] for r in D), "upvotes counted")
print(len(unmatched), "answers matched nothing;", sum(p for p, _ in unmatched), "upvotes dropped")
for p, b in sorted(unmatched, reverse=True)[:12]:
    print(f"   dropped {p:>6}  {b[:80]}")
json.dump(D, open("/tmp/tvrows.json", "w"), ensure_ascii=False)
for se, ep, v, n in D[:20]:
    print(f"{v:>7}  {ep}  —  {se}  ({n})")
