"""r/MusicRecommendations — "Recommend me the best songs you've EVER listened to"

A second music tally, and structurally the opposite of the first one. "The most
beautiful song" got people converging on a handful of answers; "the best song
you've ever heard" gets 200 people naming 200 different things, because it is a
question about them rather than about the songs.

Counting, same rule as the book and film tallies: by distinct redditor, naming
counts and agreeing counts, quoting a lyric does not. Where someone listed a
pile of favourites, all of them count — the question invited it. Live versions
and covers are kept as the person named them ("Heart's Stairway to Heaven at the
Kennedy Center" is not the Led Zeppelin recording, and the difference is the
whole reason they picked it).
"""
import csv
import json
from collections import defaultdict

THREAD = {
 "q": "Recommend me the best songs you've EVER listened to",
 "site": "Reddit · r/MusicRecommendations", "year": 2025,
 "meta": "109 points",
 "url": "https://www.reddit.com/r/MusicRecommendations/comments/1k98z1q/recommend_me_the_best_songs_youve_ever_listened_to/",
}

# redditor -> [(song, artist), ...]
B = {
"Entire_Papaya8505": [("Stairway to Heaven (Heart, live at the Kennedy Center Honors)", "Heart")],
"ApprehensiveNet3213": [("Stairway to Heaven (Heart, live at the Kennedy Center Honors)", "Heart"),
  ("Blackbird", "The Beatles"), ("Goodbye Yellow Brick Road", "Elton John"),
  ("Nightswimming", "R.E.M."), ("America", "Simon & Garfunkel")],
"BeneGurl": [("Stairway to Heaven (Heart, live at the Kennedy Center Honors)", "Heart")],
"Roosterfish33": [("Stairway to Heaven (Heart, live at the Kennedy Center Honors)", "Heart")],
"lijojosef": [("Stairway to Heaven (Heart, live at the Kennedy Center Honors)", "Heart")],
"SoftBoiled15": [("God Only Knows", "The Beach Boys"), ("Sea Stories", "Sturgill Simpson")],
"DeePeeMac": [("God Only Knows", "The Beach Boys")],
"Particular_Maybe8485": [("God Only Knows", "The Beach Boys"), ("Hurricane Season", "Trombone Shorty"),
  ("Golden Slumbers / Carry That Weight / The End", "The Beatles")],
"Prestigious-Curve-30": [("The Silence", "Manchester Orchestra")],
"Agitated_Tone_3528": [("The Silence", "Manchester Orchestra")],
"dadsyrhinowhite": [("Bankrobber", "The Clash"), ("All or Nothing", "Small Faces"),
  ("Down in the Tube Station at Midnight", "The Jam"), ("Stupid Marriage", "The Specials"),
  ("Won't Get Fooled Again", "The Who"), ("This Is How It Feels", "Inspiral Carpets"),
  ("There Is a Light That Never Goes Out", "The Smiths")],
"Fit_Scientist8949": [("Down in the Tube Station at Midnight", "The Jam")],
"jayjaynorcross": [("Purple Rain", "Prince")],
"Least-Quail216": [("Purple Rain", "Prince")],
"_AmyAtHome_": [("Gimme Shelter", "The Rolling Stones")],
"isz4345": [("Gimme Shelter", "The Rolling Stones"), ("Light My Fire", "The Doors")],
"Dunnowhatevs": [("Sympathy for the Devil", "The Rolling Stones")],
"EvitaPuppy": [("Sympathy for the Devil", "The Rolling Stones")],
"APrimaDonna": [("Sympathy for the Devil", "The Rolling Stones")],
"ja20481": [("No Excuses", "Alice in Chains"), ("River of Deceit", "Mad Season")],
"spamtardeggs": [("Wake Up", "Alice in Chains")],
"StandbytoStandby33": [("Mountain Jam", "The Allman Brothers Band")],
"RicEl2": [("Will the Circle Be Unbroken", "The Allman Brothers Band")],
"thecuz1963": [("Bridge Over Troubled Water", "Simon & Garfunkel")],
"Osibruh": [("Rain", "The Beatles")],
"Dogestyle123": [("Rain", "The Beatles"), ("A Day in the Life", "The Beatles")],
"Vladimir4521": [("“Heroes”", "David Bowie")],
"Pumpkins1971": [("Transdermal Celebration", "Ween"), ("Bullet Train to Iowa", "Puscifer"),
  ("Exactly What Nobody Wanted", "Jeffrey Lewis")],
"Few_Substance280": [("Baba O'Riley", "The Who")],
"Kliptik81": [("Time", "Pink Floyd"), ("The Chain", "Fleetwood Mac")],
"famousroadkill": [("I'm Expanding My Mind", "Superdrag"), ("Feel Me Flow", "Naughty by Nature"),
  ("Oxygen", "Swans"), ("Cherry Blossom Clinic Revisited", "The Move"),
  ("Map Ref. 41°N 93°W", "Wire"), ("Hothouse", "The Sound")],
"Superb-Inflation5018": [("Map Ref. 41°N 93°W", "Wire")],
"Longjumping_Bee1479": [("How to Disappear Completely", "Radiohead")],
"PBJellyion": [("Frou-Frou Foxes in Midsummer Fires", "Cocteau Twins")],
"dinozaurs": [("Fotzepolitic", "Cocteau Twins")],
"Jonxb": [("All the Love in the World", "The Outfield")],
"Only-Walrus797": [("The Ballad of El Goodo", "Big Star"), ("In from Japan", "Madison Cunningham")],
"AxewomanK156": [("The Ballad of El Goodo", "Big Star")],
"forzaNYC": [("Svefn-g-englar", "Sigur Rós"), ("Your Hand in Mine", "Explosions in the Sky"),
  ("The World Is Our ___", "This Will Destroy You"), ("Like Starlight into Day", "Hammock"),
  ("Graveyard Girl", "M83"), ("Under the Pressure", "The War on Drugs"),
  ("Lay Low", "My Morning Jacket"), ("Exit Music (For a Film)", "Radiohead"),
  ("Release", "Pearl Jam"), ("Guns Out", "Young the Giant"), ("Heavy Chevy", "Alabama Shakes"),
  ("When My Train Pulls In", "Gary Clark Jr."), ("Texas Flood", "Stevie Ray Vaughan")],
"huddy112591": [("When My Train Pulls In", "Gary Clark Jr."), ("Gimme Love", "The Elovaters"),
  ("Safe", "Bay Ledges")],
"Western_Plantain_210": [("I and Love and You", "The Avett Brothers"), ("T.B. Sheets", "Van Morrison")],
"mpcvyy3": [("Disorder", "Joy Division")],
"wgbeethree": [("Long as I Can See the Light", "Creedence Clearwater Revival")],
"Most_Image_21": [("Victim of Changes", "Judas Priest"), ("Thick as a Brick", "Jethro Tull"),
  ("Magnum Opus", "Kansas"), ("The Ivory Gate of Dreams", "Fates Warning"),
  ("Green Grass and High Tides", "The Outlaws"), ("Master of Puppets", "Metallica")],
"WideConsideration431": [("Green Grass and High Tides", "The Outlaws")],
"Cr3amyMcCheese": [("Green Grass and High Tides", "The Outlaws")],
"Origin_uk47": [("The Great Gig in the Sky", "Pink Floyd"), ("Something in the Way", "Nirvana"),
  ("Brothers in Arms", "Dire Straits"), ("Hurt", "Johnny Cash")],
"Electronic-Aside-164": [("The Scientist", "Coldplay")],
"avoiddead": [("The Scientist", "Coldplay")],
"Chachoulepou": [("Nobody Loves You", "Garbage")],
"PerspectiveRude9555": [("Is It Really You (Loathe cover)", "Sleep Token")],
"Some-Glove-3629": [("Storm", "Godspeed You! Black Emperor"),
  ("Hasta Que Te Conocí", "Juan Gabriel"), ("Taswell", "C418"),
  ("Shit Talk", "Sufjan Stevens"), ("Between the Bars", "Elliott Smith"), ("Bye.", "J Dilla")],
"Dogstickers420": [("Between the Bars", "Elliott Smith")],
"Optimal-Ad-7074": [("Sunday Mornin' Comin' Down", "Kris Kristofferson"),
  ("I'm a Man You Don't Meet Every Day", "The Pogues"),
  ("Fairytale of New York", "The Pogues"), ("Dublin Blues", "Guy Clark"),
  ("A New England", "Kirsty MacColl"), ("Never Going Back Again", "Fleetwood Mac")],
"ScorpionTrance": [("The Temples of Syrinx", "Rush")],
"Ok_District2853": [("Freewill", "Rush"), ("Franklin's Tower", "Grateful Dead")],
"Zero-Credibility": [("Mannish Boy", "Muddy Waters"), ("When the Levee Breaks", "Led Zeppelin"),
  ("I Am the Resurrection", "The Stone Roses")],
"RidiculousSucculent": [("The Chauffeur", "Duran Duran")],
"Slight-Opening-8327": [("Machine Gun", "Jimi Hendrix"), ("Castles Made of Sand", "Jimi Hendrix"),
  ("Voodoo Child (Slight Return)", "Jimi Hendrix"), ("Bold as Love", "Jimi Hendrix")],
"SnakeMaster5": [("The Crowing", "Coheed and Cambria")],
"Don_Frika_Del_Prima": [("Hey", "Pixies")],
"mpd0g1m": [("Sultans of Swing", "Dire Straits")],
"hnyredditguy": [("Sultans of Swing", "Dire Straits"), ("Northern Downpour", "Panic! at the Disco"),
  ("September", "Earth, Wind & Fire"), ("Aja", "Steely Dan"),
  ("Black Water", "The Doobie Brothers")],
"mpd9idx": [("Hunger Strike", "Temple of the Dog"), ("Bitter Sweet Symphony", "The Verve"),
  ("Teardrop", "Massive Attack"), ("Just Like Heaven", "The Cure"),
  ("So Here We Are", "Bloc Party")],
"Ok-Cicada-1880": [("Hunger Strike", "Temple of the Dog")],
"irukandjee": [("Comfortably Numb", "Pink Floyd"), ("Seven Nation Army", "The White Stripes"),
  ("Nothing Compares 2 U", "Sinéad O'Connor")],
"dan1boy1": [("Common People", "Pulp")],
"Big_Acanthaceae9752": [("Moonage Daydream", "David Bowie")],
"Chruno33": [("Comfortably Numb", "Pink Floyd"), ("Starless", "King Crimson"),
  ("Wasted Years", "Iron Maiden"), ("One", "Metallica"), ("The Drapery Falls", "Opeth"),
  ("Forget Not", "Ne Obliviscaris"), ("Chapter IV", "Estatic Fear"),
  ("Sun of Nothing", "Between the Buried and Me"),
  ("In the Shadow of Our Pale Companion", "Agalloch")],
"odduc": [("Too Bad", "Rival Sons")],
"Automatic-Plum-2854": [("Vinushka", "Dir En Grey")],
"bitb_": [("Condemnation", "Depeche Mode")],
"KOTF0025": [("Original Suffer Head", "Fela Kuti"), ("Decades", "Joy Division"),
  ("Uncertain Smile", "The The"), ("I Feel You", "Depeche Mode")],
"HavSomLov4YoBrothr": [("Welcome to Earth (Pollywog)", "Sturgill Simpson")],
"hazelbuttlatte": [("It's Called: Freefall", "Rainbow Kitten Surprise")],
"Far-Telephone-7432": [("Alvin Row", "Animal Collective")],
"Klaus-Heisler": [("Always with Me, Always with You", "Joe Satriani")],
"aasasss32": [("Don't Talk (Put Your Head on My Shoulder)", "The Beach Boys")],
"Honest_Letter_3409": [("Romantic Warrior", "Return to Forever")],
"mpcio76": [("Sever the Blight", "hemlocke springs")],
"_kanonmatsubara_": [("Death & Romance", "Magdalena Bay"), ("Sun Bleached Flies", "Ethel Cain")],
"DirtyMagicNL": [("Iron Sky", "Paolo Nutini")],
"InteractionFast9213": [("Iron Sky", "Paolo Nutini"), ("A Change Is Gonna Come", "Otis Redding"),
  ("Achilles Last Stand", "Led Zeppelin"), ("Mattering Ram", "Penny and Sparrow")],
"towatei1990": [("Action", "Nadine Sutherland & Terror Fabulous")],
"mpcki32": [("Headfirst Slide into Cooperstown on a Bad Bet", "Fall Out Boy")],
"BMEUP-Captain_Kirk": [("Riviera Paradise", "Stevie Ray Vaughan"), ("Aja", "Steely Dan"),
  ("Echoes", "Pink Floyd")],
"NoLongerATeacher": [("Train in Vain", "The Clash"), ("Rocky Mountain Way", "Joe Walsh"),
  ("Fast Car", "Tracy Chapman"), ("Powderfinger", "Neil Young"),
  ("Cleaning Windows", "Van Morrison")],
"bijazthadwarf": [("Strawberry Letter 23", "Shuggie Otis")],
"mxckalxcka": [("Take Me Back to Eden", "Sleep Token")],
"Rp3rkins": [("Tumbling Dice", "The Rolling Stones")],
"Deep20779": [("Best Friend", "Sofi Tukker")],
"T-Mart-J": [("Brave New World", "Kalandra")],
"Famous-Ad6576": [("We Drift Like Worried Fire", "Godspeed You! Black Emperor")],
"Typical-Can-1033": [("Oh Baby", "LCD Soundsystem")],
"Rdub412": [("I Love My Parents", "Buckethead")],
"One-Future2932": [("Forget Her", "Jeff Buckley")],
"Pristine_Noise1516": [("Burn My Shadow", "UNKLE")],
"the_third_sourcerer": [("Alone", "Stars"), ("You as You Were", "Shearwater"),
  ("Your Eyes Were Shining", "The Jealous Sound")],
"kaleb_post_kaleb": [("Hysteria", "Def Leppard"), ("Lyin' Eyes", "Eagles"),
  ("Estranged", "Guns N' Roses")],
"handsomerube": [("You and I", "Jeff Buckley")],
"Cautious_Homework628": [("Mojo Pin", "Jeff Buckley")],
"jajanken_bacon": [("Rapture", "Hurt")],
"queenwarx": [("White Chocolate Space Egg", "Liz Phair")],
"1cilldude": [("If I Fell", "The Beatles"), ("Bat Out of Hell", "Meat Loaf"),
  ("Hi De Ho Man", "Cab Calloway"), ("Brandy (You're a Fine Girl)", "Looking Glass")],
"aukinon": [("No Quarter", "Led Zeppelin"), ("Grace, Too", "The Tragically Hip")],
"Impossible-Science-4": [("The Wreck of the Edmund Fitzgerald", "Gordon Lightfoot"),
  ("X Amount of Words", "Blue October"), ("Forever Autumn", "Justin Hayward"),
  ("(Don't Fear) The Reaper", "Blue Öyster Cult"),
  ("Veteran of the Psychic Wars", "Blue Öyster Cult"), ("Hurricane", "Bob Dylan"),
  ("Point Blank", "Bruce Springsteen"), ("(Ghost) Riders in the Sky", "Johnny Cash"),
  ("Hurt", "Johnny Cash"), ("Tragedy", "Bee Gees")],
"Bellahaddid": [("Mirrors", "Justin Timberlake"), ("We Are the Champions", "Queen"),
  ("Habits (Stay High)", "Tove Lo"), ("Can You Feel My Heart", "Bring Me the Horizon")],
"PizzaAshamed7730": [("Barton Hollow", "The Civil Wars")],
"OldCreezy": [("Rest of My Life", "Less Than Jake"), ("Dismantle Me", "The Distillers"),
  ("Trying to Find a Balance", "Atmosphere")],
"ramonescreatin": [("Waterloo Sunset", "The Kinks"), ("Days", "The Kinks")],
"Icy-Swim-9861": [("98", "Meeko Brando")],
"mpd0f3e": [("The Long and Winding Road", "The Beatles")],
"ISwallowedABug412": [("The Long and Winding Road", "The Beatles")],
"bojangles-AOK": [("Shake Some Action", "Flamin' Groovies")],
"slitherbob": [("In My Bed (live)", "Amy Winehouse"), ("Tears Dry on Their Own", "Amy Winehouse")],
"Material-Fondant3792": [("If We Were Vampires", "Jason Isbell")],
"posterfluffhead": [("You Enjoy Myself", "Phish")],
"Alternative_Age3058": [("Bella Ciao", "GIMS, Vitaa, Slimane & Dadju")],
"brightears": [("Lover, You Should've Come Over", "Jeff Buckley"),
  ("Fade into You", "Mazzy Star"), ("Comfortably Numb", "Pink Floyd"),
  ("New Slang", "The Shins"), ("Most of the Time", "Bob Dylan"),
  ("The Man Comes Around", "Johnny Cash"),
  ("Subterranean Homesick Alien", "Radiohead")],
"TerribleBiscotti7751": [("Release", "Grace Potter")],
"guidomista44443": [("White Ball", "Miracle Musical"),
  ("Mosquito Song", "Queens of the Stone Age")],
"kevstershill": [("RATATATA", "Electric Callboy & BABYMETAL"), ("One Day Like This", "Elbow"),
  ("Rime of the Ancient Mariner", "Iron Maiden")],
"dukemcrae": [("The Air That I Breathe", "k.d. lang")],
"seeking_spice402": [("Seven Bridges Road", "Eagles"), ("Mr. Tambourine Man", "Bob Dylan"),
  ("Tiny Dancer", "Elton John")],
"singtomeinfrench1": [("Nights", "Frank Ocean"), ("What Is Life", "George Harrison"),
  ("Everything in Its Right Place", "Radiohead"), ("Still D.R.E.", "Dr. Dre"),
  ("Undone – The Sweater Song", "Weezer"), ("My Father My King", "Mogwai")],
"mpfgzyr": [("Everything in Its Right Place", "Radiohead")],
"panconjamon1996": [("Ah… Te Vi Entre Las Luces", "La Máquina de Hacer Pájaros")],
"VD3NFS1216": [("Widower", "The Dillinger Escape Plan"), ("A Flood of Light", "Rolo Tomassi"),
  ("Grim Heart/Black Rose", "Converge"), ("Satan in the Wait", "Daughters"),
  ("Dissociation", "The Dillinger Escape Plan")],
"mfdoombolt": [("Lateralus", "Tool"), ("Right in Two", "Tool"), ("Reckoner", "Radiohead"),
  ("Benzie Box", "Danger Doom"), ("Sometime Around Midnight", "The Airborne Toxic Event"),
  ("Call It Dreaming", "Iron & Wine")],
"nogozone6969": [("Sometime Around Midnight", "The Airborne Toxic Event")],
"BezequillePotter": [("Midnight Blue", "Lou Gramm")],
"Nicklas8844": [("Charlie", "Red Hot Chili Peppers"), ("Savior", "Rise Against"),
  ("A Lot More Free", "Max McNown")],
"Ok-Truck-5526": [("Fall on Me", "R.E.M.")],
"Tweedie_NL": [("Nervous (The Ooh Song)", "Gavin James"), ("Move", "The Mamas"),
  ("Sowieso", "Mark Forster"), ("Je te laisserai des mots", "Patrick Watson"),
  ("To Build a Home", "The Cinematic Orchestra")],
"Baldude863xx": [("From the Beginning", "Emerson, Lake & Palmer")],
"Honest_Maybe847": [("Exodus", "Bob Marley")],
"Fyrebeard": [("Dream Odyssey", "MONO")],
"so_dang_big": [("More Than a Feeling", "Boston"), ("Come Sail Away", "Styx")],
"BubblyPassage6483": [("More Than a Feeling", "Boston")],
"stabbingrabbit": [("Take Me Home, Country Roads", "John Denver"),
  ("What a Wonderful World", "Louis Armstrong")],
"Busy_Psychology6621": [("Close to the Edge", "Yes")],
"pj67rocks": [("Presence of the Lord", "Blind Faith")],
"LongjumpingTone3544": [("Cypress Grove", "Clutch"), ("Floods", "Pantera"),
  ("Dirt", "Alice in Chains")],
"dlc0027": [("Pacific Street", "Hem"), ("King of the Jailhouse", "Aimee Mann"),
  ("Young Pilgrims", "The Shins")],
"PurpleButthole666": [("Vajra", "Secret Chiefs 3")],
"UnableContest2669": [("Ball of Confusion", "The Temptations"), ("The Snake", "Al Wilson"),
  ("The Night", "Frankie Valli & The Four Seasons")],
"BohnerSoup": [("Mayonaise", "The Smashing Pumpkins"),
  ("Backwards Marathon", "Between the Buried and Me"), ("Oblivion", "Mastodon")],
"Green_Independent119": [("Smalltown Boy", "Bronski Beat")],
"Thatanndradona": [("The Lost Words Blessing", "Julie Fowlis & Karine Polwart")],
"11db11": [("I Don't Wanna Be an Asshole Anymore", "The Menzingers")],
"Dakotaraptor123": [("Into the Endless Night (live)", "Parannoul")],
"Disastrous-Comb-3446": [("I'd Love to Change the World", "Ten Years After"),
  ("Nights on Broadway", "Bee Gees")],
"LatinHoser": [("Lost Cause", "Beck"), ("I Went to the Store One Day", "Father John Misty"),
  ("Angeles", "Elliott Smith"), ("Poses", "Rufus Wainwright"), ("Sisyphus", "Andrew Bird"),
  ("50 Ways to Leave Your Lover", "Paul Simon"), ("Domingo no Parque", "Gilberto Gil"),
  ("Can't Find My Way Home", "Blind Faith"), ("Cálice", "Chico Buarque"),
  ("Travessia", "Milton Nascimento"), ("Terra", "Caetano Veloso"),
  ("(Nothing But) Flowers", "Talking Heads"), ("Thirteen", "Big Star"),
  ("My Iron Lung", "Radiohead"), ("Do You Realize??", "The Flaming Lips"),
  ("Impossible Germany", "Wilco"), ("Hold On", "Tom Waits"),
  ("Last Goodbye", "Jeff Buckley"), ("Pink Moon", "Nick Drake"),
  ("Red Right Hand", "Nick Cave"), ("I Know It's Over", "The Smiths"),
  ("Nobody Does It Better", "Carly Simon")],
"AlgySnorkel": [("Spectral Mornings", "Steve Hackett"), ("Echoes", "Camel")],
"Remote-Ad-430": [("Con te partirò", "Andrea Bocelli"), ("Somebody to Love", "Queen")],
"BaronPorg": [("Cause = Time", "Broken Social Scene"), ("Weird Fishes/Arpeggi", "Radiohead"),
  ("Dirt in the Ground", "Tom Waits")],
"mpe5zlm": [("Champagne Coast", "Blood Orange")],
"TopCommercial2185": [("October", "Evanescence")],
"Iceman_creed": [("No Expectations", "The Rolling Stones"),
  ("Wayfaring Stranger", "Runaway Planet"), ("I Need You", "Lynyrd Skynyrd"),
  ("Low Man's Lyric", "Metallica"), ("Road to Nowhere", "Ozzy Osbourne"),
  ("Dirty Old Town", "The Pogues"), ("Solitude", "Black Sabbath")],
"SEARCHFORWHATISGOOD": [("I Was Young When I Left Home", "Bob Dylan"),
  ("Bird on the Wire", "Leonard Cohen"), ("America", "Simon & Garfunkel"),
  ("The Story", "Brandi Carlile"), ("Crawling Back to You", "Tom Petty"),
  ("Martha", "Tom Waits"), ("Release", "Pearl Jam"), ("All My Love", "Noah Kahan")],
"no-sleeping-": [("Atlantic City", "The Band")],
"hall0800": [("Golden Slumbers", "The Beatles")],
"Automatic-Count2092": [("Spanish Pipedream", "John Prine")],
"ComprehensiveEast376": [("Subdivisions", "Rush")],
"goldprofred": [("India", "The Psychedelic Furs")],
"Acrobatic_Skirt3827": [("So What", "Miles Davis"), ("West End Blues", "Louis Armstrong"),
  ("Mood Indigo", "Duke Ellington"), ("Take Five", "The Dave Brubeck Quartet")],
"idontknowyou2294": [("Mack the Knife (live in Berlin)", "Ella Fitzgerald")],
"According-Boat-1838": [("Let It Be", "The Beatles")],
"prettygood_not_bad": [("Kids and Dogs", "David Crosby")],
"celticteal": [("No Time", "The Guess Who"), ("September", "Earth, Wind & Fire"),
  ("Don't Worry Baby", "The Beach Boys"), ("Come and Get Your Love", "Redbone"),
  ("Without You", "Harry Nilsson"), ("Daisy Jane", "America"),
  ("Dancing in the Moonlight", "King Harvest"), ("This Is the Last Time", "Keane")],
"Current_Vanilla_3565": [("Heat Above", "Greta Van Fleet")],
"RealBatmanArkham": [("Get a Hold", "A Tribe Called Quest")],
"Classic-Quote3884": [("Anesthesia", "Type O Negative"), ("Driven Under", "Seether"),
  ("Love, Hate, Love", "Alice in Chains")],
"mukn4on": [("Alleluia", "Randall Thompson")],
"Odif12321": [("American Pie", "Don McLean"), ("In My Life", "The Beatles"),
  ("Why Does Love Got to Be So Sad", "Derek and the Dominos")],
"daishukanami": [("Come On! Feel the Illinoise!", "Sufjan Stevens")],
"Middle-Letterhead760": [("(Sittin' On) The Dock of the Bay", "Otis Redding"),
  ("Drift Away", "Dobie Gray"), ("Love Song", "Tesla")],
"DreadtheSnoFro": [("Under Pressure", "Queen & David Bowie")],
"gjk14": [("Telegraph Road", "Dire Straits")],
"Waltpanorama": [("Unfinished Sympathy", "Massive Attack")],
"AbbreviationsBorn276": [("Inertia Creeps", "Massive Attack")],
"BirthdayComplex1243": [("Fussing and Fighting", "Bob Marley"),
  ("African Herbsman", "Bob Marley"), ("Dancing Shoes", "Bob Marley")],
"powerwentout": [("Rats", "METZ"), ("We're So Ugly", "Hornet Leg"),
  ("Terminal Jape", "Thee Oh Sees"), ("Diversion", "Ty Segall"), ("Off", "Meatbodies"),
  ("untitled 03", "Kendrick Lamar")],
"Educational-Fig-1594": [("Motorbike", "Poppy")],
"CommanderBagels": [("The Place Where He Inserted the Blade", "Black Country, New Road"),
  ("White Noise", "Will Wood"),
  ("The Tallest Man, the Broadest Shoulders", "Sufjan Stevens")],
"BentoBoxNoir": [("Omoide in My Head (last live)", "Number Girl")],
"HairFabulous5094": [("What's Going On", "Marvin Gaye"), ("Ventura", "Lucinda Williams"),
  ("Gloria", "Patti Smith")],
"IvanLendl87": [("Duk Koo Kim", "Sun Kil Moon"), ("Moments of Pleasure", "Kate Bush"),
  ("The Caves of Altamira", "Steely Dan"), ("Under Pressure", "Queen & David Bowie"),
  ("In My Life", "The Beatles"), ("Black Water", "The Doobie Brothers"),
  ("Road", "Nick Drake"), ("Simple Man", "Lynyrd Skynyrd"), ("Mr. Big", "Free"),
  ("Only Us", "Peter Gabriel")],
"TopBid7531": [("Desolation", "Xelesiah")],
"Sinistermarmalade": [("Heaven and Hell", "Bible Black"), ("Invoker", "Eternal Champion"),
  ("Seventeen", "The Vestals")],
"Nomotorbike": [("Line of Fire", "Junip")],
"oggupito": [("Midday", "Michael Brook")],
"rocketsauce2112": [("The Tracks of My Tears", "Smokey Robinson"),
  ("You Really Got a Hold on Me", "Smokey Robinson"),
  ("Desolation Row", "Bob Dylan"), ("It's All Over Now, Baby Blue", "Bob Dylan")],
"Responsible-Bison258": [("Dancing with the Moonlit Knight", "Genesis")],
"Harringt0n": [("Three Days", "Jane's Addiction")],
"JamesonSchaefer": [("The Soundmaker", "Rodrigo y Gabriela")],
"dillydallyaleey": [("Sound & Color", "Alabama Shakes")],
"RussellAlden": [("Good Luck, Babe!", "Chappell Roan"), ("Lovefool", "The Cardigans"),
  ("Sara", "Fleetwood Mac"), ("Whole Lotta Love", "Led Zeppelin"),
  ("The Real Me", "The Who"), ("Jessica", "The Allman Brothers Band"),
  ("Born to Run", "Bruce Springsteen"),
  ("Can't You Hear Me Knocking", "The Rolling Stones"),
  ("He Stopped Loving Her Today", "George Jones"), ("I Feel Love", "Donna Summer")],
"FGC_RG3_MARVEL": [("Colorful", "tripleS")],
"DifficultCat2000": [("Glory Box", "Portishead"), ("Pink Moon", "Nick Drake"),
  ("Have You Ever Seen the Rain", "Creedence Clearwater Revival"),
  ("Apologize", "The Warning"), ("Pussywillows, Cattails", "Kenny Rankin")],
"Fated2LuvBTS": [("Méditation from Thaïs", "Jules Massenet")],
"ThatJ4ke": [("The Little Things Give You Away", "Linkin Park"),
  ("A Haven with Two Faces", "Spiritbox"), ("Dementia", "ERRA"),
  ("Wax Wings", "Periphery")],
"PTD27": [("Lucretia My Reflection", "The Sisters of Mercy")],
"jtmcad14": [("Takin' It to the Streets", "The Doobie Brothers"),
  ("Hello It's Me", "Todd Rundgren"), ("Jazzman", "Carole King"),
  ("She's Gone", "Hall & Oates"),
  ("Every Little Thing She Does Is Magic", "The Police"),
  ("Electric Feel", "MGMT"), ("Time Out of Mind", "Steely Dan")],
"rgators": [("Raspberry Beret", "Prince")],
"rodgee": [("Blackbird", "The Beatles")],
"WestwardSquall": [("Friends", "Shadrew")],
"United-Profit-1139": [("Parking Lots", "Plums")],
"Monkeymann2112": [("Nights in White Satin", "The Moody Blues")],
"SaintsFan3386": [("Left of the Dial", "The Replacements")],
"DreamingOfHope3489": [("Station to Station", "David Bowie")],
"Charming_Falcon8458": [("Summer Wind", "Frank Sinatra")],
"ItsDaniCalifornia": [("Jigsaw Falling into Place", "Radiohead")],
"elsem7": [("Exit Music (For a Film)", "Radiohead"),
  ("The Sound of Silence", "Simon & Garfunkel"), ("One More Light", "Linkin Park"),
  ("Nutshell", "Alice in Chains"), ("Master of Puppets", "Metallica"),
  ("Hallelujah", "Leonard Cohen"), ("Wish You Were Here", "Pink Floyd"),
  ("November Rain", "Guns N' Roses")],
"RoofThink7762": [("Moonlight Mile", "The Rolling Stones")],
"AnakinJH": [("Panic Paralysis", "Future Palace")],
"livbird46": [("Invincible", "Tool")],
"Own-Fox-7792": [("Anything Anything", "Dramarama")],
"TheLesbianQueer": [("Don't Threaten Me with a Good Time", "Panic! at the Disco")],
"wearehostingcom": [("FAMJAM4000", "Jordan Ward")],
"Feeling-Buffalo2914": [("Local Hero", "Mark Knopfler"), ("Square Hammer", "Ghost")],
"No_Tea5664": [("This Is a Low", "Blur")],
"callowruse": [("Everything's Ruined", "Faith No More")],
"cryptorambo69": [("Cocaine and Abel", "Amigo the Devil")],
"long_strange_trip_67": [("Terrapin Station", "Grateful Dead")],
"Lostin15801": [("Mr. Blue Sky", "Electric Light Orchestra")],
"scjs115": [("Giorgio by Moroder", "Daft Punk")],
"texasrigger": [("Marquee Moon", "Television")],
"ToxicTonberry": [("Dead Rope Machine", "Rishloo")],
"_dontseeme": [("Ava", "Le Son")],
"mph2vj6": [("The Sound of Silence", "Disturbed")],
"Specific_Pirate1346": [("Take My Breath", "The Weeknd")],
"Fritz1601": [("Song of the Stars", "Dead Can Dance")],
"WonderfulGuarantee73": [("I Won't See You Tonight Part 1", "Avenged Sevenfold")],
"OGHighway": [("The Tale of Jenny & Screech", "Ren")],
"offmychestthrowawsy": [("One", "Metallica"),
  ("Stop the World I Want to Goof Off", "Summerbruise"),
  ("Losing My Religion", "R.E.M."), ("The Winner Takes It All", "ABBA"),
  ("CLOSER", "Waterparks")],
"Ancient_Visual_7451": [("Broken", "Seether")],
}

counts = defaultdict(set)
meta = {}
for user, songs in B.items():
    for song, artist in songs:
        counts[(song, artist)].add(user)

rows = sorted(
    ({"song": s, "artist": a, "mentions": len(u)} for (s, a), u in counts.items()),
    key=lambda r: (-r["mentions"], r["song"].lower()))

json.dump({"thread": THREAD, "rows": rows}, open("bestsongs.json", "w"),
          ensure_ascii=False, separators=(",", ":"))

# The Spotify importer wants Year,Artist,Track,Album — it only reads two of them.
with open("best-songs.csv", "w", newline="") as fh:
    w = csv.writer(fh)
    w.writerow(["Year", "Artist", "Track", "Album"])
    for r in rows:
        w.writerow(["", r["artist"], r["song"], ""])

once = sum(1 for r in rows if r["mentions"] == 1)
print(len(rows), "songs from", len(B), "redditors;",
      sum(r["mentions"] for r in rows), "mentions;", once, "named once")
for r in rows[:12]:
    print(f'  {r["mentions"]}x  {r["song"]} — {r["artist"]}')
