"""r/Music — "Best Song Ever Written (in your opinion)?"

The biggest thread on the site, and the one that behaves least like the others.
3,865 comments. Reddit only serves the top 500, so this was captured five times
over — best, top, new, old and controversial — and merged, because each ordering
surfaces a different slice and every single fetch truncates before the end. What
is counted here is therefore a large sample, not the whole thread, and the note
on the list says so.

The question is also doing something the other music threads aren't. It asks for
the best song *written*, not the best song heard, and a good chunk of the thread
argues about whether that's a different question at all. One person says the
quiet part out loud: everyone is naming their favourite track rather than
answering. That argument is the interesting thing about this list, and it is why
it sits next to the other three rather than duplicating them.

Counting, same rule as everywhere else on this site: by distinct redditor,
naming counts and agreeing counts, quoting a lyric does not. Comments that named
an artist, an album or a genre rather than a song are dropped, as are the
several hundred replies that are conversation rather than a vote. The asker's
own pick — Avalanche by Leonard Cohen — is excluded, though other people naming
it are counted.
"""
import csv
import json
from collections import defaultdict

THREAD = {
    "q": "Best Song Ever Written (in your opinion)?",
    "site": "Reddit · r/Music",
    "year": 2022,
    "meta": "2,396 points · 3,865 comments",
    "url": "https://www.reddit.com/r/Music/comments/z3uxx6/best_song_ever_written_in_your_opinion/",
}

# redditor -> [(song, artist), ...]
B = {
"Spartanjaws": [("God Only Knows", "The Beach Boys")],
"slip_this_in": [("Don't Worry Baby", "The Beach Boys")],
"Zaphod_042": [("God Only Knows", "The Beach Boys")],
"gasjetruss04": [("God Only Knows", "The Beach Boys")],
"DSOTM": [("God Only Knows", "The Beach Boys")],
"chels182": [("Don't Worry Baby", "The Beach Boys")],
"Mikadostudios": [("Good Vibrations", "The Beach Boys")],
"Head_Buyer_526": [("Heroes and Villains", "The Beach Boys")],
"Ash_LLR": [("Surf's Up", "The Beach Boys")],
"3TH4N_C00P3R": [("California Dreamin'", "The Beach Boys")],
"pikaboo8": [("There Is a Light That Never Goes Out", "The Smiths")],
"sherribobbins": [("There Is a Light That Never Goes Out", "The Smiths"),
  ("How Soon Is Now?", "The Smiths")],
"Dependent-Fix-574": [("Asleep", "The Smiths")],
"i_heart_pastathey": [("Gimme Shelter", "The Rolling Stones"),
  ("How Soon Is Now?", "The Smiths")],
"copperdomebodhi": [("Ode to Joy", "Beethoven"), ("A Day in the Life", "The Beatles")],
"FadeToBlackSun": [("Ode to Joy", "Beethoven")],
"wartsnall1985": [("Clair de Lune", "Debussy"),
  ("I Only Have Eyes for You", "The Flamingos")],
"Substantial_Cold2385": [("Clair de Lune", "Debussy")],
"Odd_Comparison9310": [("Für Elise", "Beethoven")],
"BlitheringEediot": [("The Boxer", "Simon & Garfunkel")],
"sawyerkittyHad": [("The Boxer", "Simon & Garfunkel")],
"dusktilhon": [("The Boxer", "Simon & Garfunkel")],
"MrSaturnboink": [("American Tune", "Paul Simon")],
"rdotrdot7789": [("The Only Living Boy in New York", "Simon & Garfunkel")],
"YDS696969": [("Scarborough Fair", "Simon & Garfunkel")],
"Kodamurphy": [("Homeward Bound", "Simon & Garfunkel")],
"Falcon3492": [("The Sound of Silence", "Simon & Garfunkel")],
"Uranus_Hz": [("Bridge Over Troubled Water", "Simon & Garfunkel")],
"dustydooshe": [("Bridge Over Troubled Water", "Simon & Garfunkel")],
"Tossed_Away_1776": [("Hurt", "Nine Inch Nails")],
"No-River-9295": [("Hurt", "Nine Inch Nails")],
"Thunder_Mug": [("Hurt", "Nine Inch Nails")],
"jo_ker94": [("Hurt", "Nine Inch Nails")],
"mr18above": [("Hurt", "Nine Inch Nails")],
"Defiant-Ad5932": [("Into the Mystic", "Van Morrison")],
"MissMannerss": [("Sweet Thing", "Van Morrison")],
"mostlygroovy": [("Thunder Road", "Bruce Springsteen")],
"Timb3r_6": [("Thunder Road", "Bruce Springsteen")],
"re10pect": [("Thunder Road", "Bruce Springsteen")],
"AshgarPN": [("Born to Run", "Bruce Springsteen")],
"Rampage12114": [("Free Bird", "Lynyrd Skynyrd")],
"Bryn79": [("The River", "Bruce Springsteen")],
"hambonecharlie": [("Jackson Cage", "Bruce Springsteen")],
"BeginningWater3553": [("Tunnel of Love", "Bruce Springsteen")],
"Flaggstaff": [("Time", "Pink Floyd")],
"MrCleanyaHands": [("Time", "Pink Floyd")],
"Existing-Calendar200": [("Time", "Pink Floyd")],
"SaintedDemon69": [("Time", "Pink Floyd")],
"TicklerVikingPilot": [("Time", "Pink Floyd"), ("Illegal Smile", "John Prine")],
"Sherlockstopstealing": [("Time", "Pink Floyd")],
"4evaDolphinLuv": [("Grace", "Jeff Buckley")],
"green-d20": [("Shine On You Crazy Diamond", "Pink Floyd")],
"zyygh": [("Shine On You Crazy Diamond", "Pink Floyd")],
"Strange-Read9026": [("Shine On You Crazy Diamond", "Pink Floyd")],
"Gwtheyrn": [("Wish You Were Here", "Pink Floyd")],
"hisfirewithin": [("Wish You Were Here", "Pink Floyd")],
"Solidus_Bock": [("Wish You Were Here", "Pink Floyd")],
"unlessthemoon": [("Wish You Were Here", "Pink Floyd")],
"TheCrowsonator4ever": [("Ten Years Gone", "Led Zeppelin"),
  ("Wish You Were Here", "Pink Floyd")],
"BigBillSmash": [("Comfortably Numb", "Pink Floyd")],
"Iucidium": [("Comfortably Numb", "Pink Floyd")],
"NectarineExisting194": [("Echoes", "Pink Floyd")],
"Own-Tutor-5256": [("Echoes", "Pink Floyd")],
"UnrealismOfFilms": [("Echoes", "Pink Floyd")],
"VarietyNice9496": [("Echoes", "Pink Floyd")],
"dogtaxi812": [("Time", "Pink Floyd"), ("Gimme Shelter", "The Rolling Stones"),
  ("Comfortably Numb", "Pink Floyd"), ("Brothers in Arms", "Dire Straits"),
  ("Funeral for a Friend / Love Lies Bleeding", "Elton John")],
"damp_paper_towel": [("(Don't Fear) The Reaper", "Blue Öyster Cult")],
"colirado": [("The Weight", "The Band")],
"JunkieBravo": [("If We Were Vampires", "Jason Isbell and the 400 Unit")],
"-OccamsLaser": [("If We Were Vampires", "Jason Isbell and the 400 Unit")],
"realteamme": [("Alabama Pines", "Jason Isbell")],
"kbergstr": [("Speed Trap Town", "Jason Isbell")],
"RepairDependent3607": [("Speed Trap Town", "Jason Isbell")],
"Leeian44": [("If It Takes a Lifetime", "Jason Isbell")],
"Pierson230": [("Amazing Grace", "traditional")],
"tardypartyy": [("Amazing Grace", "traditional")],
"RiverofGrass": [("Amazing Grace", "traditional")],
"elonbrave": [("Amazing Grace", "traditional")],
"Jezzyrulescoco": [("The Killing Moon", "Echo & the Bunnymen")],
"Accomplished-Wish680": [("The Killing Moon", "Echo & the Bunnymen")],
"RadioBoy93": [("Bring On the Dancing Horses", "Echo & the Bunnymen")],
"elithemoonwalker": [("Don't Think Twice, It's All Right", "Bob Dylan")],
"TheOneHundredEmoji": [("Sara", "Bob Dylan")],
"EazyP87": [("Tangled Up in Blue", "Bob Dylan")],
"Tranesblues": [("Waitin' Around to Die", "Townes Van Zandt")],
"Leperchaun913": [("(Quicksilver) Daydreams of Maria", "Townes Van Zandt")],
"JustinArmuchee": [("Tecumseh Valley", "Townes Van Zandt")],
"Plane_Particular_731": [("Marie", "Townes Van Zandt")],
"MarikoKonjou": [("Pancho and Lefty", "Townes Van Zandt")],
"omgitsbillyfrick": [("Angel from Montgomery", "John Prine")],
"MBDf_Doc": [("Sam Stone", "John Prine")],
"DevinBelow": [("Positively 4th Street", "Bob Dylan")],
"swimbackdanman": [("With God on Our Side", "Bob Dylan")],
"Disastrous-Nebula606": [("My Back Pages", "Bob Dylan")],
"leadhound": [("American Pie", "Don McLean")],
"Lunndonbridge": [("American Pie", "Don McLean")],
"bigsignwave": [("American Pie", "Don McLean")],
"brockollirobb": [("American Pie", "Don McLean"),
  ("Casimir Pulaski Day", "Sufjan Stevens")],
"No_Construction_5108": [("Vincent", "Don McLean")],
"platypus_tuxedo": [("Somewhere Over the Rainbow", "Harold Arlen")],
"trevorap": [("Somewhere Over the Rainbow", "Harold Arlen")],
"megatheriumburger": [("Hummingbird", "Wilco")],
"-O-0-0-O-": [("Rainbow Connection", "Kermit the Frog")],
"gwm3d": [("Rainbow Connection", "Kermit the Frog")],
"Mosbelu": [("Sultans of Swing", "Dire Straits")],
"killerk14": [("Sultans of Swing", "Dire Straits")],
"JimHeuer40": [("Romeo and Juliet", "Dire Straits")],
"islandsimian": [("Telegraph Road", "Dire Straits")],
"AccidentalPundit": [("Money for Nothing", "Dire Straits")],
"prdunham1993": [("Vienna", "Billy Joel")],
"yllomcullen": [("Vienna", "Billy Joel")],
"reformedjerkoff": [("And So It Goes", "Billy Joel")],
"Dangerous-Bed7278": [("Piano Man", "Billy Joel")],
"bigcinty": [("Scenes from an Italian Restaurant", "Billy Joel")],
"StargazerLuke": [("Scenes from an Italian Restaurant", "Billy Joel")],
"goldknight1": [("For the Longest Time", "Billy Joel")],
"RiseOfTheRevenge": [("Life on Mars?", "David Bowie")],
"bowie567": [("Ashes to Ashes", "David Bowie")],
"ginger_kitty97": [("Five Years", "David Bowie")],
"Mazcal": [("Grandma's Hands", "Bill Withers")],
"Dhd710": [("Ain't No Sunshine", "Bill Withers")],
"strychnine8575": [("Ain't No Sunshine", "Bill Withers")],
"Oldslim": [("Enjoy the Silence", "Depeche Mode")],
"benadrylpill": [("In My Life", "The Beatles")],
"trumpsiranwar": [("In My Life", "The Beatles")],
"mmonroejohnson": [("In My Life", "The Beatles")],
"One-Leadership-3580": [("In My Life", "The Beatles")],
"cool_sex_falcon": [("Watermelon in Easter Hay", "Frank Zappa")],
"Supermannyfraker": [("If You Could Read My Mind", "Gordon Lightfoot")],
"Fickle_Atmosphere_36": [("The Wreck of the Edmund Fitzgerald", "Gordon Lightfoot")],
"dotto48_": [("Landslide", "Fleetwood Mac")],
"pRhymeTime333": [("Landslide", "Fleetwood Mac")],
"daydreamingingblue": [("Landslide", "Fleetwood Mac"),
  ("Sign of the Times", "Harry Styles")],
"edgor123": [("Go Your Own Way", "Fleetwood Mac")],
"bboobbear": [("Never Going Back Again", "Fleetwood Mac")],
"pastIife": [("Sara", "Fleetwood Mac")],
"escudonbk": [("The Wind Cries Mary", "Jimi Hendrix"),
  ("Castles Made of Sand", "Jimi Hendrix")],
"88667695634914163284": [("Little Wing", "Jimi Hendrix")],
"maraheinze": [("Chariots of Fire", "Vangelis"), ("Free Bird", "Lynyrd Skynyrd"),
  ("Hallelujah", "Leonard Cohen")],
"swany5": [("Cat's in the Cradle", "Harry Chapin")],
"slipkid092": [("Baba O'Riley", "The Who")],
"StonkeyTonk666999": [("How to Disappear Completely", "Radiohead")],
"btsarmyVbtsarmy": [("How to Disappear Completely", "Radiohead")],
"murked2312": [("Black Hole Sun", "Soundgarden")],
"roknrollaz198": [("Black Hole Sun", "Soundgarden")],
"kapachow": [("Soul Meets Body", "Death Cab for Cutie")],
"notjosemanuel": [("What Sarah Said", "Death Cab for Cutie")],
"outtastudy": [("Grapevine Fires", "Death Cab for Cutie")],
"Umbilical_Syllables_": [("Blackbird", "The Beatles")],
"oddmetre": [("Stairway to Heaven", "Led Zeppelin")],
"ADSWNJ": [("Stairway to Heaven", "Led Zeppelin")],
"Doc-Goop": [("Stairway to Heaven", "Led Zeppelin")],
"qawsedrf12": [("One", "Metallica")],
"NeedleworkerRich2788": [("One", "Metallica")],
"Outrageous-Sock-752": [("One", "Metallica")],
"ender_198": [("Fade to Black", "Metallica"), ("Cemetery Gates", "Pantera")],
"Slow-Sink3984": [("Wichita Lineman", "Glen Campbell")],
"liveguy2112": [("Wichita Lineman", "Glen Campbell")],
"NewUnityModder": [("Wichita Lineman", "Glen Campbell")],
"kommienezuspadt42": [("Strange Fruit", "Billie Holiday")],
"elola": [("Bohemian Rhapsody", "Queen")],
"Apprehensive_Home688": [("Bohemian Rhapsody", "Queen")],
"HarryHavok96": [("Bohemian Rhapsody", "Queen")],
"Theatrplattie": [("Bohemian Rhapsody", "Queen")],
"yodleyahehu1": [("Bohemian Rhapsody", "Queen")],
"DungeonBoi": [("Bohemian Rhapsody", "Queen")],
"wbash75": [("Bohemian Rhapsody", "Queen")],
"ArgetDota": [("Bohemian Rhapsody", "Queen")],
"beatnickk": [("Bohemian Rhapsody", "Queen")],
"menacelive": [("Bohemian Rhapsody", "Queen")],
"TheSocialGadfly": [("Bohemian Rhapsody", "Queen")],
"Chainwreck": [("Bohemian Rhapsody", "Queen")],
"bobbypkp": [("Another One Bites the Dust", "Queen")],
"ExternalPiglet1": [("Under Pressure", "Queen & David Bowie")],
"Top_Operation_6499": [("We Are the Champions", "Queen")],
"not_me_much": [("The House of the Rising Sun", "The Animals")],
"NoProduct7097": [("Yesterday", "The Beatles")],
"BrownJamba30": [("Yesterday", "The Beatles")],
"wivsta": [("Yesterday", "The Beatles")],
"Smirkly": [("A Change Is Gonna Come", "Sam Cooke")],
"OriginalTiny9892": [("A Change Is Gonna Come", "Sam Cooke")],
"SuspiciousLeading898": [("Crying", "Roy Orbison")],
"Black__Dove": [("In Dreams", "Roy Orbison")],
"NightDriver3370": [("Pyramid Song", "Radiohead")],
"No_Badger_830": [("Jigsaw Falling Into Place", "Radiohead")],
"Y3ll0w_Sn0w4": [("Paranoid Android", "Radiohead")],
"Exotic-Wish5248": [("Weird Fishes / Arpeggi", "Radiohead")],
"Personal-Nobody5501": [("House of Cards", "Radiohead")],
"Next-Rip3809": [("As", "Stevie Wonder")],
"xizzy7": [("Sir Duke", "Stevie Wonder")],
"Landalf": [("Superstition", "Stevie Wonder"), ("Hey Ya!", "OutKast")],
"Unusual-War-9697": [("Tuesday's Gone", "Lynyrd Skynyrd"),
  ("The Boxer", "Simon & Garfunkel"), ("L.A. Woman", "The Doors"),
  ("Skateaway", "Dire Straits")],
"Krypto_Kal-El": [("The Shrine / An Argument", "Fleet Foxes")],
"imso_preeti": [("Reflections", "The Neighbourhood")],
"Texas-Lazarusman70": [("Hallelujah", "Leonard Cohen")],
"urbannoangeldecay": [("Hallelujah", "Leonard Cohen")],
"daishomaster": [("Hallelujah", "Leonard Cohen")],
"ndorox": [("Hallelujah", "Leonard Cohen")],
"MurkDiesel": [("Hallelujah", "Leonard Cohen"),
  ("The Times They Are A-Changin'", "Bob Dylan")],
"_Nikolai_Gogol": [("Famous Blue Raincoat", "Leonard Cohen")],
"fblinders13": [("Famous Blue Raincoat", "Leonard Cohen")],
"sc_we_ol": [("Hallelujah", "Leonard Cohen"), ("Unchained Melody", "The Righteous Brothers"),
  ("Exit Music (For a Film)", "Radiohead")],
"rarerumrunner": [("Sunday Morning", "The Velvet Underground"),
  ("No Surprises", "Radiohead"), ("Moonage Daydream", "David Bowie"),
  ("Avalanche", "Leonard Cohen")],
"Mountain_Air_3698": [("Best Song Ever", "One Direction")],
"VermicelliOwn1698": [("Best Song Ever", "One Direction")],
"Powrug": [("Best Song Ever", "One Direction")],
"Hot_Committee_6679": [("Wait for U", "Future")],
"Unknownmff699": [("Like That", "Future")],
"Spirited_Ad_1655": [("Fourth of July", "Sufjan Stevens")],
"DaveGrohlGirl": [("John Wayne Gacy, Jr.", "Sufjan Stevens")],
"yoitsansell": [("City of Blinding Lights", "U2")],
"halfofzenosparadox": [("One", "U2")],
"flexcloud0": [("One", "U2")],
"emcconnell11": [("One", "U2")],
"Tomm1878": [("Sunday Bloody Sunday", "U2")],
"BuyRevolutionary6358": [("A Day in the Life", "The Beatles")],
"AVnerd117": [("A Day in the Life", "The Beatles")],
"drawingsido": [("A Day in the Life", "The Beatles")],
"layne75": [("A Day in the Life", "The Beatles")],
"SpeedyGoldenberg": [("A Day in the Life", "The Beatles"), ("Mona Lisa", "Lil Wayne")],
"LegLast": [("Human Sadness", "The Voidz")],
"FrostingTop2758": [("My Way", "Frank Sinatra")],
"Minute_Chocolate_451": [("Weekend", "Mac Miller"),
  ("Take Me Out", "Franz Ferdinand")],
"Numerous_Station_759": [("A Seagull & Clouds", "Himiko Kikuchi")],
"OkBreak828": [("God Save the Queen", "Sex Pistols"),
  ("I Remember You", "Ramones")],
"Maleficent-Session81": [("The Four Seasons", "Vivaldi"),
  ("A Song for You", "Donny Hathaway")],
"farfromeverywhere": [("A Song for You", "Ray Charles")],
"ApprehensiveShop8250": [("Ascensionism", "Sleep Token")],
"Quiet_Plenty_2120": [("I Gave You Power", "Nas")],
"Stunning_Ice2939": [("I Can", "Nas")],
"Intelligent_Tale5949": [("Sing About Me, I'm Dying of Thirst", "Kendrick Lamar")],
"Kaylumboi2": [("Sing About Me, I'm Dying of Thirst", "Kendrick Lamar")],
"Monk3ydood": [("Sing About Me, I'm Dying of Thirst", "Kendrick Lamar")],
"The_Truce": [("Alright", "Kendrick Lamar")],
"No-Blueberry-8077": [("DUCKWORTH.", "Kendrick Lamar")],
"treefroggo17": [("Would?", "Alice in Chains")],
"IrishUnknown": [("Nutshell", "Alice in Chains")],
"Wonderful_Jump3909": [("Distant Dreamer", "Duffy")],
"likioc": [("Pancho and Lefty", "Merle Haggard & Willie Nelson"),
  ("Bohemian Rhapsody", "Queen"), ("Runaway", "Kanye West"),
  ("Brandy (You're a Fine Girl)", "Looking Glass")],
"Ok_Hurry_898": [("King for a King", "Will Varley")],
"norcimorci": [("Careless Whisper", "George Michael")],
"simo_nahh": [("Careless Whisper", "George Michael")],
"Allen_Wrench2009": [("Don't Think Twice, It's All Right", "Bob Dylan"),
  ("Still Crazy After All These Years", "Paul Simon"),
  ("God Only Knows", "The Beach Boys"),
  ("Here, There and Everywhere", "The Beatles"),
  ("A Change Is Gonna Come", "Sam Cooke"),
  ("Brown Eyed Girl", "Van Morrison"),
  ("Our House", "Crosby, Stills, Nash & Young"),
  ("Lullabye (Goodnight, My Angel)", "Billy Joel"),
  ("American Pie", "Don McLean"), ("Bohemian Rhapsody", "Queen")],
"nicogmattos_": [("Lover, You Should've Come Over", "Jeff Buckley")],
"Any-Door9688": [("My Own Grave", "As I Lay Dying")],
"KaChing801": [("Gin and Juice", "Snoop Dogg")],
"Jimmersion": [("Takin' It to the Streets", "The Doobie Brothers")],
"QuirkyGuest288": [("Chop Suey!", "System of a Down")],
"Desperate-Ad-273": [("Better Than I", "Joseph: King of Dreams")],
"CalligrapherGreat971": [("Stan", "Eminem")],
"XPMR": [("Sing for the Moment", "Eminem"), ("Stan", "Eminem")],
"all_authored_surface": [("Lose Yourself", "Eminem")],
"Fine_Veterinarian_21": [("Dancing in the Moonlight", "King Harvest")],
"pullmantrip": [("Dancing in the Moonlight", "King Harvest")],
"Key_Instruction_929": [("In the End", "Linkin Park"), ("Imagine", "John Lennon"),
  ("The Sound of Silence", "Disturbed")],
"rentopotato420": [("In the End", "Linkin Park")],
"Flaky-Round-4142": [("Roads Untraveled", "Linkin Park")],
"isitva1711": [("Estranged", "Guns N' Roses")],
"dj1200techniques": [("November Rain", "Guns N' Roses")],
"No-Oil2576": [("Nessun Dorma", "Puccini")],
"prettyoddoz": [("Riches and Wonders", "The Mountain Goats")],
"Irithel-the-marksman": [("Hey Jude", "The Beatles")],
"ComfortableAd6083": [("After All These Years", "Silverchair")],
"ClassicPost9403": [("Summer of '69", "Bryan Adams")],
"South-Specific7095": [("Breaking All Illusions", "Dream Theater")],
"Born-Standard-8193": [("Get Together", "The Youngbloods")],
"Sad_Abalone_4777": [("Hallowed Be Thy Name", "Iron Maiden")],
"DumbAssFissh": [("Wake Up Dead", "Megadeth"),
  ("Stranger in a Strange Land", "Iron Maiden")],
"tavliboy2": [("Bittersweet Symphony", "The Verve")],
"BewareOfFloof": [("Hotel California", "Eagles")],
"Southern_Manager_785": [("Hotel California", "Eagles"),
  ("Family Tree", "Megadeth"), ("Rag Doll", "Aerosmith")],
"Mirabelle_9": [("The Last Resort", "Eagles")],
"Notinyourbushes": [("The Last Resort", "Eagles")],
"Salm0nfish": [("Mr. Blue Sky", "Electric Light Orchestra")],
"gns2g": [("Mr. Blue Sky", "Electric Light Orchestra"),
  ("A Hard Rain's A-Gonna Fall", "Bob Dylan")],
"melloooooooooooooooo": [("505", "Arctic Monkeys")],
"stf2018": [("A Whiter Shade of Pale", "Procol Harum")],
"Daymareman": [("A Whiter Shade of Pale", "Procol Harum")],
"Nylthrm8": [("Night and Day", "Cole Porter")],
"No-Instruction-651": [("90210", "Travis Scott")],
"venomROZE": [("I Miss You", "Blink-182")],
"ApprehensiveCup8596": [("Long Way Home", "Tom Waits")],
"johnnyknack": [("Old Shoes (& Picture Postcards)", "Tom Waits")],
"Zygarde_0p123": [("I'm Yours", "Jason Mraz")],
"Any_Water8550": [("Tribute", "Tenacious D")],
"Masagmarod": [("Tribute", "Tenacious D")],
"osagecountyguns": [("Tribute", "Tenacious D")],
"OGfromaSmallTown": [("Runaway", "Kanye West")],
"stickenstuff": [("Runaway", "Kanye West")],
"Abyss416": [("Gorgeous", "Kanye West")],
"Key-Nefariousness-44": [("Devil in a New Dress", "Kanye West")],
"Character_Project534": [("Mr. Crowley", "Ozzy Osbourne")],
"YouSubstantial498": [("Take On Me", "a-ha"), ("Build a Fire", "Young Ejecta"),
  ("Billie Jean", "Michael Jackson")],
"NyvatL": [("Everybody Wants to Rule the World", "Tears for Fears")],
"DivisionBell1996": [("Everybody Wants to Rule the World", "Tears for Fears")],
"Hayek66": [("Everybody Wants to Rule the World", "Tears for Fears")],
"timelordoftheimpala": [("Shout", "Tears for Fears")],
"Rowdy_Puppy": [("Hummer", "The Smashing Pumpkins"),
  ("Everybody Wants to Rule the World", "Tears for Fears"),
  ("Adagio for Strings", "Samuel Barber")],
"flexytev": [("1979", "The Smashing Pumpkins")],
"Brave_Acadia_1908": [("Simple Man", "Lynyrd Skynyrd")],
"beachboynerf12": [("2112", "Rush")],
"Loose-Alternative-77": [("Face of Melinda", "Opeth")],
"Emma_Awesome12": [("Sweater Weather", "The Neighbourhood")],
"t0x1cpanda16": [("Train Wreck", "James Arthur")],
"Illustrious_Stand062": [("Is This It", "The Strokes")],
"zhyrafa": [("To Be a Man", "Dax")],
"letsgoNYMets9376": [("Love Shack", "The B-52's")],
"Original-Wolf-7250": [("What's Going On", "Marvin Gaye")],
"Remote-Sprinkles9928": [("Ordinary World", "Duran Duran"),
  ("Hell Is Living Without You", "Alice Cooper"),
  ("I Only Have Eyes for You", "The Flamingos")],
"No_Carpenter_1110": [("Imagine", "John Lennon"), ("Hallelujah", "Leonard Cohen"),
  ("The Sound of Silence", "Simon & Garfunkel"),
  ("Fade Into You", "Mazzy Star"), ("The Night We Met", "Lord Huron"),
  ("True Love Will Find You in the End", "Daniel Johnston"),
  ("Under the Milky Way", "The Church"), ("Harvest Moon", "Neil Young"),
  ("Fourth of July", "Sufjan Stevens"), ("Julia Dream", "Pink Floyd")],
"DEADRAIDER420": [("Right in Two", "Tool")],
"A__rian": [("Space Song", "Beach House")],
"starfoxrocks": [("Imagine", "John Lennon")],
"eWBx": [("Imagine", "John Lennon")],
"RedditorNumber679260": [("Imagine", "John Lennon")],
"IamFigjam": [("Imagine", "John Lennon")],
"ranger8913": [("The Long and Winding Road", "The Beatles")],
"Legalize_glue44": [("One Last Breath", "Creed")],
"sandcrawler2": [("Alvin Row", "Animal Collective")],
"broteinsandwich": [("Clairvoyant", "The Story So Far")],
"Expensive-Stuff3781": [("Friend of the Devil", "Grateful Dead")],
"wazserd": [("The Greatest Story Ever Told", "Grateful Dead")],
"marcusaurelius1957": [("Song of the Wind", "Santana"),
  ("Jack Straw", "Grateful Dead"),
  ("I'd Love to Change the World", "Ten Years After")],
"Alive_Protection9021": [("Somebody to Love", "Queen"),
  ("Let's Stay Together", "Al Green")],
"PureMapleSyrup_119": [("Ex-Factor", "Ms. Lauryn Hill")],
"special_leather": [("10,000 Days (Wings Pt. 2)", "Tool")],
"Saplers": [("10,000 Days (Wings Pt. 2)", "Tool")],
"jorahos1": [("Invincible", "Tool")],
"drhay53": [("Lateralus", "Tool")],
"Averen": [("Lateralus", "Tool")],
"tahitidreams": [("46 & 2", "Tool"), ("Stinkfist", "Tool")],
"PM_ur_Rump": [("Third Eye", "Tool")],
"jsharp85": [("Kiss from a Rose", "Seal")],
"Petty_Spaghetti_Yeti": [("I Think It's Going to Rain Today", "Randy Newman")],
"suzannesfarmhouse": [("Taking Water", "Billy Strings")],
"AndrewH-McGillicuddy": [("Reunited", "Wu-Tang Clan")],
"klakkr": [("Left Your Body", "Bad Books")],
"lankymidget15": [("Come as You Are", "Nirvana")],
"chiogb302": [("7 Years", "Lukas Graham")],
"MrsaviPas": [("Gangnam Style", "PSY")],
"13cyanic": [("All Too Well", "Taylor Swift")],
"Photoshop_666": [("All Too Well (10 Minute Version)", "Taylor Swift")],
"giantgorillaballs": [("All Too Well (10 Minute Version)", "Taylor Swift"),
  ("Sing About Me, I'm Dying of Thirst", "Kendrick Lamar"),
  ("Mural", "Lupe Fiasco")],
"ikonet": [("Baby Shark", "Pinkfong")],
"TeeeLi": [("Baby Shark", "Pinkfong")],
"fernando5302": [("Monsters", "All Time Low & Demi Lovato")],
"Ok-Pressure-3879": [("Everchanging", "Rise Against"),
  ("The Ice Is Getting Thinner", "Death Cab for Cutie")],
"smallislandgirl": [("My Humps", "The Black Eyed Peas")],
"RanyaAnusih": [("Jesus of Suburbia", "Green Day")],
"Wain609": [("Good Riddance (Time of Your Life)", "Green Day")],
"TopReception2389": [("My Ding-a-Ling", "Chuck Berry")],
"always777": [("Around the World", "Daft Punk")],
"MarkusRight": [("Californication", "Red Hot Chili Peppers")],
"Machopsdontcry": [("Smile Like You Mean It", "The Killers")],
"CommanderWar64": [("Jenny Was a Friend of Mine", "The Killers")],
"mnarr0ws": [("MMMBop", "Hanson")],
"wolviesaurus": [("Regulate", "Warren G"),
  ("Thorns of Crimson Death", "Dissection")],
"coastermarioguy": [("Axel F", "Crazy Frog")],
"superTwist": [("Sugar Baby Love", "The Rubettes")],
"hotrodmike_": [("Happy Birthday to You", "traditional")],
"Hands-for-maps": [("Happy Birthday to You", "traditional")],
"SupremePooper": [("Happy Birthday to You", "traditional")],
"sketchykg": [("Happy Birthday to You", "traditional")],
"hehaw": [("In the Aeroplane Over the Sea", "Neutral Milk Hotel")],
"dray1033": [("Strawberry Fields Forever", "The Beatles")],
"theripped": [("Blues Run the Game", "Jackson C. Frank")],
"acleverlie421": [("Gucci Gang", "Lil Pump")],
"FlansDigitalDotCom": [("MacArthur Park", "Richard Harris")],
"RiDark_Souls": [("Save Me", "Avenged Sevenfold"),
  ("Victim", "Avenged Sevenfold")],
"Specialist-Report-94": [("The Star-Spangled Banner", "traditional")],
"derekthedomino143": [("Layla", "Derek and the Dominos")],
"Ok-Impress-2222": [("Have You Ever Seen the Rain", "Creedence Clearwater Revival"),
  ("Layla", "Derek and the Dominos")],
"FRESH_MEME_DETECTOR": [("Never Gonna Give You Up", "Rick Astley")],
"Serfalon": [("Snuff", "Slipknot")],
"um8medoit": [("Canon in D", "Pachelbel")],
"nicodicesarezoso": [("Starless", "King Crimson")],
"picknwiggle": [("Epitaph", "King Crimson")],
"sagopalm12": [("Hejira", "Joni Mitchell")],
"infidel99": [("False Alarm", "Joni Mitchell")],
"gpchamb": [("Losing My Religion", "R.E.M.")],
"klophidian": [("Find the River", "R.E.M.")],
"thunnus": [("Find the River", "R.E.M."), ("Sweetness Follows", "R.E.M.")],
"hopeuntilwecant": [("Tiny Dancer", "Elton John")],
"Odd_Responsibility_5": [("She Wolf", "Shakira")],
"nosmelc": [("More Than a Feeling", "Boston")],
"bwm8142": [("Foreplay / Long Time", "Boston")],
"Nafe3344": [("Hook", "Blues Traveler")],
"jsu718": [("Hook", "Blues Traveler")],
"rosh200": [("Cliffs of Dover", "Eric Johnson")],
"theonetowalkinthesun": [("In My Life", "The Beatles")],
"daiwilly": [("Heart of Gold", "Neil Young")],
"Alrighty_Jay": [("Black", "Pearl Jam")],
"dbhanger": [("Reelin' in the Years", "Steely Dan")],
"Le_Goobinatti": [("Deacon Blues", "Steely Dan")],
"Dammitbandit": [("The Idiots Are Taking Over", "NOFX")],
"galvanizedrocknroll": [("Mockingbirds", "Grant Lee Buffalo")],
"Rothko28": [("Do You Realize??", "The Flaming Lips"),
  ("I Am the Resurrection", "The Stone Roses")],
"Leotardleotard": [("Loose", "The Stooges"), ("Sister Ray", "The Velvet Underground")],
"stutterbuddy": [("Fast Car", "Tracy Chapman")],
"VIVXPrefix": [("Fast Car", "Tracy Chapman")],
"Legitimate_Winter_97": [("Fast Car", "Tracy Chapman")],
"efefia": [("Here Comes the Sun", "The Beatles")],
"Outrageous-Ad-7087": [("The Trapeze Swinger", "Iron & Wine")],
"guanwho": [("Call It Dreaming", "Iron & Wine")],
"JoelyRavioli": [("Ripped Pants", "SpongeBob SquarePants")],
"EnthusiasmGlass4739": [("Let It Be", "The Beatles")],
"Born_a_wise_man": [("Detachable Penis", "King Missile")],
"mellowyellowwww": [("Roundabout", "Yes")],
"_SageArt_": [("Close to the Edge", "Yes")],
"Ok-Fudge8848": [("Waterloo Sunset", "The Kinks")],
"danfester": [("If I Can Dream", "Elvis Presley")],
"crf3rd": [("Jesu, Joy of Man's Desiring", "J.S. Bach")],
"PajamaWarriorJohn": [("The Scientist", "Coldplay")],
"Cydonian___FT14X": [("Fix You", "Coldplay")],
"MudFIow": [("After the Storm", "Kali Uchis")],
"starwarsnerd9": [("Everlong", "Foo Fighters")],
"ScreenNo571": [("Everlong", "Foo Fighters")],
"Jonhazen": [("Painters of the Tempest, Pt. II (Triptych Lux)", "Ne Obliviscaris")],
"dixondarling": [("Babylon", "David Gray")],
"PantherEverSoPink": [("The Other Side", "David Gray")],
"theboredsinger": [("Propane Nightmares", "Pendulum")],
"Gwer-101": [("Don't Stop Me Now", "Queen"), ("Highway Star", "Deep Purple"),
  ("Afraid to Shoot Strangers", "Iron Maiden"), ("Gypsy", "Uriah Heep")],
"LanktheMeme": [("SOS", "ABBA")],
"Corb_mac": [("Hard to Find the Words", "Cinderella")],
"korban65": [("Three Days", "Jane's Addiction")],
"Midnight_Oil_": [("You Should Have Seen the Other Guy", "Nathaniel Rateliff")],
"Soup3rTROOP3R": [("Sometime Around Midnight", "The Airborne Toxic Event")],
"BloodBaneBoneBreaker": [("You Are My Sunshine", "traditional")],
"10101010010101010110": [("Love Will Tear Us Apart", "Joy Division")],
"Big_Gullible": [("For a Dancer", "Jackson Browne")],
"Severe-Building244": [("Pavane pour une infante défunte", "Maurice Ravel")],
"Location_Lazy": [("Shape of You", "Ed Sheeran")],
"Money-Pineapple8152": [("Tequila", "The Champs")],
"Canadianeseish": [("Nothing Compares 2 U", "Prince")],
"myincogitoaccount": [("Chasing Cars", "Snow Patrol")],
"EyeHaveNoBanana": [("This River", "JJ Grey")],
"mix3dupkid": [("Tinseltown in the Rain", "The Blue Nile")],
"plattemuilaap": [("Peter Gunn", "Emerson, Lake & Palmer")],
"Scythemag88": [("Homage", "Mild High Club")],
"NewYorkJewbag": [("Cosmic Slop", "Funkadelic")],
"TheKillingMoon30": [("Maggot Brain", "Funkadelic")],
"TeTrico_": [("Alone Again (Naturally)", "Gilbert O'Sullivan")],
"IanMalcoRaptor": [("WAP", "Cardi B")],
"Many_Speaker_5937": [("Pain Remains", "Lorna Shore")],
"kassra25": [("Save Me", "Kadebostany")],
"vikingoalegre850": [("Die Meistersinger von Nürnberg", "Wagner")],
"RZAxlash": [("Interstate Love Song", "Stone Temple Pilots")],
"WhoKeepsYourFlame": [("Like a Rolling Stone", "Bob Dylan"),
  ("Hallelujah", "Jeff Buckley"),
  ("Helplessly Hoping", "Crosby, Stills & Nash")],
"0bl0m0v0": [("Waiting for You", "Nick Cave")],
"Internal-Cookie-1330": [("Believer", "Imagine Dragons")],
"Iceman_creed": [("Outskirts of Heaven", "Warren Zeiders")],
"two1000": [("Was It Something I Said?", "OMD")],
"hdjxacto": [("Vineyard", "Joe Higgs")],
"tanarcuriad": [("Crucify Me", "Bring Me the Horizon")],
"eti_erik": [("Song to the Siren", "This Mortal Coil")],
"listerinebreath": [("Gravity Rides Everything", "Modest Mouse")],
"WhiteNoise421": [("God of Wine", "Third Eye Blind")],
"sid32": [("So What", "Anti-Nowhere League")],
"Errorcode_38": [("Carnival of Rust", "Poets of the Fall")],
"aguayt": [("Torn and Frayed", "The Rolling Stones")],
"archronin": [("Nobody Does It Better", "Carly Simon")],
"Zealjin": [("Sunglasses", "Black Country, New Road")],
"Thinlinebaby": [("Something", "The Beatles"),
  ("What It Feels Like for a Girl", "Madonna")],
"AussiePete51": [("We Gotta Get Out of This Place", "The Animals"),
  ("I Was Only 19", "Redgum"), ("The Anniversary Song", "Al Jolson")],
"Alamander81": [("Unchained Melody", "The Righteous Brothers")],
"hankwinner": [("Unchained Melody", "The Righteous Brothers")],
"wizard_hat_and_staff": [("Caring Is Creepy", "The Shins"),
  ("Giorgio by Moroder", "Daft Punk"), ("Fade Into You", "Mazzy Star"),
  ("Doo Wop (That Thing)", "Ms. Lauryn Hill"),
  ("Crawling Back to You", "Tom Petty"), ("Golden Years", "David Bowie")],
"Scoochh": [("Station to Station", "David Bowie"),
  ("Going to California", "Led Zeppelin"),
  ("With God on Our Side", "Bob Dylan"), ("A Day in the Life", "The Beatles"),
  ("Paranoid Android", "Radiohead")],
"DamonLazer": [("Tomorrow Never Knows", "The Beatles"),
  ("Something", "The Beatles"), ("Eleanor Rigby", "The Beatles"),
  ("Across the Universe", "The Beatles")],
"cleverkid": [("Being Boring", "Pet Shop Boys")],
"penis-muncher785": [("Good Morning, Captain", "Slint")],
"rsmith4025": [("Stardust", "Hoagy Carmichael")],
"RawSewage33": [("Love Song", "Tesla")],
"nicoleeatscheese": [("Everlong", "Foo Fighters")],
"lizardhamster": [("One", "Metallica")],
"Ilvesarahpaulsonalot": [("Wish You Were Here", "Pink Floyd")],
"Infinite-Direction24": [("The Greatest Song Ever", "Pleasantries")],
"Perfect_Response655": [("Resonance", "HOME")],
"jfbrow334": [("To Beat the Devil", "Kris Kristofferson")],
"Strange_Negotiation7": [("Perfect", "Tyler, the Creator")],
"HuptheCuck": [("Bongo Bong", "Manu Chao")],
"Nylthrm8_dupe_guard": [],
}
B.pop("Nylthrm8_dupe_guard")

counts = defaultdict(set)
for user, songs in B.items():
    for song, artist in songs:
        counts[(song, artist)].add(user)

rows = sorted(
    ({"song": s, "artist": a, "mentions": len(u)} for (s, a), u in counts.items()),
    key=lambda r: (-r["mentions"], r["song"].lower()))

json.dump({"thread": THREAD, "rows": rows}, open("bestwritten.json", "w"),
          ensure_ascii=False, separators=(",", ":"))

with open("best-written.csv", "w", newline="") as fh:
    w = csv.writer(fh)
    w.writerow(["Year", "Artist", "Track", "Album"])
    for r in rows:
        w.writerow(["", r["artist"], r["song"], ""])

once = sum(1 for r in rows if r["mentions"] == 1)
print(len(rows), "songs from", len(B), "redditors;",
      sum(r["mentions"] for r in rows), "mentions;", once, "named once")
for r in rows[:18]:
    print(f'  {r["mentions"]}x  {r["song"]} — {r["artist"]}')
