"""Most beautiful city in the world — r/BeautifulTravelPlaces, 1wtds7h.

Counted by distinct redditor who *names* a city as beautiful, top-level or in a
reply. Same rule as museums.py: "seconding this" without a name adds nothing,
and a city named only to knock it ("Barcelona is meh", "too much graffiti in
Vienna") is not a vote. Regions, islands and landscapes that aren't a city
(Tasmania, Bali, Madeira, Mallorca, the French Riviera, County Kerry, Lake
Como, Milford Sound) are dropped — the post says "the specific city". Joke
answers (Gary, Indiana; Paris, Texas) are kept: they were said.

Data was transcribed by hand from the thread's old.reddit .json, pasted in.
"""
import json
from urllib.parse import quote

URL = "https://www.reddit.com/r/BeautifulTravelPlaces/comments/1wtds7h/which_city_do_you_think_is_the_most_beautiful_in/"

# redditor -> cities they put forward
V = {
"Intelligent_Pop1173":["Barcelona","Cape Town"],
"quemaspuess":["Prague","Sausalito","Bogotá"],
"Individual_Toe_7270":["Seville"],
"Buff1965":["Barcelona","Rio de Janeiro","Cape Town","Vancouver"],
"lthomazini":["Rio de Janeiro"],
"RyanMacCW":["Cape Town","Budapest"],
"Blackjack21x":["Kyoto"],
"JohnnyRicko":["Budapest"],
"NickiDMoe":["Edinburgh"],
"peatgirl21":["Edinburgh"],
"thehanghoul":["Edinburgh","Granada","Seattle","San Diego","Kyoto","Cape Town","Rio de Janeiro","Vancouver","Florence","Bologna","Rome"],
"ktink224":["Vancouver"],
"Sirsmokealotx":["Vancouver"],
"ToucanicEmperor":["Strasbourg","Rovinj"],
"Fanny08850":["Colmar"],
"nickfsu3":["Seville"],
"pastafariantimatter":["Seville"],
"christian4867":["Rio de Janeiro","Cape Town"],
"Dracoroth05":["Prague"],
"Choice-Passenger7470":["Prague"],
"water-sloth":["San Sebastián","Porto"],
"UniversityActual8740":["San Sebastián"],
"junkeee999":["Stockholm"],
"Content-Type-4295":["Dubrovnik"],
"Adorable-Ad-6404":["Ljubljana"],
"WardCleaver1962":["Venice"],
"OmegaKitty1":["Venice"],
"Seuss221":["Venice","Positano"],
"Haunting_Badger7752":["San Francisco"],
"JolyonWagg99":["San Francisco"],
"TheMinimumFlair":["San Francisco"],
"RainieNoNo":["San Francisco"],
"DubUpPro":["San Francisco"],
"DRR-DDD":["Lisbon"],
"BananaFern":["Bruges"],
"liveprgrmclimb":["Ghent"],
"PouletAuPoivre":["Ghent"],
"cat4897":["Vienna","Paris"],
"Altruistic_Shirt_840":["Vancouver"],
"SparrowJack1":["Florence","Vienna","Granada","Budapest","Rome","Salzburg"],
"FreshNegotiation2603":["Rome"],
"LoInfoVoter":["Paris"],
"Donkeyball_Z_":["Paris, Texas","Ludwigshafen"],
"One_Law_2443":["Paris, Illinois"],
"No-University-8391":["Paris, Kentucky"],
"bhrm":["Paris, Ontario"],
"Useful_Record1888":["Strasbourg","Avignon","Saint-Malo","La Rochelle"],
"slo-Amanda":["Edinburgh"],
"Incident-Impossible":["Rome"],
"Old_Range_4358":["Annecy","Salzburg","Lucerne"],
"Haunting-Hero1234":["Vienna"],
"D00rmat1983":["Annecy"],
"mjbonne":["Rio de Janeiro"],
"Ok-Strain6961":["Venice"],
"Internal-Stomach-999":["Budapest"],
"Suspicious_Beach_159":["Beirut"],
"Upstairs-Bath9158":["Prague","Porto"],
"enotaeywa":["Matera"],
"Music_Adventure":["Riga"],
"Simpleton565":["Matera"],
"blueroseinwinter":["Budapest"],
"petrichoroma":["Sydney"],
"nesguy1":["San Francisco","Paris","Annecy"],
"Tor-por-416":["Paris"],
"Turtle-power-21":["Paris, Texas"],
"soupsl00t":["Amsterdam"],
"SisyphusOnHoliday":["Florence","Venice"],
"aquazombb":["Cape Town"],
"bobsmith696969":["San Miguel de Allende"],
"Weird-Scheme-1649":["Venice","Rome"],
"benjithepanda":["Venice"],
"missThora":["Bergen"],
"Eddie4344":["Florence"],
"dannyghobo":["Budapest"],
"Medium_Can387":["Nassau"],
"JRR92":["Venice","Annecy"],
"coloch_w0rth9":["Sydney"],
"Longjumping-One5065":["Cuenca"],
"juniebutt":["Venice"],
"SillyProfessional527":["Kilkenny"],
"lucid_illusionz":["San Francisco","Hong Kong"],
"Left_Guess":["Hong Kong"],
"EnvironmentalDrag153":["Rome","Prague"],
"Ok_Avocado_4729":["Venice"],
"bashd12":["Queenstown"],
"Fancy_Incident_1854":["Sydney"],
"Pilatus-Porter":["Sydney"],
"Educational_Tax6114":["Rio de Janeiro"],
"GolfOk6373":["Istanbul"],
"Immediate-Count-1202":["Istanbul"],
"greyeminence2":["Siena","Paris"],
"wjbc":["Chicago"],
"NWHornedFrog":["Zürich"],
"mikeyzhong":["Porto"],
"Loki7-":["Barcelona"],
"jetpack324":["Óbidos"],
"Mission-Safe-7117":["Delft"],
"some_lazy_vibes":["Venice"],
"Own-Assistance5743":["Fukuoka"],
"ibanker92":["Kyoto"],
"UndecidedPanda11":["Venice"],
"CloudsandSunsets":["Cape Town","Rio de Janeiro","Quito","San Francisco","Udaipur","Barcelona","Edinburgh"],
"the3rdmichael":["Rio de Janeiro","Paris","Venice"],
"Difficult_Weekend_70":["Paris","Chicago","Prague","Kraków"],
"OSU_Go_Buckeyes":["Cody"],
"Severe-Town-6105":["Copenhagen","Gdańsk"],
"Royal-Entrepreneur41":["Bruges"],
"EuphoricSimple231":["Vienna"],
"MACVGNL":["Utrecht"],
"loopphoto":["Cape Town"],
"pianoplayer1014":["Vancouver"],
"evansdead":["Barcelona"],
"ChickenMan1829":["Seville"],
"AdditionalNewt2517":["Utrecht"],
"jakfor":["Sedona"],
"Happy-Constant-1627":["Saint-Julien-Molin-Molette","Saint-Just-la-Pendue","Saint-Hilaire-Cusson-la-Valmitte"],
"MyBlueBlazerBlack":["Seville"],
"eruptor_13":["Toledo"],
"F4B10_12":["Sedona"],
"Fragrant-Economist26":["Athens"],
"Consistent_Law_3857":["Copenhagen","Vienna"],
"SuddenStrength":["Red Deer"],
"grumpsticks":["San Miguel de Allende","Bruges","Paris"],
"Cocomagno":["Barcelona"],
"gooner9999999999":["Dresden"],
"Wheels322":["Prague"],
"Engg440":["Zürich","Cape Town","Seville","Vienna"],
"Raj_ryder_666":["Warsaw","Kraków"],
"Alarming_Lifeguard85":["Vancouver"],
"kugelscheisser":["Vienna"],
"Bomber402":["Los Angeles"],
"Embarrassed-Fall-487":["Positano"],
"CyclicBus471335":["Mirissa"],
"Status_Insurance7181":["Paris","Laguna Beach"],
"Purple-Cardiologist4":["Brig-Glis"],
"Soul1971":["Rome"],
"theyellowscriptures":["Rio de Janeiro"],
"Plus-Sun-2699":["New York","Chicago"],
"Impressive-Act-5637":["Milan","Paris"],
"makaveli-is-dead":["Rio de Janeiro"],
"notamovie":["Rio de Janeiro","Zürich","Stockholm"],
"UneCitoyenneDuMonde":["Paris","Istanbul"],
"pingu_nootnoot":["Split"],
"Spirited-Swim-3275":["Rio de Janeiro"],
"Legitimate-Drag4377":["Hong Kong"],
"XJ7blue":["Rome"],
"IloveIsrael-":["Sydney","Auckland"],
"Ok-Curve5569":["Stockholm","Vancouver"],
"mdc2135":["Singapore"],
"Current_Slide_6708":["Sydney"],
"SaltSpecialist6794":["Dingle"],
"Glittering_Echo_":["Kraków"],
"stevenmacarthur":["Milwaukee"],
"Dai-The-Flu-":["Montreal"],
"TheCarAudioKing":["Samarkand"],
"Longjumping_Bee366":["Victoria"],
"kaswardy":["Vienna"],
"fritzi2":["Salzburg"],
"Ok-Meaning1192":["Phaltan"],
"jrod259":["Banff"],
"Ringsareirrelevant":["Lucerne","Interlaken","St. George"],
"natiyellow":["Sydney"],
"Traditional-Sun4010":["Gary"],
"Spillsy68":["Rome","Vancouver"],
"Key_Incident_666":["Tokyo","Edinburgh"],
"Wonderful_Bowler_251":["Paris"],
"Elprocesso":["Rio de Janeiro"],
"mamielle":["Cusco"],
"Special-Loan-3920":["Vancouver"],
"FadingRockStar":["Ghent"],
"No_Turn9846":["Sydney"],
"NothingNo323":["Seville","Cartagena"],
"Acrobatic_Oven_1108":["Salzburg"],
"bigmacjr52":["Queenstown","Seattle"],
"LegitimateDelivery21":["Venice"],
"gablan1468":["Rome"],
"sanddollarsandcents":["Barcelona","Lauterbrunnen"],
"Dull_Pollution4691":["Athens"],
"dmodol":["Cape Town"],
"spicyzsurviving":["Edinburgh","Prague"],
"MirrorLegitimate9304":["Los Angeles"],
"ThrowawayYAYAY2002":["Prague"],
"NoRestaurant2326":["San Francisco"],
"Foreign-Dependent-12":["Vancouver","Kotor"],
"Boring_Pineapple_288":["Delhi"],
"oDanielLeeo":["Hong Kong"],
"Additional_Donut_701":["Istanbul"],
"Fantastic_Back3191":["Venice"],
"SpaGrapefruit":["Dubrovnik"],
"Gert123hu":["Cape Town"],
"Askargon":["Prague","Dilijan","Palermo","Tbilisi"],
"PsychologicalOil3987":["Edinburgh"],
"Sloth-turtle9814":["Venice"],
"Sidonietoth":["Vienna","Salzburg"],
"Lynch8933":["Lucerne"],
"thoth218":["New York"],
"Repulsive-Tour-7943":["Des Moines"],
"Atomsandbananas":["Amsterdam"],
"Mabsta06":["Istanbul"],
"inadarkwoodwandering":["York"],
"Tiny-Pea-2132":["Sorrento"],
"Vast-Management4887":["Fira","Copenhagen"],
"Infinite_Victory6018":["Salzburg"],
"ivemast999":["Edinburgh","Cape Town"],
"boch3n":["Florence"],
"spacewookette":["San Francisco"],
"ASOM01":["Istanbul"],
"furniguru":["Hong Kong"],
"scoop13":["Singapore"],
"OBRHakeswill":["Edinburgh"],
"Al777G":["Venice"],
"An0ma7y":["Hong Kong"],
"International_Ad694":["Ålesund"],
"Beginning_Fix2000":["Xi'an","Strasbourg","Turin"],
"SilverPiccolo1068":["Mojácar"],
"1holegrouper":["Lucerne"],
"Silent-Gear4609":["Kyoto"],
"Dumuzzid":["Prague"],
"Over_Silver3048":["Paris"],
"Muddydays":["Victoria","Vancouver"],
"tacomafresh":["Seattle","Vancouver"],
"MoreSmoovies":["Kastraki"],
"Technical_Trip4011":["Vancouver"],
"Dr_Bogosloviya":["Rome"],
"Fliederzschreibt":["Vienna"],
"braziliantapestry":["Rio de Janeiro"],
"Southern_Ad_429":["Rio de Janeiro","Edinburgh"],
"boozincruizin":["Bern"],
"dcskyline34":["Sydney"],
"curtyshoo":["Detroit"],
"Hefty_Journalist_666":["Zürich"],
"Busy_Philosopher1032":["Cape Town"],
"Such-Ad7669":["Hong Kong"],
"snowbdr440":["Rio de Janeiro","Sydney","San Francisco"],
"pufferfish_hoop":["Sheboygan"],
"hot_chili_pepper_":["Istanbul"],
"Electronic-Bag-3541":["Gary"],
"MadisonBob":["Gary"],
"pedralexpereira":["Prague"],
"eagleeye76":["Rio de Janeiro","Paris"],
"TheThirdBrainLives":["Como"],
"Alt-_-alt":["Strasbourg"],
"lupinle1":["Luton"],
"mmen1671":["Detroit"],
"WildmanDaGod":["Chicago"],
"lynxpoint":["Seville","Paris","San Francisco"],
"Flashy-Cream5400":["Edinburgh"],
"Faster_than_FTL":["Santa Barbara"],
"Remarkable_Sea9861":["Lubbock"],
"Ethanhuntknows":["Seattle"],
}

# city -> country (shown in the second column, used to scope the map search)
C = {
"Barcelona":"Spain","Cape Town":"South Africa","Prague":"Czechia","Sausalito":"USA","Bogotá":"Colombia",
"Seville":"Spain","Rio de Janeiro":"Brazil","Vancouver":"Canada","Budapest":"Hungary","Kyoto":"Japan",
"Edinburgh":"Scotland","Granada":"Spain","Seattle":"USA","San Diego":"USA","Florence":"Italy","Bologna":"Italy",
"Rome":"Italy","Strasbourg":"France","Rovinj":"Croatia","Colmar":"France","San Sebastián":"Spain","Porto":"Portugal",
"Stockholm":"Sweden","Dubrovnik":"Croatia","Ljubljana":"Slovenia","Venice":"Italy","Positano":"Italy",
"San Francisco":"USA","Lisbon":"Portugal","Bruges":"Belgium","Ghent":"Belgium","Vienna":"Austria","Paris":"France",
"Paris, Texas":"USA","Paris, Illinois":"USA","Paris, Kentucky":"USA","Paris, Ontario":"Canada","Ludwigshafen":"Germany",
"Avignon":"France","Saint-Malo":"France","La Rochelle":"France","Annecy":"France","Salzburg":"Austria","Lucerne":"Switzerland",
"Beirut":"Lebanon","Matera":"Italy","Riga":"Latvia","Sydney":"Australia","Amsterdam":"Netherlands",
"San Miguel de Allende":"Mexico","Bergen":"Norway","Nassau":"Bahamas","Cuenca":"Ecuador","Kilkenny":"Ireland",
"Hong Kong":"China","Queenstown":"New Zealand","Istanbul":"Türkiye","Siena":"Italy","Chicago":"USA","Zürich":"Switzerland",
"Óbidos":"Portugal","Delft":"Netherlands","Fukuoka":"Japan","Quito":"Ecuador","Udaipur":"India","Kraków":"Poland",
"Cody":"USA","Copenhagen":"Denmark","Gdańsk":"Poland","Utrecht":"Netherlands","Sedona":"USA",
"Saint-Julien-Molin-Molette":"France","Saint-Just-la-Pendue":"France","Saint-Hilaire-Cusson-la-Valmitte":"France",
"Toledo":"Spain","Athens":"Greece","Red Deer":"Canada","Dresden":"Germany","Warsaw":"Poland","Los Angeles":"USA",
"Mirissa":"Sri Lanka","Laguna Beach":"USA","Brig-Glis":"Switzerland","New York":"USA","Milan":"Italy","Split":"Croatia",
"Auckland":"New Zealand","Singapore":"Singapore","Dingle":"Ireland","Milwaukee":"USA","Montreal":"Canada",
"Samarkand":"Uzbekistan","Victoria":"Canada","Phaltan":"India","Banff":"Canada","Interlaken":"Switzerland",
"St. George":"USA","Gary":"USA","Tokyo":"Japan","Cusco":"Peru","Cartagena":"Colombia","Lauterbrunnen":"Switzerland",
"Kotor":"Montenegro","Delhi":"India","Dilijan":"Armenia","Palermo":"Italy","Tbilisi":"Georgia","Des Moines":"USA",
"York":"England","Sorrento":"Italy","Fira":"Greece","Ålesund":"Norway","Xi'an":"China","Turin":"Italy","Mojácar":"Spain",
"Kastraki":"Greece","Bern":"Switzerland","Detroit":"USA","Sheboygan":"USA","Como":"Italy","Luton":"England",
"Santa Barbara":"USA","Lubbock":"USA",
}

tally = {}
for who, cities in V.items():
    for c in set(cities):
        tally.setdefault(c, set()).add(who)
out = sorted(((c, len(w)) for c, w in tally.items()), key=lambda r: (-r[1], r[0].lower()))
missing = [c for c, _ in out if c not in C]
assert not missing, missing

rows = []
for city, n in out:
    country = C[city]
    q = city if "," in city else f"{city} {country}"
    rows.append({
        "key": f"city|{city}",
        "lead": f"{n}×",
        "sec": country,
        "pri": city,
        "links": [{"url": "https://www.google.com/maps/search/?api=1&query=" + quote(q), "label": "Map ↗"}],
        "src": {"label": "r/BeautifulTravelPlaces", "url": URL},
    })

if __name__ == "__main__":
    for c, n in out[:25]:
        print(n, c)
    print("CITIES", len(out), "REDDITORS", len(V), "VOTES", sum(n for _, n in out))
    json.dump(rows, open("/tmp/cities.json", "w"), ensure_ascii=False)
