"""r/movies — "What are your Top 10 movies of the 2000's? (2000-2009)"

Same shape as the 2010s tally: ranked or unranked tens, counted by distinct
redditor. Three rules that matter here, all recorded in the list's note:

  * Honourable mentions are not counted. Several people posted a ten and then
    a second pile of "HM" titles; counting those would give a long list an
    unearned advantage over someone who obeyed the rules.
  * People who posted a film-per-year for the whole decade are counted, since
    that is still ten-ish picks. But e8odie posted a top ten for *every* year
    — 110 films — and then their own twelve for the decade; only the twelve
    are counted, or one person would outvote everyone else.
  * Titles outside 2000–2009 are dropped (Inception, The Grand Budapest Hotel,
    The Shape of Water, and a whole parallel 90s list), because the question
    asked for a decade.

The asker posted no list of their own, so nothing needs excluding there.
"""
import json
from collections import defaultdict

THREAD = {
 "q": "What are your Top 10 movies of the 2000's? (2000-2009)",
 "site": "Reddit · r/movies", "year": 2018,
 "meta": "top-ten lists",
 "url": "https://www.reddit.com/r/movies/comments/a0w5ch/what_are_your_top_10_movies_of_the_2000s_20002009/",
}

LOTR = "The Lord of the Rings trilogy"

BALLOTS = {
"spencerlevey": ["Mamma Mia!","Enchanted","Cars","Little Miss Sunshine","The Devil Wears Prada",
  "Mean Girls","Elf","Bruce Almighty","The Hills Have Eyes","The Texas Chainsaw Massacre"],
"MajesticMongoose": [LOTR,"Monsters, Inc.","Inglourious Basterds","Ratatouille","The Dark Knight",
  "The Prestige","Children of Men","Finding Nemo","Hot Fuzz","The Mist"],
"eallalrr": ["Caché","The Piano Teacher","There Will Be Blood","Eternal Sunshine of the Spotless Mind",
  "Let the Right One In","Punch-Drunk Love","The White Ribbon","Oldboy","Hero",
  "No Country for Old Men"],
"ealokvy": ["Before Sunset","Harry Potter and the Prisoner of Azkaban","Hot Rod",
  "In the Mood for Love","Lost in Translation","Master and Commander: The Far Side of the World",
  "Punch-Drunk Love","Requiem for a Dream","The Descent","The Diving Bell and the Butterfly"],
"Sparkski": ["The Assassination of Jesse James by the Coward Robert Ford",
  "Eternal Sunshine of the Spotless Mind","No Country for Old Men","Watchmen","The Dark Knight",
  "The Departed","Gladiator","Zodiac","Sunshine","Collateral"],
"SkyDogsGhost": ["No Country for Old Men","There Will Be Blood","Before the Devil Knows You're Dead",
  "In Bruges","Mulholland Drive","The Pianist",
  "The Assassination of Jesse James by the Coward Robert Ford","City of God",LOTR,"Children of Men"],
# Posted a top ten for every single year, then their own twelve for the decade.
# Only the twelve count — otherwise one commenter carries 110 votes.
"e8odie": ["Memento","Almost Famous","Big Fish","Atonement","Training Day",
  "O Brother, Where Art Thou?","City of God","Across the Universe","Pan's Labyrinth",
  "Catch Me If You Can","Eternal Sunshine of the Spotless Mind","Hard Candy"],
"yung-rude": ["American Psycho","The Royal Tenenbaums","Punch-Drunk Love","Kill Bill: Vol. 1",
  "Before Sunset","Collateral","Sin City","Children of Men","Superbad","Synecdoche, New York",
  "Enter the Void"],
"pineapplebender": ["Requiem for a Dream",LOTR,"Gladiator","Finding Nemo","Tropic Thunder",
  "Black Dynamite","Inland Empire","Mulholland Drive","Pitch Black","No Country for Old Men"],
"gibsonlespaul": ["American Psycho","Requiem for a Dream","Remember the Titans","Memento",
  "O Brother, Where Art Thou?","Gangs of New York","Kill Bill: Vol. 1","Bruce Almighty","Big Fish",
  "Pirates of the Caribbean: Dead Man's Chest","Pan's Labyrinth","There Will Be Blood",
  "The Dark Knight","Inglourious Basterds","Coraline"],
"ClownUnderYourBed": ["The Dark Knight","Donnie Darko","American Psycho","Ratatouille",
  "Kiss Kiss Bang Bang","Pan's Labyrinth","28 Days Later","District 9","A.I. Artificial Intelligence",
  "Shaun of the Dead","Slumdog Millionaire"],
"eal9kg2": ["Lost in Translation","Adventureland","Eternal Sunshine of the Spotless Mind",
  "Moulin Rouge!","The 40-Year-Old Virgin","Zombieland","The Notebook",
  "Harold & Kumar Go to White Castle","Wedding Crashers","Far from Heaven"],
"IsaoEB": ["Moon","The Departed","Casino Royale","No Country for Old Men","Treasure Planet",
  "The Prestige","A Scanner Darkly","District 9","Eternal Sunshine of the Spotless Mind","Sin City"],
"eakuzmv": ["Requiem for a Dream","4 Months, 3 Weeks and 2 Days","American Psycho","Antichrist",
  "Lilya 4-ever","Elephant","Memento","Sideways","Death Proof","You Can Count on Me"],
"eal008e": ["There Will Be Blood","Morvern Callar","Crouching Tiger, Hidden Dragon","Spirited Away",
  "Ratatouille","Birth","Step Brothers","Ghost World","Pan's Labyrinth","25th Hour"],
"Darko33": ["In the Bedroom","Eternal Sunshine of the Spotless Mind","Brokeback Mountain",
  "There Will Be Blood","Pan's Labyrinth","Michael Clayton","The Visitor","Memento",
  "Lost in Translation","The Departed"],
"Tarantiyes": ["Hot Fuzz","The Prestige","Monsters, Inc.","A Beautiful Mind",
  "Pirates of the Caribbean: The Curse of the Black Pearl","The Departed","Oldboy","Up",
  "Inglourious Basterds","Moon"],
"eal8a8r": ["There Will Be Blood","Zodiac","No Country for Old Men","Watchmen",LOTR,
  "Pan's Labyrinth","The Prestige","Inglourious Basterds","Mulholland Drive","Unbreakable"],
"mjhtemp": ["Requiem for a Dream","Eternal Sunshine of the Spotless Mind","Waking Life",
  "Spring, Summer, Fall, Winter… and Spring","Shaun of the Dead","Kill Bill: Vol. 1",
  "The Lives of Others","Dancer in the Dark","Pan's Labyrinth","The Gleaners and I"],
"ealbj8l": ["Eternal Sunshine of the Spotless Mind","Lost in Translation","Punch-Drunk Love",
  "Before Sunset","No Country for Old Men","Mulholland Drive","There Will Be Blood",
  "The Dark Knight","WALL·E","Inglourious Basterds"],
"trollcitybandit": [LOTR,"Vanilla Sky","The Departed","Catch Me If You Can","Mulholland Drive",
  "The Dark Knight","Pan's Labyrinth","Tropic Thunder","Gladiator","Superbad"],
"eam3opd": ["Gladiator","The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers","The Lord of the Rings: The Return of the King","Closer",
  "Sin City","Casino Royale","Sunshine","Gran Torino","Watchmen"],
"ArmsofSleep": ["Syndromes and a Century","Ratatouille","Yi Yi","You, the Living",
  "As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty","Spirited Away","Inside Man",
  "Still Walking","A Serious Man","Pineapple Express"],
"eakx7va": ["Speed Racer","Inglourious Basterds","Eternal Sunshine of the Spotless Mind","Memento",
  "Pan's Labyrinth","The Dark Knight","Spider-Man 2","Harry Potter and the Prisoner of Azkaban",
  "The Spiderwick Chronicles","Casino Royale"],
"Paralyzingneedle": ["Eternal Sunshine of the Spotless Mind","The Pianist","The Hours",
  "Hotel Rwanda","Doubt","Transamerica","Notes on a Scandal","Babel","The Aviator","Vera Drake"],
"jkliner": ["Brick","Eternal Sunshine of the Spotless Mind","The Royal Tenenbaums",
  "Fantastic Mr. Fox","The Incredibles",LOTR,"Lost in Translation","Children of Men",
  "Crouching Tiger, Hidden Dragon","Ocean's Eleven"],
"hombregato": ["Kill Bill: Vol. 1","Requiem for a Dream","Amélie","Lost in Translation",
  "Crouching Tiger, Hidden Dragon","Bowling for Columbine","Memento","Mulholland Drive",
  "The Last Samurai","Oldboy","The Pianist"],
"Wolver8ne": ["The Dark Knight","Lost in Translation","Into the Wild","Good Bye, Lenin!",
  "Treasure Planet","The New World","Cast Away","Mr. Nobody","Howl's Moving Castle",
  "The Last Samurai"],
"Bcreeves89": ["Batman Begins","The Dark Knight",LOTR,"The Departed","Wedding Crashers","Iron Man",
  "Green Street Hooligans","How the Grinch Stole Christmas","Inglourious Basterds",
  "Kill Bill: Vol. 1","Old School"],
"SeidoHunter": ["Inglourious Basterds","American Psycho","Catch Me If You Can",
  "No Country for Old Men","The Incredibles","A Beautiful Mind","The Departed","Ocean's Eleven",
  "Zodiac","Treasure Planet"],
"B-Abbas-B": ["Children of Men","The Dark Knight","Gladiator",LOTR,"Inglourious Basterds",
  "District 9","The Prestige","Spirited Away","The Incredibles","Up"],
"Delta_Assault": ["The Dark Knight","Zodiac","Black Hawk Down","WALL·E","The Bourne Ultimatum",
  "(500) Days of Summer","Letters from Iwo Jima","District 9","Spider-Man 2",
  "Harold & Kumar Go to White Castle"],
"hy2wrg4": ["The Dark Knight","I Am Legend","Transformers",LOTR,
  "Star Wars: Episode III – Revenge of the Sith","Freddy vs. Jason",
  "The Texas Chainsaw Massacre: The Beginning","Bad Boys II","Inglourious Basterds","Ice Age"],
"eakv9sz": ["Tie Xi Qu: West of the Tracks","Werckmeister Harmonies","In the Mood for Love",
  "A Place in the World","Evolution of a Filipino Family","Shara","Millennium Mambo",
  "The Limits of Control","Our Daily Bread","Eureka"],
"Sushibowl123": ["No Country for Old Men","There Will Be Blood","Synecdoche, New York","Oldboy",
  "In the Mood for Love","The White Ribbon","Caché","A Serious Man","Mulholland Drive",
  "Spirited Away"],
"Soliantu": ["Unbreakable","Before Sunset","Inglourious Basterds","The Wrestler","Superbad",
  "Almost Famous","The Incredibles","Big Fish","Donnie Darko","Fantastic Mr. Fox"],
"ItsAMeEric": ["Blow","Gladiator","Blood Diamond","Snatch","Memento","V for Vendetta",
  "A Beautiful Mind","Children of Men","Gran Torino","Gone Baby Gone"],
"rytis": ["Moulin Rouge!","The Lord of the Rings: The Two Towers","Avatar","Kill Bill: Vol. 1",
  "The Dark Knight","Up","300"],
"Dlimes": ["The Departed","The Hurt Locker","Insomnia","Donnie Darko","No Country for Old Men",
  "Pan's Labyrinth","The Dark Knight","Superbad","There Will Be Blood","Inglourious Basterds"],
"spencerlovesyou": ["Synecdoche, New York","A Single Man","The Lord of the Rings: The Fellowship of the Ring",
  "Ratatouille","Bronson","Hot Fuzz","Speed Racer","Oldboy","Inglourious Basterds",
  "Y Tu Mamá También"],
"eal5lmn": [LOTR,"The Dark Knight","Slumdog Millionaire","The Departed","Spirited Away",
  "Finding Nemo","Eternal Sunshine of the Spotless Mind","Oldboy","Rush Hour 2","District 9"],
"what_if_Im_dinosaur": ["Eternal Sunshine of the Spotless Mind","Waltz with Bashir",
  "Pan's Labyrinth","Shaun of the Dead","Y Tu Mamá También","The Royal Tenenbaums","City of God",
  "Suzhou River","Battle Royale","Kill Bill: Vol. 1"],
"USCplaya": ["Inglourious Basterds","The Departed","Children of Men","Catch Me If You Can","Borat",
  "Gladiator","Zombieland","Cast Away","Up in the Air","Iron Man"],
"Fearzane": ["V for Vendetta","Donnie Darko","Bang Bang You're Dead","Billy Elliot",
  "The History Boys","Crash","The Departed","The Dark Knight","Millions","Transamerica"],
"ealaabg": ["The Prestige","The Departed","Inglourious Basterds","Batman Begins",
  "Gangs of New York","The Dark Knight","Blow","Master and Commander: The Far Side of the World",
  "No Country for Old Men","Pirates of the Caribbean: The Curse of the Black Pearl"],
"ealamtr": ["The Lord of the Rings: The Return of the King","The Dark Knight","Watchmen",
  "Spider-Man 2","Star Wars: Episode III – Revenge of the Sith","Star Trek","Iron Man",
  "Casino Royale","Pirates of the Caribbean: The Curse of the Black Pearl","Tropic Thunder"],
"GuamPolice": ["Snatch","Gladiator","City of God","Spirited Away","The Departed","Moulin Rouge!",
  "Gangs of New York","No Country for Old Men","Friday Night Lights","Superbad"],
"ihaveblink": ["Children of Men","Ghost World","Eternal Sunshine of the Spotless Mind",
  "Mulholland Drive","Superbad","The Assassination of Jesse James by the Coward Robert Ford",
  "Scott Pilgrim vs. the World","The Squid and the Whale","The Wrestler","Punch-Drunk Love"],
"tnkr28": ["No Country for Old Men","American Splendor","Pan's Labyrinth","High Fidelity",
  "City of God","Zodiac","Children of Men","Waltz with Bashir","There Will Be Blood",
  "O Brother, Where Art Thou?"],
"Benreineck123": ["Inglourious Basterds","Batman Begins","Iron Man","Pineapple Express",
  "Star Wars: Episode III – Revenge of the Sith"],
"Spideyboss": ["Children of Men","There Will Be Blood","Memento","No Country for Old Men",
  "Inglourious Basterds","The Departed","The Wrestler","Hot Fuzz","Zodiac","In Bruges"],
"MadEgg531": ["Burn After Reading","Inglourious Basterds","The Dark Knight",LOTR,
  "There Will Be Blood","Adaptation.","The Other Guys","Gangs of New York",
  "Eternal Sunshine of the Spotless Mind"],
"deadandmessedup": ["Unbreakable","Pulse","Spirited Away","Memories of Murder","Primer",
  "The Descent","Apocalypto","No Country for Old Men","The Fall","A Serious Man"],
"cp5184": ["In Bruges","Almost Famous","Gladiator","The Dish",LOTR,"Ocean's Eleven","Snatch",
  "Spirited Away","Big Trouble","Batman Begins","Layer Cake","V for Vendetta","Watchmen","Hot Fuzz",
  "Michael Clayton","WALL·E","High Fidelity"],
"ealltrv": ["Eternal Sunshine of the Spotless Mind","28 Days Later","Up","Finding Neverland",
  "Breakfast on Pluto","Disco Pigs","The Hole","WALL·E","The Dark Knight","Big Fish"],
"FloatingB": ["Crouching Tiger, Hidden Dragon","No Country for Old Men","Memories of Murder",
  "Kill Bill: Vol. 1","Zodiac","Oldboy","Shaun of the Dead","In the Mood for Love","Apocalypto",
  "Dogtooth"],
"p__d4wg": ["There Will Be Blood","Mulholland Drive","In the Mood for Love","Zodiac",
  "The Assassination of Jesse James by the Coward Robert Ford","The Dark Knight",
  "Crouching Tiger, Hidden Dragon","The Lord of the Rings: The Fellowship of the Ring",
  "Spirited Away","Elephant"],
"lawschoolredux": ["Mulholland Drive","Munich","Collateral","The Dark Knight",
  "No Country for Old Men","The Bourne Ultimatum","Mystic River","Spartan","Zodiac",
  "Kill Bill: Vol. 2"],
"eam39ht": ["The Departed","Ocean's Eleven","Catch Me If You Can","The Fast and the Furious",
  "The Dark Knight","Pirates of the Caribbean: The Curse of the Black Pearl",
  "Harry Potter and the Goblet of Fire","Remember the Titans","The Hangover","Cars"],
"Jason4hees": ["The Assassination of Jesse James by the Coward Robert Ford","The Prestige",
  "No Country for Old Men","American Psycho","The Departed","Batman Begins","Walk Hard: The Dewey Cox Story",
  "Public Enemies","Eternal Sunshine of the Spotless Mind","Zodiac"],
"trimonkeys": ["The Dark Knight","Casino Royale","The Lord of the Rings: The Return of the King",
  "Eternal Sunshine of the Spotless Mind","The Departed","The Prestige","Children of Men",
  "Shaun of the Dead","Inglourious Basterds","Collateral"],
"yodadamanadamwan": ["The Dark Knight","Gladiator","The Departed","Kiss Kiss Bang Bang",
  "The Prestige","Ocean's Eleven","Hot Fuzz","Spirited Away","Iron Man","Big Fish"],
}

YEARS = {
"(500) Days of Summer":2009,"25th Hour":2002,"28 Days Later":2002,"300":2006,
"4 Months, 3 Weeks and 2 Days":2007,"A Beautiful Mind":2001,"A Place in the World":2001,
"A Scanner Darkly":2006,"A Serious Man":2009,"A Single Man":2009,"A.I. Artificial Intelligence":2001,
"Across the Universe":2007,"Adaptation.":2002,"Adventureland":2009,"Almost Famous":2000,
"Amélie":2001,"American Psycho":2000,"American Splendor":2003,"Antichrist":2009,"Apocalypto":2006,
"As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty":2000,"Atonement":2007,
"Avatar":2009,"Babel":2006,"Bad Boys II":2003,"Bang Bang You're Dead":2002,"Batman Begins":2005,
"Battle Royale":2000,"Before Sunset":2004,"Before the Devil Knows You're Dead":2007,
"Big Fish":2003,"Big Trouble":2002,"Billy Elliot":2000,"Birth":2004,"Black Dynamite":2009,
"Black Hawk Down":2001,"Blood Diamond":2006,"Blow":2001,"Borat":2006,"Bowling for Columbine":2002,
"Breakfast on Pluto":2005,"Brick":2005,"Brokeback Mountain":2005,"Bronson":2008,
"Bruce Almighty":2003,"Burn After Reading":2008,"Caché":2005,"Cars":2006,"Casino Royale":2006,
"Cast Away":2000,"Catch Me If You Can":2002,"Children of Men":2006,"City of God":2002,
"Closer":2004,"Collateral":2004,"Coraline":2009,"Crash":2004,"Crouching Tiger, Hidden Dragon":2000,
"Dancer in the Dark":2000,"Death Proof":2007,"Disco Pigs":2001,"District 9":2009,"Dogtooth":2009,
"Donnie Darko":2001,"Doubt":2008,"Elephant":2003,"Elf":2003,"Enchanted":2007,"Enter the Void":2009,
"Eternal Sunshine of the Spotless Mind":2004,"Eureka":2000,"Evolution of a Filipino Family":2004,
"Fantastic Mr. Fox":2009,"Far from Heaven":2002,"Finding Nemo":2003,"Finding Neverland":2004,
"Freddy vs. Jason":2003,"Friday Night Lights":2004,"Gangs of New York":2002,"Ghost World":2001,
"Gladiator":2000,"Gone Baby Gone":2007,"Good Bye, Lenin!":2003,"Gran Torino":2008,
"Green Street Hooligans":2005,"Hard Candy":2005,"Harold & Kumar Go to White Castle":2004,
"Harry Potter and the Goblet of Fire":2005,"Harry Potter and the Prisoner of Azkaban":2004,
"Hero":2002,"High Fidelity":2000,"Hotel Rwanda":2004,"Hot Fuzz":2007,"Hot Rod":2007,
"How the Grinch Stole Christmas":2000,"Howl's Moving Castle":2004,"I Am Legend":2007,
"Ice Age":2002,"In Bruges":2008,"In the Bedroom":2001,"In the Mood for Love":2000,
"Inglourious Basterds":2009,"Inland Empire":2006,"Inside Man":2006,"Insomnia":2002,
"Into the Wild":2007,"Iron Man":2008,"Kill Bill: Vol. 1":2003,"Kill Bill: Vol. 2":2004,
"Kiss Kiss Bang Bang":2005,"Layer Cake":2004,"Let the Right One In":2008,
"Letters from Iwo Jima":2006,"Lilya 4-ever":2002,"Little Miss Sunshine":2006,
"Lost in Translation":2003,"Mamma Mia!":2008,
"Master and Commander: The Far Side of the World":2003,"Mean Girls":2004,"Memento":2000,
"Memories of Murder":2003,"Michael Clayton":2007,"Millennium Mambo":2001,"Millions":2004,
"Monsters, Inc.":2001,"Moon":2009,"Morvern Callar":2002,"Moulin Rouge!":2001,"Mr. Nobody":2009,
"Mulholland Drive":2001,"Munich":2005,"Mystic River":2003,"No Country for Old Men":2007,
"Notes on a Scandal":2006,"O Brother, Where Art Thou?":2000,"Ocean's Eleven":2001,
"Old School":2003,"Oldboy":2003,"Our Daily Bread":2005,"Pan's Labyrinth":2006,
"Pineapple Express":2008,"Pirates of the Caribbean: Dead Man's Chest":2006,
"Pirates of the Caribbean: The Curse of the Black Pearl":2003,"Pitch Black":2000,"Primer":2004,
"Public Enemies":2009,"Pulse":2001,"Punch-Drunk Love":2002,"Ratatouille":2007,
"Remember the Titans":2000,"Requiem for a Dream":2000,"Rush Hour 2":2001,
"Scott Pilgrim vs. the World":2010,"Shara":2003,"Shaun of the Dead":2004,"Sideways":2004,
"Sin City":2005,"Slumdog Millionaire":2008,"Snatch":2000,"Spartan":2004,"Speed Racer":2008,
"Spider-Man 2":2004,"Spirited Away":2001,"Spring, Summer, Fall, Winter… and Spring":2003,
"Star Trek":2009,"Star Wars: Episode III – Revenge of the Sith":2005,"Step Brothers":2008,
"Still Walking":2008,"Sunshine":2007,"Superbad":2007,"Suzhou River":2000,
"Synecdoche, New York":2008,"Syndromes and a Century":2006,"The 40-Year-Old Virgin":2005,
"The Assassination of Jesse James by the Coward Robert Ford":2007,"The Aviator":2004,
"The Bourne Ultimatum":2007,"The Dark Knight":2008,"The Departed":2006,"The Descent":2005,
"The Devil Wears Prada":2006,"The Dish":2000,"The Diving Bell and the Butterfly":2007,
"The Fall":2006,"The Fast and the Furious":2001,"The Gleaners and I":2000,"The Hangover":2009,
"The Hills Have Eyes":2006,"The History Boys":2006,"The Hole":2001,"The Hours":2002,
"The Hurt Locker":2008,"The Incredibles":2004,"The Last Samurai":2003,
"The Limits of Control":2009,"The Lives of Others":2006,
"The Lord of the Rings: The Fellowship of the Ring":2001,
"The Lord of the Rings: The Return of the King":2003,
"The Lord of the Rings: The Two Towers":2002,LOTR:"2001–03","The Mist":2007,
"The New World":2005,"The Notebook":2004,"The Other Guys":2010,"The Pianist":2002,
"The Piano Teacher":2001,"The Prestige":2006,"The Royal Tenenbaums":2001,
"The Spiderwick Chronicles":2008,"The Squid and the Whale":2005,
"The Texas Chainsaw Massacre":2003,"The Texas Chainsaw Massacre: The Beginning":2006,
"The Visitor":2007,"The White Ribbon":2009,"The Wrestler":2008,"There Will Be Blood":2007,
"Tie Xi Qu: West of the Tracks":2002,"Training Day":2001,"Transamerica":2005,"Transformers":2007,
"Treasure Planet":2002,"Tropic Thunder":2008,"Unbreakable":2000,"Up":2009,"Up in the Air":2009,
"V for Vendetta":2005,"Vanilla Sky":2001,"Vera Drake":2004,"WALL·E":2008,"Waking Life":2001,
"Walk Hard: The Dewey Cox Story":2007,"Waltz with Bashir":2008,"Watchmen":2009,
"Wedding Crashers":2005,"Werckmeister Harmonies":2000,"Y Tu Mamá También":2001,"Yi Yi":2000,
"You Can Count on Me":2000,"You, the Living":2007,"Zodiac":2007,"Zombieland":2009,
}

# The question asked for 2000–2009. A few people drifted.
OUT_OF_DECADE = {t for t, y in YEARS.items() if isinstance(y, int) and not 2000 <= y <= 2009}

counts = defaultdict(set)
dropped = defaultdict(int)
for user, films in BALLOTS.items():
    for f in films:
        if f in OUT_OF_DECADE:
            dropped[f] += 1
            continue
        counts[f].add(user)

rows = sorted(
    ({"title": f, "year": YEARS.get(f, ""), "mentions": len(u)} for f, u in counts.items()),
    key=lambda r: (-r["mentions"], r["title"].lower()))

json.dump({"thread": THREAD, "rows": rows}, open("films2000s.json", "w"),
          ensure_ascii=False, separators=(",", ":"))
missing = [r["title"] for r in rows if r["year"] == ""]
print(len(rows), "films from", len(BALLOTS), "ballots;",
      sum(r["mentions"] for r in rows), "placements")
print("missing years:", missing or "none")
print("dropped (outside 2000-09):", dict(dropped))
for r in rows[:16]:
    print(f'  {r["mentions"]}x  {r["title"]} ({r["year"]})')
