#!/usr/bin/env python3
"""r/AskReddit — "What books are truly masterpieces?"

One capture of the thread, sorted by top, at ?depth=1 — which strips replies and
leaves one clean top-level answer per comment. 407 comments in the thread; the
capture held 224 top-level answers.

Ranked by DISTINCT REDDITORS naming the book. Where a comment lists several
books, each one counts. Upvotes on the naming comments are the tie-break.

What's left out, and it is all of it written down here:
  - the asker's own list (as on every other book tally);
  - answers that name only an author or a body of work ("All Charles Dickens",
    "the works of Kafka, Poe, Lovecraft") — there's no row to put them in;
  - books mentioned without being called a masterpiece: one "heard it was
    amazing but haven't read it", one "just picked it up", one companion-read
    suggestion, one "a masterpiece of pretension";
  - joke answers: a picture-book run (The Very Hungry Caterpillar, If You Give
    a Mouse a Cookie, Dog Man, Superfudge), a Windows 95 manual, the Bluebook,
    and the rest of AskReddit's usual furniture.
Series are kept as one row when named as a series (Aubrey–Maturin, The Book of
the New Sun, The Wheel of Time), because that's how they were answered.

Run from the repo root:  python3 tools/masterpieces.py && python3 tools/agreed.py
"""

import json, collections

PATH = "content/shelves.json"
SLUG = "truly-masterpieces"
URL = "https://www.reddit.com/r/AskReddit/comments/1wokqpm/what_books_are_truly_masterpieces/"

AUTHORS = {
    "Lonesome Dove": "Larry McMurtry",
    "1984": "George Orwell",
    "The Count of Monte Cristo": "Alexandre Dumas",
    "Endurance": "Alfred Lansing",
    "The Grapes of Wrath": "John Steinbeck",
    "Frankenstein": "Mary Shelley",
    "Dracula": "Bram Stoker",
    "The Haunting of Hill House": "Shirley Jackson",
    "One Hundred Years of Solitude": "Gabriel García Márquez",
    "A Farewell to Arms": "Ernest Hemingway",
    "East of Eden": "John Steinbeck",
    "A Gentleman in Moscow": "Amor Towles",
    "Lolita": "Vladimir Nabokov",
    "Dandelion Wine": "Ray Bradbury",
    "Anna Karenina": "Leo Tolstoy",
    "11/22/63": "Stephen King",
    "Brave New World": "Aldous Huxley",
    "Rubbernecker": "Belinda Bauer",
    "Ubik": "Philip K. Dick",
    "Solaris": "Stanisław Lem",
    "Fahrenheit 451": "Ray Bradbury",
    "Piranesi": "Susanna Clarke",
    "Blood Meridian": "Cormac McCarthy",
    "The Old Man and the Sea": "Ernest Hemingway",
    "The Picture of Dorian Gray": "Oscar Wilde",
    "Watership Down": "Richard Adams",
    "Moby-Dick": "Herman Melville",
    "For Whom the Bell Tolls": "Ernest Hemingway",
    "Stoner": "John Williams",
    "Hard Rain Falling": "Don Carpenter",
    "To Kill a Mockingbird": "Harper Lee",
    "Siddhartha": "Hermann Hesse",
    "Catch-22": "Joseph Heller",
    "Dune": "Frank Herbert",
    "The Lord of the Rings": "J. R. R. Tolkien",
    "The Great Gatsby": "F. Scott Fitzgerald",
    "The Catcher in the Rye": "J. D. Salinger",
    "The Bell Jar": "Sylvia Plath",
    "Crime and Punishment": "Fyodor Dostoevsky",
    "Pride and Prejudice": "Jane Austen",
    "Ulysses": "James Joyce",
    "Don Quixote": "Miguel de Cervantes",
    "The Hobbit": "J. R. R. Tolkien",
    "The Silmarillion": "J. R. R. Tolkien",
    "Perfume": "Patrick Süskind",
    "Suttree": "Cormac McCarthy",
    "The English Patient": "Michael Ondaatje",
    "A Pale View of Hills": "Kazuo Ishiguro",
    "The Remains of the Day": "Kazuo Ishiguro",
    "The Aubrey–Maturin series": "Patrick O'Brian",
    "The Dark Is Rising sequence": "Susan Cooper",
    "The Round House": "Louise Erdrich",
    "The Plague of Doves": "Louise Erdrich",
    "The Narrow Road to the Deep North": "Richard Flanagan",
    "Accordion Crimes": "Annie Proulx",
    "Les Misérables": "Victor Hugo",
    "The Overstory": "Richard Powers",
    "Spring Moon": "Bette Bao Lord",
    "Infinite Jest": "David Foster Wallace",
    "Slaughterhouse-Five": "Kurt Vonnegut",
    "Jane Eyre": "Charlotte Brontë",
    "Gravity's Rainbow": "Thomas Pynchon",
    "Star Maker": "Olaf Stapledon",
    "House of Leaves": "Mark Z. Danielewski",
    "If on a Winter's Night a Traveler": "Italo Calvino",
    "The Hitchhiker's Guide to the Galaxy": "Douglas Adams",
    "The Phantom Tollbooth": "Norton Juster",
    "One Day in the Life of Ivan Denisovich": "Aleksandr Solzhenitsyn",
    "Eugene Onegin": "Alexander Pushkin",
    "The Song of Achilles": "Madeline Miller",
    "Matterhorn": "Karl Marlantes",
    "The Good Soldier Švejk": "Jaroslav Hašek",
    "The Fortunes of Wangrin": "Amadou Hampâté Bâ",
    "The Tale of Genji": "Murasaki Shikibu",
    "You Can't Win": "Jack Black",
    "The Master and Margarita": "Mikhail Bulgakov",
    "2666": "Roberto Bolaño",
    "All About Love": "bell hooks",
    "The Secret History": "Donna Tartt",
    "The Little Friend": "Donna Tartt",
    "The Goldfinch": "Donna Tartt",
    "Heart of Darkness": "Joseph Conrad",
    "The Rise and Fall of the Third Reich": "William L. Shirer",
    "The Forgotten Soldier": "Guy Sajer",
    "Gödel, Escher, Bach": "Douglas Hofstadter",
    "The Book of the New Sun": "Gene Wolfe",
    "The Handmaid's Tale": "Margaret Atwood",
    "Pachinko": "Min Jin Lee",
    "The Divine Comedy": "Dante Alighieri",
    "The Sword of Kaigen": "M. L. Wang",
    "Brideshead Revisited": "Evelyn Waugh",
    "Bleak House": "Charles Dickens",
    "The Great War for Civilisation": "Robert Fisk",
    "American Tabloid": "James Ellroy",
    "Under the Volcano": "Malcolm Lowry",
    "War and Peace": "Leo Tolstoy",
    "The Mars Trilogy": "Kim Stanley Robinson",
    "The Sea and Summer": "George Turner",
    "Mirror Dance": "Lois McMaster Bujold",
    "A Portrait of the Artist as a Young Man": "James Joyce",
    "Cannery Row": "John Steinbeck",
    "Henderson the Rain King": "Saul Bellow",
    "A Confederacy of Dunces": "John Kennedy Toole",
    "Demian": "Hermann Hesse",
    "Annihilation": "Jeff VanderMeer",
    "Beloved": "Toni Morrison",
    "Contact": "Carl Sagan",
    "Adventures of Huckleberry Finn": "Mark Twain",
    "The Hunger Games": "Suzanne Collins",
    "Titus Groan": "Mervyn Peake",
    "The Wall": "Marlen Haushofer",
    "Hyperion": "Dan Simmons",
    "A Voyage to Arcturus": "David Lindsay",
    "Narcissus and Goldmund": "Hermann Hesse",
    "Jitterbug Perfume": "Tom Robbins",
    "Sister Carrie": "Theodore Dreiser",
    "The Thirty Years War": "C. V. Wedgwood",
    "The Autumn of the Middle Ages": "Johan Huizinga",
    "The Desert of Souls": "Howard Andrew Jones",
    "The Call of the Wild": "Jack London",
    "Anathem": "Neal Stephenson",
    "Animal Farm": "George Orwell",
    "The Shining": "Stephen King",
    "Underworld": "Don DeLillo",
    "Man's Search for Meaning": "Viktor Frankl",
    "The Stranger": "Albert Camus",
    "John Dies at the End": "David Wong",
    "The Mahabharata": "Vyasa",
    "Shōgun": "James Clavell",
    "A Storm of Swords": "George R. R. Martin",
    "The Girl with the Dragon Tattoo": "Stieg Larsson",
    "The Wheel of Time": "Robert Jordan",
    "I Keep My Exoskeletons to Myself": "Marisa Crane",
    "The Bible": "Various",
    "The Heroes": "Joe Abercrombie",
    "Trust": "Hernan Diaz",
    "The Dresden Files": "Jim Butcher",
    "Circe": "Madeline Miller",
    "Dungeon Crawler Carl": "Matt Dinniman",
    "Gang Leader for a Day": "Sudhir Venkatesh",
    "Good Morning, Monster": "Catherine Gildiner",
    "Rebecca": "Daphne du Maurier",
    "The Way of Kings": "Brandon Sanderson",
    "Randamoozham": "M. T. Vasudevan Nair",
    "The Brothers Karamazov": "Fyodor Dostoevsky",
    "Pedro Páramo": "Juan Rulfo",
    "Gormenghast": "Mervyn Peake",
    "The Pillars of the Earth": "Ken Follett",
    "Magician": "Raymond E. Feist",
    "The Curious Incident of the Dog in the Night-Time": "Mark Haddon",
    "Fight Club": "Chuck Palahniuk",
    "Cujo": "Stephen King",
    "The Jungle Book": "Rudyard Kipling",
    "The Maltese Falcon": "Dashiell Hammett",
    "The War of the Worlds": "H. G. Wells",
    "Angela's Ashes": "Frank McCourt",
    "Dead Souls": "Nikolai Gogol",
    "The Chronicles of Barsetshire": "Anthony Trollope",
    "Roadside Picnic": "Arkady & Boris Strugatsky",
    "The Fall": "Albert Camus",
    "The Metamorphosis": "Franz Kafka",
    "Mason & Dixon": "Thomas Pynchon",
    "Buddenbrooks": "Thomas Mann",
    "The Magic Mountain": "Thomas Mann",
    "The Adventures of Augie March": "Saul Bellow",
    "Labyrinths": "Jorge Luis Borges",
    "Europe Central": "William T. Vollmann",
    "The Bloody Chamber": "Angela Carter",
    "Ice": "Anna Kavan",
    "The Sailor Who Fell from Grace with the Sea": "Yukio Mishima",
    "The Overcoat": "Nikolai Gogol",
    "It": "Stephen King",
    "Invicto": "Marcos Vázquez",
    "King Rat": "James Clavell",
    "Jonathan Livingston Seagull": "Richard Bach",
    "The Book Thief": "Markus Zusak",
    "Zen and the Art of Motorcycle Maintenance": "Robert M. Pirsig",
    "The Things They Carried": "Tim O'Brien",
    "The Winter of Our Discontent": "John Steinbeck",
    "One Flew Over the Cuckoo's Nest": "Ken Kesey",
    "Driving on the Rim": "Thomas McGuane",
    "Fear and Loathing in Las Vegas": "Hunter S. Thompson",
    "The Collected Stories of Amy Hempel": "Amy Hempel",
    "A Tale of Two Cities": "Charles Dickens",
    "Wolf Hall": "Hilary Mantel",
    "All the King's Men": "Robert Penn Warren",
    "Growth of the Soil": "Knut Hamsun",
    "The Creative Act": "Rick Rubin",
    "Difference and Repetition": "Gilles Deleuze",
    "The Hours": "Michael Cunningham",
    "Omniscient Reader's Viewpoint": "Sing Shong",
    "Small Gods": "Terry Pratchett",
    "The Road": "Cormac McCarthy",
    "Butcher's Crossing": "John Williams",
    "Absalom, Absalom!": "William Faulkner",
    "Train Dreams": "Denis Johnson",
    "Gilead": "Marilynne Robinson",
    "The Troika": "Stepan Chapman",
    "Greenmantle": "John Buchan",
    "Nostromo": "Joseph Conrad",
    "Demon Copperhead": "Barbara Kingsolver",
    "Cloud Cuckoo Land": "Anthony Doerr",
    "No Country for Old Men": "Cormac McCarthy",
    "David Copperfield": "Charles Dickens",
    "White Bones": "Graham Masterton",
    "Of Mice and Men": "John Steinbeck",
    "Breakfast of Champions": "Kurt Vonnegut",
    "Downward to the Earth": "Robert Silverberg",
    "Musashi": "Eiji Yoshikawa",
    "The Alchemist": "Paulo Coelho",
    "Madame Bovary": "Gustave Flaubert",
    "The Warrior's Apprentice": "Lois McMaster Bujold",
    "The Wings of the Dove": "Henry James",
    "In Search of Lost Time": "Marcel Proust",
    "The Women": "Kristin Hannah",
    "Harry Potter": "J. K. Rowling",
    "The Time Traveler's Wife": "Audrey Niffenegger",
    "Geek Love": "Katherine Dunn",
    "The Gunslinger": "Stephen King",
    "Watchmen": "Alan Moore & Dave Gibbons",
    "The Sirens of Titan": "Kurt Vonnegut",
    "God Bless You, Mr. Rosewater": "Kurt Vonnegut",
    "Snow Crash": "Neal Stephenson",
    "Wuthering Heights": "Emily Brontë",
}

# (redditor, score, books named). One entry per top-level comment that counts,
# in the order the capture listed them. Titles are normalised to AUTHORS keys.
C = [
 ("RelaxatioNation", 177, ["Lonesome Dove"]),
 ("GeggingIn", 171, ["1984"]),
 ("Octarine_", 159, ["The Count of Monte Cristo"]),
 ("Teabagbomber", 125, ["Endurance"]),
 ("MikeLMP", 60, ["The Grapes of Wrath"]),
 ("Flipperyapper59", 51, ["Frankenstein", "Dracula", "The Haunting of Hill House"]),
 ("moonsharksquirrel", 50, ["One Hundred Years of Solitude"]),
 ("enzoblue64", 53, ["A Farewell to Arms"]),
 ("elitecloser", 50, ["East of Eden", "A Gentleman in Moscow", "Lolita", "Dandelion Wine"]),
 ("Tulips_Hyacinths", 45, ["Anna Karenina"]),
 ("Dirkem15", 41, ["11/22/63", "Lonesome Dove"]),
 ("Shadow_of_Moonlight1", 41, ["Brave New World", "Rubbernecker", "Ubik", "Solaris", "Fahrenheit 451"]),
 ("treefruit", 39, ["Piranesi"]),
 ("yards11", 38, ["Blood Meridian"]),
 ("Any-Walk1691", 37, ["11/22/63"]),
 ("Dee-tective", 34, ["The Old Man and the Sea", "The Picture of Dorian Gray"]),
 ("funbunny100", 35, ["Watership Down"]),
 ("Quankers", 32, ["Moby-Dick"]),
 ("Manofknees", 25, ["Lonesome Dove", "For Whom the Bell Tolls", "Endurance", "The Count of Monte Cristo", "Blood Meridian", "Stoner", "Hard Rain Falling"]),
 ("MajorNut", 20, ["To Kill a Mockingbird"]),
 ("fn_br", 21, ["Siddhartha"]),
 ("crowtrobot2001", 25, ["Catch-22"]),
 ("Sudden-Research9105", 19, ["Dune", "The Lord of the Rings"]),
 ("hotmisosoup", 16, ["11/22/63"]),
 ("es254", 16, ["Lonesome Dove"]),
 ("Embarrassed-Ad-605", 16, ["The Great Gatsby"]),
 ("Dire_Hulk", 15, ["For Whom the Bell Tolls"]),
 ("Dantefire107", 17, ["The Catcher in the Rye"]),
 ("Embarrassed-Ad-605", 15, ["The Bell Jar"]),
 ("itzykan", 14, ["One Hundred Years of Solitude"]),
 ("delveccio", 13, ["Lonesome Dove"]),
 ("deezoz", 13, ["Crime and Punishment"]),
 ("swisszimgirl79", 13, ["Pride and Prejudice"]),
 ("EmeraldBison", 12, ["Ulysses"]),
 ("Unlikely_Spinach", 14, ["Stoner"]),
 ("SpinalVinyl", 11, ["Don Quixote"]),
 ("New_Satisfaction22", 9, ["The Lord of the Rings", "The Hobbit", "The Silmarillion"]),
 ("Belch_Huggins", 11, ["Perfume"]),
 ("zealot_ratio", 8, ["Blood Meridian", "Suttree", "The Lord of the Rings", "The English Patient", "A Pale View of Hills", "The Remains of the Day", "The Aubrey–Maturin series", "The Dark Is Rising sequence", "The Round House", "The Plague of Doves", "The Narrow Road to the Deep North", "Accordion Crimes", "Les Misérables"]),
 ("ketzcm", 7, ["Lolita"]),
 ("Cydok1055", 7, ["The Overstory", "Spring Moon"]),
 ("JHam67", 5, ["Les Misérables"]),
 ("rollin20s", 6, ["Infinite Jest"]),
 ("Bkae25", 6, ["The Great Gatsby"]),
 ("bearheart", 6, ["Slaughterhouse-Five"]),
 ("oh2climb", 7, ["Jane Eyre"]),
 ("DigJust8037", 5, ["Gravity's Rainbow", "Star Maker"]),
 ("_pinotnoir", 4, ["Ulysses", "Frankenstein", "House of Leaves", "If on a Winter's Night a Traveler", "The Hitchhiker's Guide to the Galaxy", "Moby-Dick", "The Phantom Tollbooth", "One Day in the Life of Ivan Denisovich", "Eugene Onegin", "The Song of Achilles"]),
 ("UNaMean", 5, ["Les Misérables"]),
 ("Murph523", 5, ["Slaughterhouse-Five"]),
 ("dbrindley", 4, ["Matterhorn"]),
 ("2x2darkgreytile", 5, ["The Count of Monte Cristo", "Catch-22", "The Good Soldier Švejk", "The Fortunes of Wangrin", "The Tale of Genji"]),
 ("tastybeer", 5, ["You Can't Win"]),
 ("mickeyneely", 3, ["The Master and Margarita", "2666", "All About Love"]),
 ("Cambridge89", 4, ["Blood Meridian"]),
 ("Embarrassed-Ad-605", 4, ["The Secret History", "The Little Friend", "The Goldfinch"]),
 ("bucket_overlord", 3, ["Heart of Darkness"]),
 ("yachtmaster001", 4, ["East of Eden", "The Aubrey–Maturin series", "The Rise and Fall of the Third Reich", "The Forgotten Soldier"]),
 ("zqpmx", 4, ["Gödel, Escher, Bach"]),
 ("duncandun", 4, ["The Book of the New Sun"]),
 ("rooked153", 3, ["The Grapes of Wrath"]),
 ("blankenstaff", 3, ["Jane Eyre"]),
 ("pozza66", 4, ["One Hundred Years of Solitude"]),
 ("ExpertAd1710", 4, ["The Handmaid's Tale", "Jane Eyre"]),
 ("Prairie2Pacific", 3, ["The Grapes of Wrath", "Frankenstein"]),
 ("Beginning_Month_2702", 4, ["Pachinko"]),
 ("Ziopover", 3, ["The Divine Comedy"]),
 ("Live_Cockroach8931", 3, ["The Sword of Kaigen"]),
 ("Embarrassed-Ad-605", 3, ["Brideshead Revisited"]),
 ("Mabtizzy", 3, ["Bleak House"]),
 ("DramaticHumor5363", 3, ["Pride and Prejudice"]),
 ("Quankers", 3, ["The Great War for Civilisation"]),
 ("drqlx", 3, ["Moby-Dick"]),
 ("Quankers", 3, ["American Tabloid"]),
 ("dusbintrousers", 3, ["Under the Volcano"]),
 ("Von-Konigs", 3, ["War and Peace"]),
 ("NirgalFromMars", 3, ["The Mars Trilogy", "The Sea and Summer", "Piranesi", "Mirror Dance"]),
 ("_peanut_butter_bear_", 3, ["A Portrait of the Artist as a Young Man", "Cannery Row", "East of Eden", "Perfume", "Henderson the Rain King", "A Confederacy of Dunces", "Ulysses", "Lolita", "The Old Man and the Sea"]),
 ("m_faustus", 3, ["Catch-22"]),
 ("Breauxaway90", 3, ["East of Eden"]),
 ("JoyDe-vision", 3, ["Blood Meridian"]),
 ("Downtown_Lemon5747", 3, ["Demian"]),
 ("elchinguito", 3, ["A Confederacy of Dunces", "Annihilation", "Beloved", "Matterhorn", "Contact", "Adventures of Huckleberry Finn"]),
 ("PresentationKey4373", 2, ["The Book of the New Sun"]),
 ("sexyimmigrant1998", 2, ["The Hunger Games"]),
 ("deannatoi", 2, ["Titus Groan"]),
 ("herbalhippie", 2, ["The Haunting of Hill House"]),
 ("HarvestMourn", 2, ["The Wall"]),
 ("lemals13", 2, ["Dune", "Hyperion"]),
 ("Old-Ingenuity-4346", 2, ["A Voyage to Arcturus"]),
 ("LernSumtin", 2, ["Narcissus and Goldmund"]),
 ("bearheart", 2, ["Jitterbug Perfume"]),
 ("brooklynguitarguy", 2, ["Sister Carrie"]),
 ("hexenkesse1", 2, ["The Thirty Years War", "The Autumn of the Middle Ages"]),
 ("raheinlein3", 2, ["The Desert of Souls"]),
 ("PrivateResidence", 2, ["Suttree"]),
 ("Nonstandard_Deviate", 2, ["The Grapes of Wrath"]),
 ("imjorman", 2, ["Stoner"]),
 ("RIBCAGESTEAK", 2, ["The Call of the Wild"]),
 ("CornwallaceJuicerton", 2, ["The Lord of the Rings"]),
 ("Closet_Scientist", 2, ["A Farewell to Arms"]),
 ("ikadell", 2, ["Anathem"]),
 ("Alert_Practice_227", 2, ["Animal Farm"]),
 ("YukariYakum0", 2, ["The Shining"]),
 ("follower-of-st-jimmy", 2, ["The Catcher in the Rye"]),
 ("Mitzy1612", 2, ["East of Eden"]),
 ("Cmojo69", 2, ["Underworld"]),
 ("Adiantum-Veneris", 2, ["The Master and Margarita"]),
 ("tychoist", 2, ["Man's Search for Meaning"]),
 ("wombatbridgehunt", 2, ["The Stranger"]),
 ("YetiMarauder", 2, ["John Dies at the End"]),
 ("Icy-Pear-2241", 2, ["The Mahabharata"]),
 ("InternationalFig400", 2, ["Don Quixote"]),
 ("Bodhidharma1", 1, ["Shōgun"]),
 ("lookitskris", 1, ["A Storm of Swords"]),
 ("treefruit", 1, ["Annihilation"]),
 ("Jberts77", 1, ["The Girl with the Dragon Tattoo"]),
 ("enlighteningbug", 1, ["One Hundred Years of Solitude"]),
 ("pintotop", 1, ["Perfume"]),
 ("Andray_Bolkonsky", 1, ["War and Peace"]),
 ("topherthepest", 1, ["The Wheel of Time"]),
 ("catwith4peglegs", 1, ["I Keep My Exoskeletons to Myself"]),
 ("Ok_Concert_3089", 1, ["The Grapes of Wrath"]),
 ("RogerSmith123456", 1, ["The Bible"]),
 ("Infinite_Anybody_113", 1, ["The Heroes"]),
 ("interstatebus", 1, ["Trust"]),
 ("raheinlein3", 1, ["The Dresden Files"]),
 ("Feature_Agitated", 1, ["The Lord of the Rings", "The Hobbit", "Circe", "Dracula", "To Kill a Mockingbird", "Dungeon Crawler Carl"]),
 ("KrayZKatz", 1, ["Crime and Punishment", "Gang Leader for a Day", "Good Morning, Monster"]),
 ("Scholarish", 1, ["Rebecca"]),
 ("Miochiiii", 1, ["The Way of Kings"]),
 ("pv77uck3r", 1, ["The Book of the New Sun"]),
 ("Charming_History7423", 1, ["Randamoozham"]),
 ("Difficult_End_3447", 1, ["The Brothers Karamazov", "Frankenstein", "Pedro Páramo"]),
 ("nickmcgimmick", 1, ["Gormenghast"]),
 ("Pelvisleslie", 1, ["The Pillars of the Earth", "Magician"]),
 ("Working_Rub_8278", 1, ["Fahrenheit 451", "1984", "11/22/63", "Brave New World", "The Curious Incident of the Dog in the Night-Time", "Slaughterhouse-Five", "Fight Club", "Cujo", "The Jungle Book", "Frankenstein", "Dracula", "The Maltese Falcon", "The War of the Worlds"]),
 ("squishypoo91", 1, ["Annihilation"]),
 ("roominating237", 1, ["Angela's Ashes"]),
 ("Gambler136", 1, ["The Brothers Karamazov"]),
 ("Electronic_Cress2684", 1, ["Dead Souls"]),
 ("Electronic_Cress2684", 1, ["The Chronicles of Barsetshire"]),
 ("H4xXxIsH", 1, ["The Remains of the Day"]),
 ("Maria_Walshh", 1, ["Roadside Picnic", "The Fall"]),
 ("wexfordred", 1, ["The Metamorphosis", "Gravity's Rainbow", "Mason & Dixon", "Buddenbrooks", "The Magic Mountain", "The Adventures of Augie March", "One Hundred Years of Solitude", "The Master and Margarita", "If on a Winter's Night a Traveler", "Labyrinths", "Europe Central", "The Bloody Chamber", "Ice", "The Sailor Who Fell from Grace with the Sea"]),
 ("kittyfluff717", 1, ["The Hunger Games"]),
 ("Feeling_Valuable5239", 1, ["The Overcoat"]),
 ("GreatKingRat666", 1, ["It"]),
 ("Madi27", 1, ["Piranesi"]),
 ("Material-Divide-4452", 1, ["Invicto"]),
 ("SavingQueelag", 1, ["The Lord of the Rings"]),
 ("bleak_biscuit", 1, ["King Rat"]),
 ("Shinobi2354", 1, ["Stoner"]),
 ("Shinobi2354", 1, ["The Brothers Karamazov"]),
 ("johnaceofhearts", 1, ["1984", "Jonathan Livingston Seagull", "The Bible"]),
 ("Direct-Tank387", 1, ["The Magic Mountain"]),
 ("Significant_Stand_95", 1, ["East of Eden", "Lonesome Dove", "The Count of Monte Cristo", "A Storm of Swords", "Slaughterhouse-Five", "Stoner", "The Brothers Karamazov", "One Hundred Years of Solitude"]),
 ("hiddenstar13", 1, ["The Book Thief"]),
 ("LocoMod", 1, ["Zen and the Art of Motorcycle Maintenance"]),
 ("BarryZuckercornEsq", 1, ["The Things They Carried"]),
 ("Opposite-Presence349", 1, ["The Great Gatsby"]),
 ("Toveladi", 1, ["The Winter of Our Discontent", "One Flew Over the Cuckoo's Nest", "Driving on the Rim", "Fear and Loathing in Las Vegas", "11/22/63"]),
 ("m00nlighter_", 1, ["The Collected Stories of Amy Hempel"]),
 ("Crook3d", 1, ["Shōgun"]),
 ("Temporary-Reach4668", 1, ["Les Misérables", "A Tale of Two Cities"]),
 ("Longjumping-Ask2746", 1, ["Les Misérables", "War and Peace", "Siddhartha"]),
 ("-SirBaphomet-", 1, ["The Picture of Dorian Gray"]),
 ("hornetttttttttttt", 1, ["Wolf Hall"]),
 ("bkk-bos", 1, ["All the King's Men"]),
 ("SnooDonkeys4853", 1, ["Blood Meridian", "Growth of the Soil"]),
 ("CoordAndScholar", 1, ["The Creative Act"]),
 ("LiesofCogito", 1, ["Difference and Repetition"]),
 ("Manamehendra", 1, ["The Master and Margarita", "Lolita", "Wolf Hall"]),
 ("Pearl-wonders2022", 1, ["The Hours"]),
 ("Loose-Drive-9611", 1, ["Moby-Dick"]),
 ("anoraq", 1, ["The Grapes of Wrath"]),
 ("themysteriouscoconut", 1, ["Omniscient Reader's Viewpoint"]),
 ("Curious-Jackfruit563", 1, ["Piranesi"]),
 ("ObscenelyBoring", 1, ["Crime and Punishment"]),
 ("skrunkarus", 1, ["Small Gods"]),
 ("Negative_Ad3286", 1, ["The Catcher in the Rye"]),
 ("FlyingCarpetMonster", 1, ["Lonesome Dove", "The Grapes of Wrath", "Blood Meridian", "The Road", "Butcher's Crossing", "Les Misérables", "Dune", "Absalom, Absalom!", "Train Dreams", "Gilead"]),
 ("Asleep-Draft-5148", 1, ["The Troika"]),
 ("moneybags2410", 1, ["Greenmantle"]),
 ("Korf", 1, ["The Master and Margarita"]),
 ("aditya28", 1, ["Catch-22"]),
 ("DecimusValorum", 1, ["Fahrenheit 451"]),
 ("haponto", 1, ["Siddhartha"]),
 ("DepartureHuge", 1, ["Nostromo"]),
 ("cb_pl181", 1, ["Infinite Jest", "A Confederacy of Dunces", "Demon Copperhead", "The Old Man and the Sea", "Cloud Cuckoo Land", "No Country for Old Men", "The Road"]),
 ("Specific_Hyena4637", 1, ["David Copperfield"]),
 ("5MinuteReads", 1, ["White Bones"]),
 ("industrialstr", 1, ["The Great Gatsby", "Of Mice and Men", "Watership Down", "Slaughterhouse-Five", "Breakfast of Champions", "The Road", "Blood Meridian", "No Country for Old Men", "Downward to the Earth", "Roadside Picnic", "Solaris", "1984", "The Wall"]),
 ("Busy_Reading_5103", 1, ["Musashi"]),
 ("jgreen110715", 1, ["The Alchemist"]),
 ("borgeanmccarthy", 1, ["Don Quixote", "Heart of Darkness", "Blood Meridian", "Madame Bovary", "One Hundred Years of Solitude", "Pedro Páramo"]),
 ("phishfood4me", 1, ["The Warrior's Apprentice"]),
 ("tSpacklemaster", 1, ["The Wings of the Dove"]),
 ("plot--twisted", 1, ["In Search of Lost Time"]),
 ("Fins-1", 1, ["The Women"]),
 ("AlisterKubo", 0, ["Crime and Punishment"]),
 ("bellator_ecclesiam", 0, ["Crime and Punishment"]),
 ("Winter_Beach2860", 0, ["Harry Potter"]),
 ("ProdigalButcher", 0, ["Absalom, Absalom!"]),
 ("grrhss", -1, ["The Time Traveler's Wife", "Geek Love", "The Gunslinger", "Watchmen"]),
 ("kittens_and_jesus", -2, ["The Sirens of Titan", "God Bless You, Mr. Rosewater", "War and Peace", "Siddhartha", "House of Leaves", "Snow Crash", "Anathem", "Wuthering Heights"]),
]

people = collections.defaultdict(set)
votes = collections.Counter()
for who, score, books in C:
    for b in books:
        assert b in AUTHORS, b
        if who not in people[b]:
            people[b].add(who)
            votes[b] += score

order = sorted(people, key=lambda b: (-len(people[b]), -votes[b], b.lower()))
src = {"label": "r/AskReddit", "url": URL}
rows = [{"key": f"mast|{b}", "lead": f"{len(people[b])}×", "sec": AUTHORS[b], "pri": b, "src": src}
        for b in order]

LIST = {
    "slug": SLUG,
    "title": "Truly a Masterpiece",
    "kind": "Tally",
    "verb": "read",
    "desc": "r/AskReddit, asked which books are truly masterpieces. McCarthy on top by head count; a Western about two old Texas Rangers on top by upvotes.",
    "cols": ["Named by", "Author", "Title", "Look up · source"],
    "gr": "sec",
    "sources": [{"url": URL, "label": "Reddit · r/AskReddit",
                 "q": "What books are truly masterpieces?",
                 "meta": "2026 · 216 points · 407 comments"}],
    "note": ("Counted by distinct redditor; where a comment named several books, each one counts, "
             "and upvotes on the naming comments break ties. One capture of the thread, sorted by top, "
             "replies stripped: 224 top-level answers. Left out: the asker's own list, answers naming only "
             "an author or a body of work (&ldquo;All Charles Dickens&rdquo;), books mentioned without being "
             "called a masterpiece, and the joke answers — a run of picture books, a Windows 95 manual, the "
             "Bluebook. Series stay as one row where they were answered as a series."),
    "rows": rows,
}

shelves = json.load(open(PATH))
books = [s for s in shelves if s["slug"] == "books"][0]
books["lists"] = [l for l in books["lists"] if l["slug"] != SLUG] + [LIST]
json.dump(shelves, open(PATH, "w"), ensure_ascii=False, indent=1)

print(len(rows), "books from", len({w for w, _, _ in C}), "redditors,",
      sum(len(p) for p in people.values()), "mentions")
for b in order[:15]:
    print(f"  {len(people[b]):>2}×  {b} ({votes[b]} pts)")
