import re, json
lines=[l.split(" :: ",1) for l in open("/home/claude/museums.txt").read().split("\n") if " :: " in l]
T=[
("Musée d'Orsay","Paris",r"orsay|orsee|d.orsay"),
("The British Museum","London",r"british museum"),
("The Metropolitan Museum of Art","New York",r"metropolitan museum|\bthe met\b|\bmet\b(?=[,\.]|$)|the met,"),
("The Louvre","Paris",r"louvre|louve"),
("Van Gogh Museum","Amsterdam",r"van gogh museum|van gogh\b"),
("Rijksmuseum","Amsterdam",r"rijksmuseum|rijkmuseum"),
("Vasa Museum","Stockholm",r"vasa|våsa"),
("Museo Nacional de Antropología","Mexico City",r"anthropolog[iy].{0,20}mexico|mexico city.{0,20}anthropolog|antropolog|museo de antropolog"),
("Deutsches Museum","Munich",r"deutsches museum|deutsches"),
("Galleria Borghese","Rome",r"borghese|boghese"),
("Museo del Prado","Madrid",r"\bprado\b"),
("Museum of Modern Art (MoMA)","New York",r"\bmoma\b|museum of modern art.{0,15}(nyc|new york)"),
("The Getty Center","Los Angeles",r"\bgetty\b"),
("Art Institute of Chicago","Chicago",r"art institute"),
("Galleria degli Uffizi","Florence",r"uffizi|uffizzi"),
("Centre Pompidou","Paris",r"pompidou"),
("Natural History Museum","London",r"natural history museum.{0,15}london|london.{0,25}natural history"),
("American Museum of Natural History","New York",r"american museum of natural history|natural history.{0,12}(nyc|new york)|museum of natural history in nyc"),
("The Hermitage","St Petersburg",r"hermitage"),
("Musée de l'Orangerie","Paris",r"orangerie"),
("Louisiana Museum of Modern Art","Humlebæk",r"louisiana museum|louisiana mo?ma|the louisiana"),
("Galleria dell'Accademia","Florence",r"accademia|accedemia|academia gallery|acade?mia gallery"),
("National WWII Museum","New Orleans",r"(ww2|wwii|world war ii|world war 2).{0,25}new orleans|new orleans.{0,20}(ww2|wwii)"),
("Victoria and Albert Museum","London",r"victoria and albert|victoria & albert|\bv and a\b|victoria&albert"),
("Vatican Museums","Vatican City",r"vatican"),
("The Met Cloisters","New York",r"cloisters"),
("Reina Sofía","Madrid",r"reina sofia|reina sofía"),
("Yad Vashem","Jerusalem",r"yad ?va ?shem|yad vesham"),
("Field Museum","Chicago",r"field museum|the field\b"),
("Smithsonian National Air and Space Museum","Washington DC",r"air and space|udvar.?hazy"),
("Museum of Broken Relationships","Zagreb",r"broken relationships"),
("Anne Frank House","Amsterdam",r"anne frank"),
("Te Papa Tongarewa","Wellington",r"te papa"),
("Newseum","Washington DC",r"newseum"),
("National September 11 Memorial Museum","New York",r"9/11"),
("Acropolis Museum","Athens",r"acropolis"),
("Albertina","Vienna",r"albertina"),
("Belvedere","Vienna",r"belvedere"),
("Kunsthistorisches Museum","Vienna",r"kunsthistorisches"),
("Frick Collection","New York",r"\bfrick\b"),
("Isabella Stewart Gardner Museum","Boston",r"isabell?a? stewart gardn?e?r"),
("Barnes Foundation","Philadelphia",r"barnes"),
("Whitney Museum of American Art","New York",r"whitney"),
("Guggenheim Museum","New York",r"guggenheim nyc|guggenheim in ny|guggenheim museum"),
("Peggy Guggenheim Collection","Venice",r"peggy guggenheim"),
("Guggenheim Museum Bilbao","Bilbao",r"moma in bilbao|guggenheim bilbao"),
("Museum of Musical Instruments","Brussels",r"musical instruments? museum.{0,15}brussels|museum of musical instruments"),
("Musical Instrument Museum","Phoenix",r"musical instrument museum.{0,15}phoenix|phoenix"),
("Musée Rodin","Paris",r"rodin museum|the rodin"),
("Musée Picasso","Paris",r"picasso museum|musee picasso"),
("Kröller-Müller Museum","Otterlo",r"kroller|kröller"),
("Hiroshima Peace Memorial Museum","Hiroshima",r"hiroshima"),
("National Museum of the US Air Force","Dayton",r"(usaf|us air force|united states air force)"),
("National Palace Museum","Taipei",r"national palace museum"),
("Museum of Old and New Art (MONA)","Hobart",r"\bmona\b|old and new art"),
("Detroit Institute of Arts","Detroit",r"detroit institute|\bdia\b"),
("The Henry Ford","Dearborn",r"henry ford"),
("Neues Museum","Berlin",r"neues museum"),
("Pergamon Museum","Berlin",r"pergam"),
("DDR Museum","Berlin",r"ddr museum"),
("Stasi Museum","Berlin",r"stasi"),
("Museum of the Second World War","Gdańsk",r"gdansk|gdańsk"),
("National Museum of Scotland","Edinburgh",r"national museum of scotland"),
("Surgeons' Hall Museums","Edinburgh",r"surgeon"),
("Mütter Museum","Philadelphia",r"mutter|mütter"),
("Museo Galileo","Florence",r"museo galileo"),
("Museo del Oro","Bogotá",r"museo de oro|museo del oro"),
("Egyptian Museum","Cairo",r"cairo|egyptian museum"),
("Pitt Rivers Museum","Oxford",r"pitt rivers"),
("Ashmolean Museum","Oxford",r"ashmolean"),
("Petrie Museum of Egyptian Archaeology","London",r"petrie"),
("Tate Modern","London",r"tate modern|the tate\b"),
("The National Gallery","London",r"national gallery\b(?!.{0,12}(victoria|ireland|irish))"),
("Sir John Soane's Museum","London",r"soane"),
("Churchill War Rooms","London",r"churchill"),
("Bletchley Park","Milton Keynes",r"bletchley"),
("Titanic Belfast","Belfast",r"titanic"),
("Mary Rose Museum","Portsmouth",r"mary rose"),
("Ny Carlsberg Glyptotek","Copenhagen",r"glyptotek"),
("Icelandic Phallological Museum","Reykjavík",r"penis museum|phallolog"),
("Mucha Museum","Prague",r"mucha"),
("Museum of the Occupation of Latvia","Riga",r"occupation of latvia"),
("Oceanographic Museum","Monaco",r"oceanographic"),
("Naturhistorisches Museum","Vienna",r"vienna natural history"),
("Nelson-Atkins Museum of Art","Kansas City",r"nelson.?atkins"),
("Cleveland Museum of Art","Cleveland",r"cleveland art|cleveland museum"),
("Legacy Museum","Montgomery",r"legacy museum"),
("National Civil Rights Museum","Memphis",r"civil rights museum"),
("National Museum of African American History and Culture","Washington DC",r"african.?american national history|african american history"),
("Exploratorium","San Francisco",r"exploratorium"),
("Museum of Science","Boston",r"museum of science in boston|museum of science.{0,10}boston"),
("Museum of Science and Industry","Chicago",r"science and industry"),
("Houston Museum of Natural Science","Houston",r"houston museum"),
("Royal Tyrrell Museum","Drumheller",r"tyrell|tyrrell"),
("Rock and Roll Hall of Fame","Cleveland",r"rock and roll hall"),
("ABBA The Museum","Stockholm",r"abba"),
("Fotografiska","Stockholm",r"fotografiska"),
("Bata Shoe Museum","Toronto",r"bata shoe"),
("Canada Aviation and Space Museum","Ottawa",r"canada aviation"),
("Canadian Museum for Human Rights","Winnipeg",r"human rights museum"),
("Oklahoma City National Memorial","Oklahoma City",r"oklahoma city|\bOKC\b"),
("USS Midway Museum","San Diego",r"uss midway"),
("Museum of Flight","Seattle",r"museum of flight"),
("Titan Missile Museum","Sahuarita",r"titan missile"),
("Arizona-Sonora Desert Museum","Tucson",r"sonoran desert|sonora desert"),
("Museum of Jurassic Technology","Los Angeles",r"jurassic technology"),
("Fondation Beyeler / Chaplin's World","—",r"__never__"),
("Ghibli Museum","Tokyo",r"ghibli"),
("Otsuka Museum of Art","Naruto",r"otsuka"),
("Hakone Open-Air Museum","Hakone",r"open air museum.{0,12}hakone|hakone"),
("National Museum of Singapore","Singapore",r"national museum of singapore"),
("ArtScience Museum","Singapore",r"artscience"),
("Tuol Sleng Genocide Museum","Phnom Penh",r"tuol sleng"),
("Kigali Genocide Memorial","Kigali",r"rwanda genocide|kigali"),
("Apartheid Museum","Johannesburg",r"apartheid"),
("National Gallery of Victoria","Melbourne",r"national gallery of victoria"),
("Museum of Innocence","Istanbul",r"museum of innocence"),
("Alte Pinakothek","Munich",r"alte pinakothek"),
("Mercedes-Benz Museum","Stuttgart",r"mercedes"),
("Harley-Davidson Museum","Milwaukee",r"harley"),
("Miniatur Wunderland","Hamburg",r"miniatur"),
("Teylers Museum","Haarlem",r"teylers"),
("Rembrandt House Museum","Amsterdam",r"rembrandt.s house"),
("Dutch Resistance Museum","Amsterdam",r"resistance museum"),
("Eise Eisinga Planetarium","Franeker",r"eisinga"),
("Musée Marmottan Monet","Paris",r"marmottan"),
("Musée de Cluny","Paris",r"cluny|middle ages museum"),
("Musée Carnavalet","Paris",r"carnavalet"),
("Musée Guimet","Paris",r"guimet"),
("Musée des Arts et Métiers","Paris",r"arts et met"),
("Fundació Joan Miró","Barcelona",r"joan miro|miro museum"),
("Dalí Theatre-Museum","Figueres",r"dali museum in figueres|salvador dali museum"),
("Palace of Versailles","Versailles",r"versailles"),
("Forbidden City","Beijing",r"forbidden city"),
("Wagner Free Institute of Science","Philadelphia",r"wagner free"),
("Cooper Hewitt","New York",r"cooper hewitt"),
("Toledo Museum of Art","Toledo",r"toledo museum"),
("Albright-Knox / Buffalo AKG","Buffalo",r"albright"),
("Yale University Art Gallery","New Haven",r"yale university art"),
("Harvard Museum of Natural History","Cambridge, MA",r"harvard museum"),
("Neue Galerie","New York",r"neue gall?erie"),
("The Huntington","San Marino",r"huntington"),
("Getty Villa","Pacific Palisades",r"getty villa"),
("Museo Soumaya","Mexico City",r"soumaya"),
("Capitoline Museums","Rome",r"capitolino|capitoline"),
("Castello Sforzesco","Milan",r"sforzesco"),
("Musée Marc Chagall","Nice",r"chagall"),
("Neon Muzeum","Warsaw",r"neon muzeum|neon museum"),
("National Museum in Warsaw","Warsaw",r"national museum in warsaw"),
("Aboa Vetus & Ars Nova","Turku",r"aboa vetus"),
("National Museum of Oman","Muscat",r"museum of oman"),
("Birmingham Museum & Art Gallery","Birmingham",r"birmingham museum"),
("St Fagans National Museum of History","Cardiff",r"st\.? fagans|fagens"),
("Hospital in the Rock","Budapest",r"hospital in the rock"),
("Red History Museum","Dubrovnik",r"red history"),
("Fortress Museum","Salzburg",r"fortress museum"),
("Museum of London","London",r"museum of london"),
("Danish Maritime Museum","Helsingør",r"danish maritime"),
("Het Scheepvaartmuseum","Amsterdam",r"maritime museum in amsterdam"),
("International Maritime Museum","Hamburg",r"maritime museum in hamburg"),
("Tropenmuseum","Amsterdam",r"tropenmuseum"),
("Tretyakov Gallery","Moscow",r"tretyakov"),
("Frida Kahlo Museum","Mexico City",r"frida kahlo"),
("Shin-Yokohama Ramen Museum","Yokohama",r"ramen museum"),
("National Mustard Museum","Middleton",r"mustard museum"),
("Marvin's Marvelous Mechanical Museum","Farmington Hills",r"marvin"),
("Omaka Aviation Heritage Centre","Blenheim",r"omaka"),
("Anchorage Museum","Anchorage",r"anchorage museum"),
("Patan Museum","Kathmandu",r"patan"),
("Smithsonian National Museum of American History","Washington DC",r"american history museum|smithsonian american history"),
("National Postal Museum","Washington DC",r"postal museum"),
("Franklin Institute","Philadelphia",r"ben franklin institute|franklin institute"),
("Courtauld Gallery","London",r"courtauld"),
("Museum of Life and Science","Durham",r"life and science"),
("San Bernardino County Museum","Redlands",r"san bernardino"),
("Pima Air & Space Museum","Tucson",r"pima air"),
]
out=[]
for name,city,pat in T:
    rx=re.compile(pat,re.I)
    n=len({u for u,b in lines if rx.search(b)})
    if n: out.append((name,city,n))
out.sort(key=lambda r:(-r[2], r[0].lower()))
for n,c,k in out[:30]: print(k,n,"—",c)
print("TOTAL", len(out), sum(x[2] for x in out))
json.dump(out, open("/tmp/mu.json","w"), ensure_ascii=False)
