"""r/MusicRecommendations — "What are some of the most romantic songs you've ever heard?"

The third music tally, and the one that makes the shape of the other two legible.

  The Most Beautiful Song  — people converge. There is a right answer and a
                             few hundred people circle it.
  The Best Song Ever       — people diverge completely. 237 redditors, 469
                             different songs. It is a question about them.
  Most Romantic Song       — sits in between, and for a reason worth naming:
                             romance is a genre before it is a feeling. Half
                             the thread is standards (Etta James, Elvis, Otis
                             Redding, "Wonderful Tonight") and the other half
                             is someone's private evidence — a wedding song, a
                             death-metal track about a corpse, a Rammstein song
                             about cannibalism. The canon and the confession
                             sit in the same list.

Counting, same rule as the book and film tallies: by distinct redditor. Naming
counts and agreeing counts ("Second I will follow you into the dark" is a
vote); quoting a lyric back at someone is not. The asker's own pick — Find New
Ways by Dan Mangan — is excluded, as in every other tally here.

Two judgement calls specific to this thread:

  - Reddit's flattened text loses reply depth, so a bare "Yes!" under a chain
    is credited to the nearest named song. Where that was genuinely unreadable
    the reply was dropped rather than guessed.
  - People who named a whole artist or album rather than a song ("every Sade
    song", "most songs by Kali Uchis") are not counted. The question asked for
    songs, and a list of songs cannot hold an artist.

Captured from the thread's "best" and "old" orderings and merged, because a
single fetch truncates before the end.
"""
import csv
import json
from collections import defaultdict

THREAD = {
    "q": "What are some of the most romantic songs you've ever heard?",
    "site": "Reddit · r/MusicRecommendations",
    "year": 2024,
    "meta": "164 points · 479 comments",
    "url": "https://www.reddit.com/r/MusicRecommendations/comments/1dmzni9/what_are_some_of_the_most_romantic_songs_youve/",
}

# redditor -> [(song, artist), ...]
B = {
"Joe-Division2889": [("This Must Be the Place (Naive Melody)", "Talking Heads")],
"Born-Sea-8044": [("This Must Be the Place (Naive Melody)", "Talking Heads")],
"miseeker": [("The Air That I Breathe", "The Hollies")],
"karma_the_sequel": [("The Air That I Breathe", "The Hollies"),
  ("Lover, You Should've Come Over", "Jeff Buckley"),
  ("I'll Be There Before the Next Teardrop Falls", "Freddy Fender"),
  ("I Drove All Night", "Cyndi Lauper"),
  ("Dance Me to the End of Love", "Leonard Cohen"),
  ("These Arms of Mine", "Otis Redding"),
  ("The Way You Look Tonight", "Tony Bennett"),
  ("Thunder Road", "Bruce Springsteen"),
  ("She", "Elvis Costello"),
  ("Crash Into Me", "Dave Matthews Band"),
  ("Into the Mystic", "Van Morrison")],
"Ringren": [("Lover, You Should've Come Over", "Jeff Buckley")],
"97_mentality": [("Lover, You Should've Come Over", "Jeff Buckley")],
"bookishkelly1005": [("Lover, You Should've Come Over", "Jeff Buckley"),
  ("Wonderful Tonight", "Eric Clapton")],
"Marshmallow_Fries": [("Lover, You Should've Come Over", "Jeff Buckley")],
"Relative_Tie3360": [("Lover, You Should've Come Over", "Jeff Buckley"),
  ("Morning Theft", "Jeff Buckley")],
"Fantastic-Title2267": [("What Love Has Joined Together", "Smokey Robinson")],
"Cheesus_K_Reist": [("We've Got Tonight", "Bob Seger")],
"DrockTipps": [("Fooled Around and Fell in Love", "Elvin Bishop"),
  ("Friday I'm in Love", "The Cure")],
"Hollow_Dreamer_": [("Fooled Around and Fell in Love", "Elvin Bishop")],
"GreenandBlue12": [("Maybe I'm Amazed", "Paul McCartney")],
"JezmundBeserker": [("Unchained Melody", "The Righteous Brothers")],
"Lightning493": [("Can't Help Falling in Love", "Elvis Presley")],
"Inevitable_Total_816": [("I'll Be There Before the Next Teardrop Falls", "Freddy Fender")],
"LeaderSanctity1999": [("I'll Be There Before the Next Teardrop Falls", "Freddy Fender")],
"kingofrr": [("I'll Be There Before the Next Teardrop Falls", "Freddy Fender"),
  ("Always on My Mind", "Elvis Presley")],
"Timstunes": [("If I Should Fall Behind", "Bruce Springsteen"),
  ("I Knew I Loved You", "Savage Garden")],
"crashcartjockey": [("I Drove All Night", "Roy Orbison"),
  ("At Last", "Etta James"),
  ("The Very Thought of You", "Etta James")],
"Anablue": [("Truly Madly Deeply", "Savage Garden"),
  ("Miracles", "Jefferson Starship")],
"AlilAwesome81": [("Lay Lady Lay", "Bob Dylan")],
"SylvieL7": [("At Last", "Etta James")],
"TheVicomtedeChagny": [("Francesca", "Hozier"), ("In a Week", "Hozier"),
  ("I Will Follow You Into the Dark", "Death Cab for Cutie")],
"alexandra887": [("I Will Follow You Into the Dark", "Death Cab for Cutie")],
"msa0675": [("Wonderful Tonight", "Eric Clapton")],
"DaisyPanda245": [("I Told You So", "Randy Travis"), ("Anymore", "Travis Tritt"),
  ("Forever and Ever, Amen", "Randy Travis")],
"Apprehensive_Day_496": [("Forever and Ever, Amen", "Randy Travis")],
"AccomplishedLeader76": [("Somebody", "Depeche Mode"), ("I'll Follow You", "Shinedown"),
  ("High Road", "Three Days Grace")],
"nopslide__": [("Into the Mystic", "Van Morrison")],
"Affectionate_Sir4212": [("Here I Am (Come and Take Me)", "Al Green"),
  ("In My Life", "The Beatles"), ("Words of Love", "Buddy Holly"),
  ("We've Only Just Begun", "The Carpenters"),
  ("I Will Always Love You", "Dolly Parton")],
"creswitch": [("Annie's Song", "John Denver")],
"pottedPlant_64": [("Annie's Song", "John Denver")],
"Appropriate_Link_837": [("Lady", "Kenny Rogers")],
"HappySloth213": [("Lady", "Kenny Rogers"), ("Reminiscing", "Little River Band")],
"namersrockandroll": [("Lady", "Styx"), ("Something", "The Beatles"),
  ("Cherish", "The Association"), ("My Cherie Amour", "Stevie Wonder")],
"GCKrazy": [("Against All Odds", "Phil Collins")],
"pcm15": [("Wild Is the Wind", "Nina Simone"), ("I Love You", "Lou Reed"),
  ("Lovesong", "The Cure"),
  ("Nights Are Forever Without You", "England Dan & John Ford Coley"),
  ("Colour My World", "Chicago")],
"enola007": [("Wicked Game", "Chris Isaak")],
"Art-to-choke-hearts": [("Cocoon", "Björk"), ("Hysteric", "Yeah Yeah Yeahs"),
  ("Attitude", "Alien Ant Farm"), ("Put Your Money on Me", "Arcade Fire"),
  ("Everything to Nothing", "Manchester Orchestra"), ("I See You", "MISSIO"),
  ("People as Places as People", "Modest Mouse"), ("Lions", "The Features"),
  ("Lovesong", "The Cure"), ("Somebody New", "Joywave"),
  ("Origin of Love", "Hedwig and the Angry Inch"), ("Maps", "Yeah Yeah Yeahs"),
  ("I'm on Call", "Kings of Leon")],
"reillywalker195": [("Time After Time", "Cyndi Lauper"),
  ("Dead in the Water", "Noel Gallagher")],
"down-up-dog": [("Time After Time", "Cyndi Lauper"), ("The Dress", "Dijon"),
  ("Bless the Telephone", "Labi Siffre"), ("God Only Knows", "The Beach Boys")],
"ali_j_ashraf": [("Fairytale of New York", "The Pogues")],
"Spectre_Mountain": [("Unchained Melody", "The Righteous Brothers")],
"algx15": [("Nothing's Gonna Stop Us Now", "Starship"), ("The Flame", "Cheap Trick"),
  ("Say You Will", "Foreigner"), ("What About Me?", "Moving Pictures"),
  ("If You Don't Know Me by Now", "Simply Red"),
  ("When I See You Smile", "Bad English"),
  ("I Don't Wanna Live Without Your Love", "Chicago"),
  ("We Belong", "Pat Benatar"), ("Alone", "Heart"),
  ("Say You, Say Me", "Lionel Richie"),
  ("Why Can't This Be Love", "Van Halen")],
"BaldyCarrotTop": [("The Flame", "Cheap Trick"),
  ("South City Midnight Lady", "The Doobie Brothers"), ("Beth", "Kiss"),
  ("Faithfully", "Journey")],
"The_Forsaken_Cookie": [("She's Got a Way", "Billy Joel")],
"Djdjdjdjdj10": [("By Your Side", "Sade")],
"turquoisenightfall": [("These Arms of Mine", "Otis Redding"),
  ("That's How Strong My Love Is", "Otis Redding"),
  ("I've Been Loving You Too Long (To Stop Now)", "Otis Redding")],
"zenny517": [("When a Man Loves a Woman", "Percy Sledge")],
"Fabulous_Killjoy06": [("Summertime", "My Chemical Romance")],
"lilcommie0fficial": [("Summertime", "My Chemical Romance"),
  ("The World Is Ugly", "My Chemical Romance")],
"Jwagner6oh": [("Something", "The Beatles")],
"Remarkable_Gold_4030": [("True Companion", "Marc Cohn")],
"Ok-Zookeepergame3974": [("Gone with the Sin", "HIM")],
"debian_fanatic": [("Faithfully", "Journey"), ("In Your Eyes", "Peter Gabriel")],
"ImissmyBella": [("At Last", "Etta James"), ("Always and Forever", "Heatwave"),
  ("Moonlight Serenade", "Glenn Miller"), ("Me and Mrs. Jones", "Billy Paul"),
  ("Fooled Around and Fell in Love", "Elvin Bishop"),
  ("You Make Me Feel Brand New", "The Stylistics"),
  ("Too Much Heaven", "Bee Gees"), ("Wonderful Tonight", "Eric Clapton"),
  ("Can't Help Falling in Love", "Elvis Presley"),
  ("I Just Can't Help Believing", "Elvis Presley"),
  ("Let's Stay Together", "Al Green"),
  ("Can't Get Enough of Your Love, Babe", "Barry White"),
  ("The Way You Look Tonight", "Frank Sinatra"),
  ("I Will Always Love You", "Whitney Houston"),
  ("I'm Not Giving You Up", "Gloria Estefan"),
  ("This Guy's in Love with You", "Herb Alpert")],
"meepmorpfeepforp": [("Always and Forever", "Heatwave")],
"BostonDudeist": [("The Rain Song", "Led Zeppelin")],
"Spirited-Pressure434": [("What Is and What Should Never Be", "Led Zeppelin"),
  ("Over the Hills and Far Away", "Led Zeppelin")],
"Due_Variation7470": [("Born to Run", "Bruce Springsteen"),
  ("In My Life", "The Beatles"), ("Wouldn't It Be Nice", "The Beach Boys"),
  ("Can't Take My Eyes Off You", "Lauryn Hill")],
"cityshepherd": [("A Warm Place", "Nine Inch Nails")],
"agathalives": [("A Warm Place", "Nine Inch Nails")],
"Emergency-Jeweler-79": [("Sway", "Diana Krall")],
"hopelessheartstrings": [("I Belong to You", "Brandi Carlile")],
"No_Marzipan_3559": [("The Story", "Brandi Carlile")],
"dlm1129": [("This Guy's in Love with You", "Herb Alpert")],
"jazzkween1": [("This Guy's in Love with You", "Herb Alpert")],
"One_Olive_Short": [("This Guy's in Love with You", "Herb Alpert")],
"xMidnightWolfiex": [("I Would Do Anything for You", "Foster the People")],
"gaabryl": [("A Song for You", "Donny Hathaway")],
"ResearchPersonal5924": [("A Song for You", "Donny Hathaway")],
"upsidedownqbert": [("The Mayor of Simpleton", "XTC"),
  ("I Drove All Night", "Cyndi Lauper")],
"Striking-Ad-1573": [("Whenever You Come Around", "Vince Gill"),
  ("She", "Elvis Costello")],
"allmimsyburogrove": [("If", "Bread")],
"SquareTadpole1419": [("Without You", "Harry Nilsson")],
"sstepp3": [("(Everything I Do) I Do It for You", "Bryan Adams")],
"raceulfson": [("Just the Two of Us", "Bill Withers")],
"Current-Toe-6532": [("Just the Two of Us", "Bill Withers")],
"PeterGriffinTV4": [("Blue Sunday", "The Doors"), ("Indian Summer", "The Doors"),
  ("Thank You", "Led Zeppelin"), ("Harvest Moon", "Neil Young"),
  ("Suite: Judy Blue Eyes", "Crosby, Stills & Nash"),
  ("Helplessly Hoping", "Crosby, Stills & Nash")],
"Wild_Flower_31": [("Wichita Lineman", "Glen Campbell")],
"foxylady315": [("If", "Bread"), ("Make It with You", "Bread"),
  ("Annie's Song", "John Denver"), ("Longer", "Dan Fogelberg"),
  ("The Wedding Song (There Is Love)", "Peter, Paul and Mary"),
  ("Heaven", "Bryan Adams")],
"Harvey_Road": [("Harvest Moon", "Neil Young")],
"DopeCharma": [("The Very Thought of You", "Nat King Cole"),
  ("L-O-V-E", "Nat King Cole")],
"IndigoRose2022": [("Unforgettable", "Natalie Cole"),
  ("All Love Can Be", "Charlotte Church"), ("Giorno Dopo Giorno", "Kelly Sweet"),
  ("Un Giorno Per Noi", "Josh Groban"), ("La Vie en Rose", "Lady Gaga"),
  ("I've Never Been in Love Before", "Barbra Streisand"),
  ("Como Te Extraño Mi Amor", "Leo Dan"),
  ("I Will Follow You Into the Dark", "Violet Orlandi"),
  ("Ten Black Roses", "The Rasmus"), ("Illusion", "VNV Nation"),
  ("Bridge Over Troubled Water", "Simon & Garfunkel"), ("If", "Bread"),
  ("Somewhere in Time", "John Barry")],
"ItchClown": [("Crush", "Dave Matthews Band")],
"dirteebirdeeE": [("Crush", "Dave Matthews Band"),
  ("Lover, Please Stay", "Nothing But Thieves")],
"phantasm-blue": [("I Want You", "Third Eye Blind"), ("Starlight", "Muse"),
  ("All I Wanna Do", "The Beach Boys")],
"Illustrious-Lead-960": [("When the Night's on Fire", "Mike Oldfield")],
"hifidesert": [("Are You the One That I've Been Waiting For?", "Nick Cave"),
  ("You're the One", "Máire Brennan & Shane MacGowan"),
  ("Made Again", "Marillion"), ("Just Like Heaven", "The Cure"),
  ("Whatever's for Us", "Joan Armatrading")],
"Top_Street_2145": [("Being with You", "Smokey Robinson"),
  ("Kiss and Say Goodbye", "The Manhattans")],
"Queer_antichrist669": [("Do You Remember", "Jack Johnson")],
"Smartdate5": [("Glory of Love", "Peter Cetera")],
"Natural_Draw4673": [("Love You to Death", "Type O Negative"),
  ("Dead Girl", "Acid Bath")],
"cannibalsong1": [("Love You to Death", "Type O Negative"),
  ("Be My Druidess", "Type O Negative")],
"possy11": [("At My Most Beautiful", "R.E.M.")],
"TheRedARMYRose": [("Trivia: Love", "BTS")],
"MaleficentSettings": [("Postcards from Italy", "Beirut")],
"Professional-Cut-820": [("The Light", "Common"),
  ("Vintage Red", "Jay Jay Pistolet"), ("Stay with You", "John Legend"),
  ("This Universe", "UMI"), ("Annie's Song", "John Denver")],
"-Some__Random-": [("Lovesong", "The Cure")],
"JBelltolls4thee": [("Message to My Girl", "Split Enz")],
"GeneralDefenestrates": [("The Sacrament", "HIM")],
"refetitev": [("Just Like Heaven", "The Cure")],
"Fit-Faithlessness253": [("Mirrors", "Justin Timberlake")],
"001Guy001": [("Only You (And You Alone)", "The Platters")],
"i-aint_1_of_Yewww": [("Crystal", "Stevie Nicks")],
"Infamous_Contract_89": [("At Last", "Etta James"),
  ("Wonderful Tonight", "Eric Clapton")],
"Dizzy-Reality-8289": [("In My Life", "The Beatles")],
"Umaboiblu": [("Time to Say Goodbye", "Andrea Bocelli & Sarah Brightman")],
"useruser551": [("Somewhere Only We Know", "Keane")],
"pj67rocks": [("Annie's Song", "John Denver")],
"Advanced-Bird-1470": [("Romeo's Tune", "Steve Forbert"),
  ("Stoves on Fire", "Robert Lester Folsom"), ("Shanty", "Jonathan Edwards"),
  ("Our House", "Crosby, Stills, Nash & Young"),
  ("Then You Can Tell Me Goodbye", "Bettye Swann")],
"Lunaj35": [("Work Song", "Hozier"), ("Francesca", "Hozier"),
  ("In a Week", "Hozier")],
"Dear_Giraffe_453": [("The Twelfth of Never", "Johnny Mathis"),
  ("Wonderful! Wonderful!", "Johnny Mathis")],
"whoopsiedoozle": [("Silver Cloud", "Falconcastle")],
"Imaginary-Ostrich515": [("Fair", "The Amazing Devil"),
  ("Slow Dance Slow", "The Weather Machine")],
"Rissa_love9412": [("Choose You", "Elmiene")],
"junokatzen": [("The Predatory Wasp of the Palisades Is Out to Get Us!", "Sufjan Stevens")],
"Uhbominable": [("Mind Sex", "dead prez")],
"Im_not_an_expert_lol": [("Absence", "Rio Romeo"), ("Nothing's New", "Rio Romeo")],
"dacelikethefish": [("Everything in Between", "Leaf Rapids")],
"Ok-Amoeba-1190": [("Interstate Love Song", "Stone Temple Pilots")],
"Valleyguy70": [("Interstate Love Song", "Stone Temple Pilots")],
"DeadGodhead": [("Flames", "VAST")],
"davidsinnergeek": [("Love and Affection", "Joan Armatrading")],
"xfileluv": [("After All", "Al Jarreau"), ("Biggest Part of Me", "Ambrosia"),
  ("Pearls", "David Sanborn")],
"WILLCHOKEAHOE": [("Marry Me", "Meghan Trainor")],
"xMusicloverr": [("Better Together", "Jack Johnson"),
  ("Book of Love", "Peter Gabriel")],
"666throwawaytrash": [("Exist for Love", "AURORA")],
"PapayaCivil8228": [("Losing You", "Kane Brown"),
  ("I Love You Always Forever", "Donna Lewis & Digital Farm Animals"),
  ("Beautiful Crazy", "Luke Combs")],
"Hanuman_Jr": [("So Nice", "Bebel Gilberto")],
"ELFcubed": [("Handsome Man", "Matt Alber"),
  ("Big Heart of Yours", "David Wax Museum")],
"TradeIcy1669": [("Enjoy the Silence", "Depeche Mode"),
  ("In Your Eyes", "Peter Gabriel")],
"Successful-Coffee-17": [("Glue Song", "beabadoobee")],
"clxzsrz": [("I Will", "Mitski")],
"Da_Big_Cheese_75": [("Nobody Knows", "Lostboycrow")],
"MrsBiscuits16": [("Bless the Telephone", "Labi Siffre")],
"Bunny_Flores": [("Me Estoy Enamorando", "La Mafia"),
  ("You've Made Me So Very Happy", "Blood, Sweat & Tears"),
  ("Love Theme from St. Elmo's Fire", "David Foster")],
"Sqisha": [("If We Were Vampires", "Jason Isbell and the 400 Unit")],
"butanejane": [("If We Were Vampires", "Jason Isbell and the 400 Unit")],
"Atillion": [("With a Thousand Words to Say But One", "Darkest Hour")],
"laststopincairo": [("You and I", "Lady Gaga")],
"Careful_Compote_4659": [("Giving You the Best That I Got", "Anita Baker")],
"Bloverfish": [("Longer", "Dan Fogelberg"), ("All Out of Love", "Air Supply"),
  ("Glory of Love", "Peter Cetera")],
"Adventurous_Path4356": [("Until...", "Sting")],
"camazotzthedeathbat": [("First Day of My Life", "Bright Eyes"),
  ("I Will Follow You Into the Dark", "Death Cab for Cutie")],
"always-knows-best": [("When You're Here", "John Fullbright")],
"MoonBarbarian": [("Tus Ojos", "Héctor Lavoe"),
  ("Every Minute", "Stephen Bishop")],
"OneManWentToMow": [("Mirrorball", "Elbow")],
"ForgottenGenX47": [("Mirrorball", "Elbow")],
"Primary_Somewhere_98": [("The Look of Love", "Gladys Knight")],
"Neither-Connection72": [("#1 Crush", "Garbage")],
"Significant-Dot4111": [("Lover", "Taylor Swift")],
"musicwithbarb": [("In the Real Early Morning", "Jacob Collier")],
"zotzenthusiast": [("St. Cecelia's", "Animal Flag"),
  ("I'll Take Care of You", "The Chicks"),
  ("Landing Feet First", "Bayside"), ("Call It Dreaming", "Iron & Wine")],
"thinkilldrinkthesea": [("Tightrope", "The Stone Roses")],
"Odd-Bee9172": [("Truly", "Lionel Richie")],
"espressocycle": [("My Favorite Picture of You", "Guy Clark")],
"Tranquilbez22": [("Don't Delete the Kisses", "Wolf Alice"),
  ("Glue Song", "beabadoobee")],
"VeeVeePA": [("You're My World", "Cilla Black")],
"thedreamingmoon12": [("Simply Beautiful", "Al Green")],
"Malachorn": [("Your Rocky Spine", "Great Lake Swimmers")],
"dvoigt412": [("Satellite of Love", "Lou Reed")],
"thefoxnotorious": [("Jersey Girl (live)", "Bruce Springsteen")],
"Lonely_plain_jane": [("The First Time Ever I Saw Your Face", "Roberta Flack")],
"KatesDad2019": [("The First Time Ever I Saw Your Face", "Roberta Flack")],
"missannthrope1": [("The First Time Ever I Saw Your Face", "Roberta Flack")],
"yuki_yuzura_chan": [("Sink Into the Floor", "Feng Suave")],
"WhimsicalChuckler": [("All of Me", "John Legend")],
"Actual_Law_505": [("All of Me", "John Legend")],
"April_Karate": [("This Year's Love", "David Gray"), ("Only Love", "Ben Howard")],
"ExternalDegree8868": [("Welcome to Earth (Pollywog)", "Sturgill Simpson")],
"OliveGreen87": [("Blue Eyes", "Cary Brothers")],
"volerei": [("Hunting High and Low", "a-ha")],
"Mellanderthist": [("Unomi", "Walken")],
"rachcarp": [("Thank You", "Bonnie Raitt")],
"Final_Salamander_826": [("Nights in White Satin", "The Moody Blues")],
"M8NSMAN": [("Then", "Brad Paisley")],
"NovelAttempt1958": [("Stir It Up", "Bob Marley")],
"Unlikely-Section-600": [("The Rime of the Ancient Mariner", "Iron Maiden")],
"LimpTransition8769": [("Suavecito", "Malo")],
"SchemataObscura": [("Still Remains", "Stone Temple Pilots"),
  ("Every Other Freckle", "alt-J")],
"Low-Bird-5379": [("Gorecki", "Lamb"), ("Lovers", "Kathleen Battle")],
"cha-do": [("The Luckiest", "Ben Folds")],
"Des_mojo": [("This Love", "Pantera")],
"PrizeCelery4849": [("Our House", "Crosby, Stills, Nash & Young")],
"wire_we_here50": [("Fools Rush In", "Elvis Presley"),
  ("Can't Help Falling in Love", "Elvis Presley"),
  ("Fade Into You", "Mazzy Star"), ("Lovesong", "The Cure")],
"ethereal_twin": [("You and Me", "Penny & the Quarters")],
"ScotterMcJohnsonator": [("Steve M Grocery", "Wormy")],
"jas4870": [("Say You Won't Let Go", "James Arthur")],
"Lost-Astronaut-8280": [("If You Can't Ride Two Horses at Once, You Should Get Out of the Circus", "Asking Alexandria")],
"Ok_Consideration8357": [("Falling in Love (theme)", "Dave Grusin")],
"lightranger": [("In Your Eyes", "Peter Gabriel")],
"Svn8time": [("In Your Eyes", "Peter Gabriel")],
"StrawberryMoonPie": [("A Thousand Kisses Deep", "Leonard Cohen")],
"amarantaaa": [("The Ship Song", "Nick Cave & the Bad Seeds")],
"Jelsol": [("You're to Blame", "Elizabeth McQueen")],
"sewest": [("Dark Side of the Gym", "The National")],
"Realistic_Stretch316": [("Beautiful", "Gordon Lightfoot")],
"unprogrammable_soda": [("Your Song", "Elton John")],
"murderskunk76": [("Our Love Is Easy", "Melody Gardot"),
  ("Dance Me to the End of Love", "Madeleine Peyroux")],
"maddenplayer2921": [("Forever After All", "Luke Combs"),
  ("Tuesdays", "Jake Scott"), ("Baby I'm Yours", "Arctic Monkeys")],
"DiscardUserAccount": [("Blue Bossa", "Kenny Dorham")],
"Fresh_off_my_meds": [("The Power of Love", "Frankie Goes to Hollywood")],
"chungledbungus": [("Deathmask Divine", "The Black Dahlia Murder")],
"Josh017": [("Starlight", "Muse")],
"Initial-Ad2243": [("Yours", "Conan Gray"), ("Until I Have You", "Lil' Pitchy"),
  ("Love You Till Tuesday", "David Bowie")],
"Ok_Werewolf_3915": [("Community Property", "Steel Panther")],
"Roseann555": [("Last Dance", "The Cure")],
"imadork1970": [("Wonderful Tonight", "Eric Clapton")],
"Grand_Opinion845": [("Pulse", "Ani DiFranco")],
"Homeschool_PromQueen": [("Eres Mi Religión", "Maná")],
"blanchattacks": [("The Night We Met", "Lord Huron")],
"Waynebgmeamc": [("Shameless", "Billy Joel")],
"unclesalazar": [("Wondering Why", "The Red Clay Strays"),
  ("Love's the Only Way", "Cage the Elephant"),
  ("Portuguese Knife Fight", "Cage the Elephant"),
  ("That's Right", "Cage the Elephant")],
"Ds0589": [("Valentine's Day", "Bruce Springsteen")],
"Delicious_Internal36": [("Crawling Back to You", "Tom Petty")],
"Careless-Art-730": [("Something", "Taylor Swift")],
"Fun-Distribution-159": [("Paradise", "Smash Into Pieces")],
"Joanr719": [("A Song for You", "Leon Russell")],
"StrikingNinja5979": [("Southern Drawl", "Bahamas")],
"enchantedmermaid22": [("Until the End of Time", "Justin Timberlake")],
"MissHibernia": [("Miracles", "Jefferson Starship")],
"kayleesanchez202": [("Yellow", "Coldplay")],
"Boatokamis": [("Falling Slowly", "Glen Hansard & Markéta Irglová"),
  ("The Promise", "When in Rome")],
"IntelligentEase7269": [("Cosmos", "Beck")],
"welxometohell": [("High School Sweethearts", "Melanie Martinez")],
"Bthecampione": [("Runaway", "Kanye West")],
"RIDEMYBONE": [("Evangeline", "Stephen Sanchez")],
"envirogirl78": [("You Make Loving Fun", "Fleetwood Mac"),
  ("Feathered Indians", "Tyler Childers"),
  ("I Wish I Was", "The Avett Brothers")],
"DownToEarth2414": [("All My Life", "K-Ci & JoJo"),
  ("The Power of Love", "Celine Dion")],
"Intelligent-Let5013": [("Stars", "My Favourite Book"),
  ("Holding On With Both Hands", "Giraffe"),
  ("Your Arms Around Me", "Jens Lekman"), ("Slow Show", "The National"),
  ("You Got It", "Roy Orbison"),
  ("I Love How You Love Me", "The Paris Sisters"),
  ("I'm Your Man", "Leonard Cohen"),
  ("Book of Love", "The Magnetic Fields"),
  ("Falling Slowly", "Glen Hansard & Markéta Irglová"),
  ("Mysteries of Love", "Julee Cruise"),
  ("Lover, You Should've Come Over", "Jeff Buckley"),
  ("Fade Into You", "Mazzy Star")],
"Roaddog0505": [("All Again", "Charles Wesley Godwin"),
  ("Wondering Why", "The Red Clay Strays"), ("Lady May", "Tyler Childers")],
"fergiishiz": [("Born to Run", "Bruce Springsteen")],
"Moist-Doughnut-5160": [("Man on Fire", "Andy Gibb"),
  ("Stormy", "Atlanta Rhythm Section"),
  ("So Into You", "Atlanta Rhythm Section"),
  ("Emotion in Motion", "Ric Ocasek"),
  ("I Still Miss Someone", "Stevie Nicks")],
"augustiswandering": [("Love Song", "Lana Del Rey")],
"Turbulent_Oil_2384": [("A King and a Queen", "Okkervil River"),
  ("Thunder Clatter", "Wild Cub"), ("Kathy with a K's Song", "Bright Eyes")],
"Old_Cyrus": [("Cold Ethyl", "Alice Cooper")],
"ScottyToo9985": [("Collide", "Howie Day")],
"DeltaMx11": [("One Last Dance", "Us the Duo")],
"guess_who_1984": [("Always and Forever", "Heatwave")],
"TotalTerrible783": [("Ebb Tide", "The Righteous Brothers")],
"RavenousBear91": [("Impossible", "Nothing But Thieves")],
"Western_Research_696": [("Annie's Song", "John Denver")],
"midclassfancy": [("Until the Last Falling Star", "Matthew Perryman Jones"),
  ("A Thousand Years", "Christina Perri"), ("Everything", "Michael Bublé"),
  ("Eternal Flame", "The Bangles"), ("I'll Stand by You", "The Pretenders"),
  ("Have I Told You Lately", "Rod Stewart")],
"astern126349": [("Pictures of You", "The Cure")],
"Cheetah_Friendly": [("Cover Me Up", "Morgan Wallen")],
"Prickly-Prostate": [("Cock in My Pocket", "The Stooges")],
"Moist-Share7674": [("Dick in a Box", "The Lonely Island")],
"VernonDent": [("She Fucks Me", "Ween")],
"horsebag": [("100 Ways", "Porno for Pyros")],
"Desperate_Thing4581": [("Mein Teil", "Rammstein")],
}

counts = defaultdict(set)
for user, songs in B.items():
    for song, artist in songs:
        counts[(song, artist)].add(user)

rows = sorted(
    ({"song": s, "artist": a, "mentions": len(u)} for (s, a), u in counts.items()),
    key=lambda r: (-r["mentions"], r["song"].lower()))

json.dump({"thread": THREAD, "rows": rows}, open("romantic.json", "w"),
          ensure_ascii=False, separators=(",", ":"))

# The Spotify importer wants Year,Artist,Track,Album — it only reads two of them.
with open("romantic-songs.csv", "w", newline="") as fh:
    w = csv.writer(fh)
    w.writerow(["Year", "Artist", "Track", "Album"])
    for r in rows:
        w.writerow(["", r["artist"], r["song"], ""])

once = sum(1 for r in rows if r["mentions"] == 1)
print(len(rows), "songs from", len(B), "redditors;",
      sum(r["mentions"] for r in rows), "mentions;", once, "named once")
for r in rows[:15]:
    print(f'  {r["mentions"]}x  {r["song"]} — {r["artist"]}')
