"""r/AskReddit — "What's the most beautiful song you've ever heard?" (2023)
Counted by distinct redditor. Building both a Listomania list and a Spotify CSV.
"""
import csv, json

THREAD = {
 "q":"What's the most beautiful song you've ever heard?",
 "site":"Reddit · r/AskReddit","year":2023,"meta":"5.3K points · 11K comments",
 "url":"https://www.reddit.com/r/AskReddit/comments/170gtc6/whats_the_most_beautiful_song_youve_ever_heard/",
}

# track, artist, mentions
D = [
 ("Annie's Song","John Denver",5),
 ("Vincent","Don McLean",4),
 ("Gymnopédie No. 1","Erik Satie",4),
 ("Over the Rainbow / What a Wonderful World","Israel Kamakawiwo'ole",4),
 ("Adagio for Strings","Samuel Barber",3),
 ("A Case of You","Joni Mitchell",3),
 ("Goodbye Yellow Brick Road","Elton John",3),
 ("Moonlight Sonata","Ludwig van Beethoven",2),
 ("Clair de Lune","Claude Debussy",2),
 ("On the Nature of Daylight","Max Richter",2),
 ("Ave Maria","Franz Schubert",2),
 ("Nights in White Satin","The Moody Blues",2),
 ("In Paradisum","Gabriel Fauré",2),
 ("The First Time Ever I Saw Your Face","Roberta Flack",2),
 ("What a Wonderful World","Louis Armstrong",2),
 ("Outro","M83",2),
 ("Fade Into You","Mazzy Star",2),
 ("No Time for Caution","Hans Zimmer",2),
 ("Cherish the Day","Sade",2),
 ("Scarborough Fair / Canticle","Simon & Garfunkel",2),
 ("Something","The Beatles",2),
 ("The Boxer","Simon & Garfunkel",1),
 ("Hide and Seek","Imogen Heap",1),
 ("Fields of Gold","Sting",1),
 ("Agnus Dei","Samuel Barber",1),
 ("Bridge Over Troubled Water","Simon & Garfunkel",1),
 ("Sweet Disposition","The Temper Trap",1),
 ("Calypso","John Denver",1),
 ("The Eagle and the Hawk","John Denver",1),
 ("You Are Not Alone","Michael Jackson",1),
 ("Killing Me Softly With His Song","Roberta Flack",1),
 ("Wicked Game","Chris Isaak",1),
 ("Moon River","Henry Mancini",1),
 ("Keep Me in Your Heart","Warren Zevon",1),
 ("Everlong","Foo Fighters",1),
 ("Dream a Little Dream of Me","Cass Elliot",1),
 ("Vienna","Billy Joel",1),
 ("Flower Duet","Léo Delibes",1),
 ("Songbird","Fleetwood Mac",1),
 ("Ode to Joy","Ludwig van Beethoven",1),
 ("Don't Give Up","Peter Gabriel",1),
 ("Just the Two of Us","Grover Washington Jr.",1),
 ("The Blower's Daughter","Damien Rice",1),
 ("9 Crimes","Damien Rice",1),
 ("Untitled","Interpol",1),
 ("The Funeral","Band of Horses",1),
 ("Last Dance","The Cure",1),
 ("Just Like Heaven","The Cure",1),
 ("Love Will Tear Us Apart","Joy Division",1),
 ("Ghosts","Muse",1),
 ("Smalltown Boy","Bronski Beat",1),
 ("With or Without You","U2",1),
 ("There Is a Light That Never Goes Out","The Smiths",1),
 ("More Than This","Roxy Music",1),
 ("Only Time","Enya",1),
 ("Time After Time","Cyndi Lauper",1),
 ("Nothing Else Matters","Metallica",1),
 ("Fade to Black","Metallica",1),
 ("Hallelujah","Jeff Buckley",1),
 ("Wildflowers","Tom Petty",1),
 ("Time","Hans Zimmer",1),
 ("Echoes","Pink Floyd",1),
 ("High Hopes","Pink Floyd",1),
 ("Space Song","Beach House",1),
 ("Unchained Melody","Elvis Presley",1),
 ("Loving Her Was Easier","Kris Kristofferson",1),
 ("I'd Rather Go Blind","Etta James",1),
 ("Reckoner","Radiohead",1),
 ("Grace","Jeff Buckley",1),
 ("Into My Arms","Nick Cave & The Bad Seeds",1),
 ("O Holy Night","Adolphe Adam",1),
 ("Cadillac of the Skies","John Williams",1),
 ("New World","Björk",1),
 ("Apotheosis","Austin Wintory",1),
 ("To Zanarkand","Nobuo Uematsu",1),
 ("What Sarah Said","Death Cab for Cutie",1),
 ("Transatlanticism","Death Cab for Cutie",1),
 ("St. Peter's Cathedral","Death Cab for Cutie",1),
 ("Half a World Away","R.E.M.",1),
 ("Sweetness Follows","R.E.M.",1),
 ("True Love Waits","Radiohead",1),
 ("4 Minute Warning","Radiohead",1),
 ("How to Disappear Completely","Radiohead",1),
 ("Hey Jupiter","Tori Amos",1),
 ("Goodbye to a World","Porter Robinson",1),
 ("Landslide","Fleetwood Mac",1),
 ("Nothing Compares 2 U","Sinéad O'Connor",1),
 ("Can't Help Falling in Love","Elvis Presley",1),
 ("Iris","Goo Goo Dolls",1),
 ("Lights","Interpol",1),
 ("All I Need","Radiohead",1),
 ("The Scientist","Coldplay",1),
]

rows = sorted(({"title":t,"author":a,"mentions":m} for t,a,m in D),
              key=lambda r:(-r["mentions"], r["title"].lower()))
json.dump({"thread":THREAD,"rows":rows}, open("songs.json","w"),
          ensure_ascii=False, separators=(",",":"))

with open("beautiful-songs.csv","w",newline="",encoding="utf-8") as f:
    w=csv.writer(f, quoting=csv.QUOTE_ALL)
    w.writerow(["Year","Artist","Track","Album"])
    for r in rows:
        w.writerow(["", r["author"], r["title"], ""])

print(len(rows),"songs;",sum(r["mentions"] for r in rows),"mentions")
