"""Best MTV Unplugged in music history — r/musicsuggestions, 1wph6v8.

Counted by distinct redditor who *names* an Unplugged set as a pick, top-level
or in a reply, with every set they put forward counted once. Same rule as
museums.py and cities.py: "Agreed", "Mine too", "Only answer" without a name
add nothing, and a set named only to knock it is not a vote. Naming a song
from the set ("unplugged Black destroys me", "Human Behaviour on
harpsichord") counts as naming the set. The asker's own pick in the post body
(Alice in Chains) counts: it is an answer, not the question.

Dropped: things that are not MTV Unplugged — Tesla's Five Man Acoustical Jam,
the Eagles' Hell Freezes Over, Don Henley's Storytellers — and artists who
never did one (Soundgarden wishes, Johnny Cash, Prince, the Rolling Stones,
Queens of the Stone Age, Death Grips, Utah Saints, Olga Guillot, the Goo Goo
Dolls). Also dropped: jokes, and a pasted AI-generated list of every episode.

Uptown MTV Unplugged (1993) is filed under Jodeci: that is who all three
people who named it meant (K-Ci & JoJo's "Lately").

Data was transcribed by hand from the thread's old.reddit .json, attached.
The capture holds 494 of 694 comments; ~200 sat behind "load more".
"""
import json

URL = "https://www.reddit.com/r/musicsuggestions/comments/1wph6v8/who_has_the_best_mtv_unplugged_in_music_history/"

# code -> (display name, year of the Unplugged set; "" where unsure)
A = {
"NIR":("Nirvana","1993"), "AIC":("Alice in Chains","1996"), "PJ":("Pearl Jam","1992"),
"TTM":("10,000 Maniacs","1993"), "BJO":("Björk","1994"), "CURE":("The Cure","1991"),
"NY":("Neil Young","1993"), "SRV":("Stevie Ray Vaughan","1990"), "REM":("R.E.M.","1991"),
"SQZ":("Squeeze","1989"), "DD":("Duran Duran","1993"), "GM":("George Michael","1996"),
"EC":("Eric Clapton","1992"), "LL":("LL Cool J","1991"), "MC":("Mariah Carey","1992"),
"PM":("Paul McCartney","1991"), "QR":("Queensrÿche","1992"), "STP":("Stone Temple Pilots","1993"),
"BD":("Bob Dylan","1994"), "KORN":("Korn","2006"), "TB":("Tony Bennett","1994"),
"AM":("Alanis Morissette","1999"), "JOD":("Jodeci (Uptown Unplugged)","1993"),
"PLA":("Placebo","2015"), "LH":("Lauryn Hill","2001"), "AHA":("a-ha","2017"),
"MO":("Midnight Oil",""), "SEAL":("Seal",""), "YO":("Yo! MTV Raps Unplugged","1991"),
"JEW":("Jewel",""), "CRAN":("The Cranberries","1994"), "SODA":("Soda Stereo","1996"),
"SA":("Soul Asylum","1993"), "JAYZ":("Jay-Z","2001"), "ROD":("Rod Stewart","1993"),
"FA":("Fiona Apple","1997"), "DT":("Diego Torres","2004"), "AK":("Alicia Keys","2005"),
"BC":("The Black Crowes",""), "GW":("Great White",""), "LIVE":("Live",""),
"SC":("Sheryl Crow",""), "OAS":("Oasis","1996"), "HOLE":("Hole","1995"),
"PP":("Page & Plant","1994"), "BS":("Bruce Springsteen","1992"), "AERO":("Aerosmith","1990"),
"SHAK":("Shakira","1999"), "STING":("Sting","1991"), "ZOE":("Zoé","2011"),
"JM":("John Mellencamp",""), "CB":("Courtney Barnett","2019"), "KISS":("KISS","1995"),
"DC":("Dashboard Confessional","2002"), "AD":("Arrested Development","1993"),
"DL":("Denis Leary",""), "RATT":("Ratt",""), "F4":("Die Fantastischen Vier","2000"),
"PARA":("Paramore",""), "CH":("Crowded House",""), "GG":("Gilberto Gil","1994"),
"SS":("Santa Sabina",""), "MANA":("Maná","1999"), "BIFFY":("Biffy Clyro","2018"),
"EJ":("Elton John",""), "MD":("Mando Diao","2010"), "KP":("Katy Perry","2009"),
}

# redditor -> sets they put forward
V = {
"deloncigarette":["AIC"],
"Suspicious_Pie_9912":["AIC","NIR"],
"rukittenmeeee":["AIC"],
"Segundaleydenewtonnn":["DT"],
"MysteryMeatballer":["AIC"],
"PoopOnRye":["PJ"],
"northern_greyhound":["BJO"],
"AaronAAaronsonIII":["BJO"],
"fooosco":["BJO"],
"lyndachinchinella":["AIC","TTM","JOD"],
"No_Lemon_3116":["AIC"],
"snafu2u":["NIR"],
"IDigRollinRockBeer":["NIR"],
"SuddenInteract8":["AIC","NIR"],
"Jk8fan":["NIR"],
"Red-Zaku-":["NIR"],
"Princibalities":["PJ"],
"Plenty_Past2333":["PJ"],
"Wobby1987":["PJ"],
"superthrust123":["NIR","STP"],
"howdiditgetinthere":["NIR"],
"millionthcustomer":["TTM"],
"Vernichtungsschmerz":["TTM","PJ"],
"miriodeservedofa":["TTM"],
"bobotheboinger":["TTM"],
"laugh_riott":["FA"],
"ifrankenstein":["PJ"],
"Beautiful-Program428":["PJ","AIC","STP","CURE","KORN","BJO","SC"],
"lobaybliss":["CURE"],
"lucifrier":["CURE","NIR"],
"tonyk11":["NY"],
"sasquatchlovesbagels":["NY","JM","QR"],
"aquariumdrunkard":["NY","PM"],
"Low_Bandicoot_3527":["NY","NIR"],
"southboundtracks":["SRV"],
"No-Wealth-5942":["REM"],
"Wutcherhurry":["REM"],
"ggmcgg11":["SQZ"],
"indil47":["DD"],
"iamsolow1":["AIC"],
"buster16521":["GM"],
"ConsistentNetwork724":["NIR","EC"],
"Trick-Masterpiece318":["EC"],
"Practical-Being-1185":["JAYZ","ROD"],
"uarstar":["EC"],
"ktslgr":["EC"],
"Unknownkowalski":["LL"],
"kindnessoffensive":["MC"],
"BumblebeeThen7954":["NIR"],
"cappykro":["NIR","PJ"],
"NerdAlert03":["PM"],
"Ghost_of_a_Pale_Girl":["QR","NIR","STP","AIC","PJ"],
"Eric_the_Shit_Cock":["QR","AIC"],
"Kvothetheraven603":["PJ"],
"EmerysMemories1106":["PJ"],
"Financial_Luck_6906":["PJ","TTM"],
"hit_n_run15":["NIR"],
"Alternative_Life9414":["NIR"],
"jackstraw_65":["BD"],
"Sally_Klein":["BD"],
"simonpunishment":["BD"],
"SpiderFromNeptune":["KORN","PJ"],
"TheMasterCommando":["KORN"],
"theguywiththefacce":["KORN"],
"juni4ling":["TTM"],
"eeejit075":["TB"],
"Jobriath":["TB","NIR"],
"munkian69":["NIR"],
"No_Teaching5581":["GM"],
"Dull_Policy_1617":["GM"],
"Jmazoso":["GM","QR","AIC","AHA"],
"BlueberryMuffin_77":["AM"],
"Winter_Map_42":["STP"],
"PlentyBoot5135":["SRV"],
"eerozwad":["NIR","JOD"],
"Mindless-Damage-5399":["PLA"],
"blkbear420":["LH"],
"Reasonable_Jicama130":["NIR"],
"LIslander":["AHA"],
"Carsully5768":["MO"],
"Strengththruwounding":["NIR","AIC"],
"Phantom_2020":["NIR","AIC","SEAL","YO","NY"],
"Halycon85":["YO"],
"TDiddy2021":["NIR","CURE"],
"Capt_J_Yossarian22":["JEW"],
"b1leper":["TTM"],
"magnoliaAveGooner":["AIC"],
"StariKrchmar":["AIC"],
"Academic_Airport_889":["CRAN"],
"TGVROLL":["EC"],
"Liquid-Hot_Smegma":["EC"],
"scrimmerman":["SRV","STP"],
"Valiant204":["NIR","AIC"],
"speaklouder1100":["SODA"],
"o-krub":["SA"],
"GoodEnoughByMudhoney":["SA"],
"TheSmalesKid":["NIR","AIC","TTM"],
"EmoogOdin":["BJO"],
"MiamiViceGuy":["NIR"],
"Penny_Royal_Tee":["NIR"],
"ParticularShirt5176":["AIC"],
"E-Stoye":["EC"],
"Historical_Ad_3356":["AIC"],
"donut_koharski":["AIC"],
"spacewrangler69":["AIC","SRV"],
"teneno":["NIR"],
"ark19790":["NIR"],
"AdOriginal1839":["NIR","AIC"],
"JPIZZLE1205":["NIR"],
"AgencyCool463":["NIR"],
"TheSevereJacket":["NIR","AIC","PJ"],
"late2thepauly":["NIR","AIC"],
"farfromeverywhere":["SRV"],
"KetiTheRedPanda":["NIR","AM","JAYZ"],
"Candid-Sky-3258":["GM"],
"Odd_Clothes1439":["AIC","REM"],
"Gizmo_caca":["PJ","NIR"],
"Euphoric_Wafer_5197":["PJ"],
"Infinite_Tension_138":["NIR"],
"Embarrassed-End-7532":["NIR"],
"neurotrash2099":["AK"],
"forever_29_ish":["DD","AM","AHA"],
"CheersToCosmopolitan":["BC","NIR","LL"],
"plinn777":["BC","GW"],
"OwlVsCrow2001":["MO"],
"Gooncookies":["NIR"],
"PotentialSure9957":["SODA"],
"timmorris82":["AIC","LIVE"],
"Capable_Butterfly_61":["SC"],
"Aneilanated":["AIC","NIR","TTM"],
"UncleSquiffy":["NIR"],
"PDXCatHerder":["AHA"],
"Paynekiller997":["OAS"],
"Intelligent-Math1821":["OAS"],
"MissionFig5582":["NIR"],
"tegeus-Cromis_2000":["YO","BD"],
"CoA77":["LIVE","HOLE","NIR"],
"mister_somewhere":["LIVE"],
"Reddityyz":["EC"],
"Fearless_Street5231":["QR"],
"RussellAlden":["NY"],
"RamblingRosie":["NIR"],
"mikedeelia":["NY"],
"BuffaloDivineEdenNo7":["NY","EC"],
"GME_Elitist":["NIR","AIC"],
"snagle-tooth":["TTM"],
"dyvargas":["AIC"],
"Shaded-Haze":["ZOE"],
"findingthebeat77":["ZOE","SHAK"],
"PataMadre":["JAYZ"],
"Inner-Sherbet-8689":["BD"],
"raletti":["CURE","REM"],
"VornadoLaCroix":["LH"],
"brianinla":["REM"],
"Zakb13":["OAS","AIC","NIR","CURE"],
"Reasonable-Pop-103":["BD"],
"Illustrious-You-1735":["NIR"],
"mrbaggy":["LL"],
"Jasper_Jaxx":["NIR"],
"Forsaken-Mix-4536":["MC"],
"bmccooley":["STING"],
"Original-Release-885":["MC"],
"Public-Ice-1270":["CURE"],
"Immediate_Formal_252":["AIC","NIR","PJ"],
"Historical_Fly_8501":["LH"],
"halfstep44":["PJ"],
"CleansingFlame":["NIR","MC"],
"MyxomatosisDRabbit":["NIR"],
"zarathos1975":["STP","TTM"],
"immabankr":["NIR"],
"slipperypete1990":["PJ"],
"Otherwise-Badger":["NIR"],
"Feeling-Art-6514":["BD"],
"iaminabox":["NIR"],
"jf737":["AIC"],
"Samnppa":["NIR","AIC"],
"Educational-Life9936":["AIC"],
"Punkupine":["NIR","CB"],
"ThatsAuJerryAu":["PJ"],
"Krankypantz":["NIR"],
"Salty-Possible-8753":["NIR"],
"No-Ebb7197":["NIR"],
"mrblacklabel71":["NIR"],
"SuperdudeKev":["PJ","SRV","QR"],
"GoetiaMagick":["NIR"],
"BINGGBONGGBINGGBONGG":["NIR"],
"AstroCrackle":["AIC"],
"markeyDAvorne":["AIC"],
"Outrageous-Arm1945":["JAYZ","NIR"],
"danosmanca":["AIC"],
"ramonescreatin":["PM"],
"IllustriousLight2344":["AIC"],
"Negative-Spell6275":["PM"],
"Playful_Title_6235":["AIC"],
"Professional_Scar340":["STP"],
"MisterEvilBreakfast":["REM"],
"nzoasisfan":["OAS"],
"LedZepSOS":["PP"],
"zoso1992":["PP"],
"mrwinky531":["SODA"],
"wahdatah":["NIR"],
"Professional-Bag2360":["AIC","NIR"],
"soolsul":["LIVE","TTM"],
"Many-Song7032":["SRV"],
"Rage4Order418":["QR"],
"Much-Car-9799":["SODA"],
"ceazarnie":["NIR"],
"fatrexhadswag25":["BS","PM"],
"Dapper-Fan-3836":["EC"],
"SamuelBilibid":["TTM"],
"Sycotic199":["NIR"],
"Snibbitz":["AIC"],
"Interesting-Ebb6378":["MC"],
"attaboy_stampy":["NIR","AERO"],
"FriendlyGiant1551":["AIC","NIR","OAS"],
"redwop131374":["NIR","PJ","AIC"],
"indyjays":["EC"],
"pappy925":["EC"],
"wmyork":["EC"],
"MaxBulla":["PP"],
"val890":["SS"],
"Mysterious-Rough1356":["AIC"],
"Puffpufftoke":["BIFFY"],
"ignaciolasvegas":["PP"],
"Regalzack":["EJ"],
"Fresh_Ad4765":["MANA"],
"favonian_":["SHAK"],
"Academic-Ad-9637":["KORN"],
"xX_dumb_god_Xx":["MC"],
"TopLahman":["NIR","AIC","MC"],
"KeyWestistheplacetob":["BD"],
"Looking4mula":["PJ","MD"],
"Allieratt":["QR"],
"Wishinifishin":["AIC","SRV"],
"laserjock314":["AIC"],
"WeaponsGrade520":["QR"],
"MentalMap-411":["KORN"],
"joelwosk":["NIR","AIC"],
"Sea_Green7967":["QR"],
"nachos4two":["NIR","KP"],
"Brizzy44206":["CB","AIC"],
"Heavy-Flow8171":["BD"],
"SirRelevant1346":["EC","NIR","LL","REM","TTM"],
"biff444444":["NIR"],
"Crazy-Field-4023":["AIC","NIR","CRAN"],
"Joe-Dang":["DC"],
"KevinH112":["NIR","AIC","KORN"],
"c1ncinasty":["STP"],
"Whisky-a-GoGo1":["PP","NIR","PJ","HOLE"],
"anonymous-axolotyl":["NIR","JAYZ"],
"Express-Shoulder6174":["NIR"],
"Remote-Platform-5138":["PP"],
"arukah_1212":["DC"],
"Salty-Ad-4693":["AIC","NIR","STP"],
"Uhazz1977":["AIC"],
"Pleasant-Carbon":["SHAK"],
"gorillagrlz":["NIR"],
"mommydumdumland":["NIR","AIC","NY"],
"ardshipman":["KISS","QR"],
"Street_Giraffe5772":["NIR"],
"dereks1234":["EC"],
"dtvoices94":["KISS"],
"Lexi-Louise":["SHAK"],
"Automatic-Turnip8144":["PJ"],
"Neat-Relation-Bus":["AIC","NIR"],
"RumorsOFsurF":["NIR"],
"Own_Recognition_5834":["AIC","NIR"],
"SenseIntelligent8846":["TTM","CURE"],
"Actual-Cold-4281":["DC"],
"PeterPook":["EC","NIR"],
"mjc7373":["BD"],
"silent_dialogue":["AIC","NIR","SRV"],
"Different-Let-9801":["AIC","NIR"],
"Electrical-Cow-817":["PJ"],
"gbaguinon":["SHAK"],
"Former-Ad-7658":["AIC"],
"_Baylock_":["PJ","STP","BJO","AD","KORN","EC"],
"Bannanapeelsmoker":["DL"],
"darbydog69":["PJ"],
"ChaosAndFish":["CURE","LL"],
"Dry-Examination-2012":["NIR"],
"ForsakenLanguage5672":["RATT"],
"wunderwutzl":["F4"],
"SpyroVeee":["AIC","NIR"],
"JelloDK":["NIR"],
"batcat44":["NIR","PARA"],
"Confused4Now76":["REM"],
"FavoriteJackson":["ROD"],
"bobbichocolatthe2nd":["SRV"],
"hookem1543":["AIC"],
"FedHillGal76":["JAYZ","JOD"],
"Mcstin":["EC"],
"dennis1953":["NIR","KISS","ROD"],
"Blaketherattlesnake":["NIR"],
"LouReedsBrain":["KISS"],
"Separatecontent7026":["NIR","AM"],
"OldFashioned62":["ROD"],
"nancypants30":["NIR"],
"JackBBSS":["NIR"],
"Ok_Flatworm8811":["NIR","AIC"],
"Jewggerz":["AIC"],
"Cold_Ad7516":["SRV","EC"],
"rockaway428":["AIC","PJ"],
"glueckszilz":["AIC"],
"Grand_Amount_8351":["AIC"],
"AutoPRND21":["SRV","LL"],
"Dont_Treat_Me_Bad":["EC","NIR"],
"pelofr":["MD"],
"Saber_tooth81":["NIR","AIC"],
"PurpleToedUnicorn":["AIC","TTM"],
"AgnesTachyon00":["AIC"],
"stussie73":["STP"],
"WearyResort3961":["NIR","AIC"],
"mcaress":["NIR"],
"Certain_Stranger2939":["STP"],
"Tewayel":["KISS"],
"SeaOk7514":["TB"],
"TheBlackDeathXXX":["NIR"],
"sexyjohncandy":["LL"],
"PrincessConsuela46":["AIC"],
"Born-Philosopher-181":["NIR"],
"Funkles_tiltskin":["NIR","AK","LH"],
"UptownLounge":["CH"],
"Cruella666_theOG":["SA"],
"heathercs34":["AIC"],
"Money_Rub7108":["KISS"],
"SnooMacaroons4212":["CRAN"],
"Wonderful-Hornet2991":["EC"],
"elvisfan777":["REM"],
"eatingsquishies":["CURE"],
"Civil-Gap5615":["QR"],
"CapOld2796":["PP"],
"Vallejo_94":["RATT"],
"Rivers_Custom":["NIR","AIC"],
"Standard-Cat-7702":["AIC"],
"Known-Delay7227":["JAYZ"],
"Infamous-Support-757":["GG","PJ","CRAN"],
"GeddleeIrwin":["QR"],
"123fofisix":["EC"],
"kbpeyton":["GM"],
"Uknoww33":["NIR","AIC"],
"LadyofHorror":["HOLE"],
"Wise_Animator_649":["AIC","STP","KORN"],
"Independent_Cap16":["BJO","REM","NIR","AIC","AM"],
"Th3L0n3R4g3r":["NIR"],
"beer_and_tacos1969":["BD"],
}

tally = {}
for who, picks in V.items():
    for code in set(picks):
        assert code in A, (who, code)
        tally[code] = tally.get(code, 0) + 1

out = sorted(tally.items(), key=lambda kv: (-kv[1], A[kv[0]][0].lower()))

rows = []
for code, n in out:
    name, year = A[code]
    q = f"{name} MTV Unplugged {year}".strip() if code != "YO" else "Yo! MTV Raps Unplugged 1991"
    rows.append({
        "key": f"unpl|{name}",
        "lead": f"{n}×",
        "sec": year or "—",
        "pri": name,
        "yt": q,
        "ytWord": "Watch",
        "src": {"label": "r/musicsuggestions", "url": URL},
    })

if __name__ == "__main__":
    for c, n in out[:25]:
        print(n, A[c][0])
    print("SETS", len(out), "REDDITORS", len(V), "VOTES", sum(n for _, n in out),
          "ONCE", sum(1 for _, n in out if n == 1))
    json.dump(rows, open("/tmp/unplugged.json", "w"), ensure_ascii=False)
