"""r/classicliterature — "What's the most unputdownable book you've read?"

Counted by distinct redditor: naming a book, or endorsing it in a reply, counts once.
"""
import json

THREAD = {
    "q": "What's the most unputdownable book you've read?",
    "site": "Reddit · r/classicliterature",
    "year": 2025,
    "meta": "378 points · 412 comments",
    "url": "https://www.reddit.com/r/classicliterature/comments/1pf1ffn/whats_the_most_unputdownable_book_youve_read/",
}

D = [
 ("The Count of Monte Cristo","Alexandre Dumas",12),
 ("Wuthering Heights","Emily Brontë",8),
 ("Crime and Punishment","Fyodor Dostoevsky",8),
 ("East of Eden","John Steinbeck",6),
 ("Stoner","John Williams",5),
 ("Anna Karenina","Leo Tolstoy",4),
 ("Lonesome Dove","Larry McMurtry",4),
 ("Giovanni's Room","James Baldwin",3),
 ("In Cold Blood","Truman Capote",3),
 ("The Master and Margarita","Mikhail Bulgakov",3),
 ("The Remains of the Day","Kazuo Ishiguro",3),
 ("Flowers for Algernon","Daniel Keyes",3),
 ("The Stranger","Albert Camus",3),
 ("Mother Night","Kurt Vonnegut",2),
 ("The Grapes of Wrath","John Steinbeck",2),
 ("The Three Musketeers","Alexandre Dumas",2),
 ("The Secret History","Donna Tartt",2),
 ("Middlemarch","George Eliot",2),
 ("War and Peace","Leo Tolstoy",2),
 ("The Road","Cormac McCarthy",2),
 ("All the Pretty Horses","Cormac McCarthy",2),
 ("The Idiot","Fyodor Dostoevsky",2),
 ("Madame Bovary","Gustave Flaubert",2),
 ("The Vegetarian","Han Kang",2),
 ("The Unbearable Lightness of Being","Milan Kundera",2),
 ("The Age of Innocence","Edith Wharton",2),
 ("Emma","Jane Austen",2),
 ("A Little Life","Hanya Yanagihara",2),
 ("The Killer Angels","Michael Shaara",2),
 ("The Wind-Up Bird Chronicle","Haruki Murakami",2),
 ("Annihilation","Jeff VanderMeer",2),
 ("The Brothers Karamazov","Fyodor Dostoevsky",2),
 ("Lolita","Vladimir Nabokov",2),
 ("The Hunchback of Notre-Dame","Victor Hugo",2),
 ("One Hundred Years of Solitude","Gabriel García Márquez",2),
 ("Dracula","Bram Stoker",2),
 ("Dune","Frank Herbert",2),
 ("The Tenant of Wildfell Hall","Anne Brontë",2),
 ("Chronicle of a Death Foretold","Gabriel García Márquez",2),
 ("The Monk","Matthew Lewis",2),
 ("Catch-22","Joseph Heller",2),
 ("The Picture of Dorian Gray","Oscar Wilde",1),
 ("Cannery Row","John Steinbeck",1),
 ("Georges","Alexandre Dumas",1),
 ("Great Expectations","Charles Dickens",1),
 ("We Have Always Lived in the Castle","Shirley Jackson",1),
 ("No Country for Old Men","Cormac McCarthy",1),
 ("The Sound and the Fury","William Faulkner",1),
 ("Glamorama","Bret Easton Ellis",1),
 ("The Crossing","Cormac McCarthy",1),
 ("The Good Soldier","Ford Madox Ford",1),
 ("Time's Arrow","Martin Amis",1),
 ("Pride and Prejudice","Jane Austen",1),
 ("The Screwtape Letters","C.S. Lewis",1),
 ("Blood Meridian","Cormac McCarthy",1),
 ("Notes from Underground","Fyodor Dostoevsky",1),
 ("Napoleon: A Life","Andrew Roberts",1),
 ("Slaughterhouse-Five","Kurt Vonnegut",1),
 ("The Bonfire of the Vanities","Tom Wolfe",1),
 ("One Flew Over the Cuckoo's Nest","Ken Kesey",1),
 ("Rabbit, Run","John Updike",1),
 ("The Virgin Suicides","Jeffrey Eugenides",1),
 ("Plainsong","Kent Haruf",1),
 ("Our Mutual Friend","Charles Dickens",1),
 ("My Ántonia","Willa Cather",1),
 ("Flashman at the Charge","George MacDonald Fraser",1),
 ("The Mill on the Floss","George Eliot",1),
 ("The Woman in White","Wilkie Collins",1),
 ("House of Leaves","Mark Z. Danielewski",1),
 ("Rebecca","Daphne du Maurier",1),
 ("Presumed Innocent","Scott Turow",1),
 ("Unbroken","Laura Hillenbrand",1),
 ("Killers of the Flower Moon","David Grann",1),
 ("The Goldfinch","Donna Tartt",1),
 ("To Kill a Mockingbird","Harper Lee",1),
 ("Gone with the Wind","Margaret Mitchell",1),
 ("Different Seasons","Stephen King",1),
 ("Angela's Ashes","Frank McCourt",1),
 ("The Sea-Wolf","Jack London",1),
 ("The River of Doubt","Candice Millard",1),
 ("For Whom the Bell Tolls","Ernest Hemingway",1),
 ("White Noise","Don DeLillo",1),
 ("Rejection","Tony Tulathimutte",1),
 ("The Martian","Andy Weir",1),
 ("The Gunslinger","Stephen King",1),
 ("The Collector","John Fowles",1),
 ("Love in the Time of Cholera","Gabriel García Márquez",1),
 ("Pet Sematary","Stephen King",1),
 ("American Psycho","Bret Easton Ellis",1),
 ("Anxious People","Fredrik Backman",1),
 ("A Man Called Ove","Fredrik Backman",1),
 ("The Odyssey","Homer",1),
 ("Don Quixote","Miguel de Cervantes",1),
 ("I, Claudius","Robert Graves",1),
 ("Their Eyes Were Watching God","Zora Neale Hurston",1),
 ("Moby-Dick","Herman Melville",1),
 ("Of Human Bondage","W. Somerset Maugham",1),
 ("The Prince of Tides","Pat Conroy",1),
 ("Franny and Zooey","J.D. Salinger",1),
 ("2666","Roberto Bolaño",1),
 ("Infinite Jest","David Foster Wallace",1),
 ("Borrowed Time","Paul Monette",1),
 ("Battle Royale","Koushun Takami",1),
 ("Eragon","Christopher Paolini",1),
 ("Jarhead","Anthony Swofford",1),
 ("Fahrenheit 451","Ray Bradbury",1),
 ("The Phantom of the Opera","Gaston Leroux",1),
 ("Animal Farm","George Orwell",1),
 ("The Physician","Noah Gordon",1),
 ("Kafka on the Shore","Haruki Murakami",1),
 ("The Three-Body Problem","Liu Cixin",1),
 ("The Call of the Wild","Jack London",1),
 ("David Copperfield","Charles Dickens",1),
 ("Shogun","James Clavell",1),
 ("The Godfather","Mario Puzo",1),
 ("The Bone Season","Samantha Shannon",1),
 ("Empire of the Vampire","Jay Kristoff",1),
 ("The Lord of the Rings","J.R.R. Tolkien",1),
 ("The Vampire Lestat","Anne Rice",1),
 ("A Storm of Swords","George R.R. Martin",1),
 ("The Real Life of Sebastian Knight","Vladimir Nabokov",1),
 ("Despair","Vladimir Nabokov",1),
 ("Memoirs of Hadrian","Marguerite Yourcenar",1),
 ("Tess of the d'Urbervilles","Thomas Hardy",1),
 ("The Spire","William Golding",1),
 ("Eichmann in Jerusalem","Hannah Arendt",1),
 ("Night","Elie Wiesel",1),
 ("Orlando Furioso","Ludovico Ariosto",1),
 ("Buddenbrooks","Thomas Mann",1),
 ("Thérèse Raquin","Émile Zola",1),
 ("Doctor Faustus","Thomas Mann",1),
 ("The Forty Days of Musa Dagh","Franz Werfel",1),
 ("A Fine Balance","Rohinton Mistry",1),
 ("Invisible Man","Ralph Ellison",1),
 ("Educated","Tara Westover",1),
 ("The Song of Achilles","Madeline Miller",1),
 ("Carmilla","J. Sheridan Le Fanu",1),
 ("Tuesdays with Morrie","Mitch Albom",1),
 ("Elective Affinities","Johann Wolfgang von Goethe",1),
 ("The Crying of Lot 49","Thomas Pynchon",1),
 ("Homage to Catalonia","George Orwell",1),
 ("Memoirs of a Geisha","Arthur Golden",1),
 ("The Bell Jar","Sylvia Plath",1),
 ("The Day of the Jackal","Frederick Forsyth",1),
 ("The Haunting of Hill House","Shirley Jackson",1),
 ("A Month in the Country","J.L. Carr",1),
]

rows = sorted(({"title": t, "author": a, "mentions": m} for t, a, m in D),
              key=lambda r: (-r["mentions"], r["title"].lower()))
json.dump({"thread": THREAD, "rows": rows}, open("unput.json", "w"),
          ensure_ascii=False, separators=(",", ":"))
print(len(rows), "books;", sum(r["mentions"] for r in rows), "recommendations")
