-- Listomania's entire server-side state.
--
-- Two things live here and nothing else: who you are (so the marks have an
-- owner), and what you ticked or bookmarked. The lists themselves stay in the
-- repository as JSON — a list is content, not user data, and putting it in a
-- database would make every edit an invisible write instead of a reviewable
-- diff.

-- ---------------------------------------------------------------- Auth.js ---
-- Verbatim from the Auth.js Postgres adapter. Don't hand-edit these.
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  "emailVerified" TIMESTAMPTZ,
  image TEXT
);

CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(255) NOT NULL,
  provider VARCHAR(255) NOT NULL,
  "providerAccountId" VARCHAR(255) NOT NULL,
  refresh_token TEXT,
  access_token TEXT,
  expires_at BIGINT,
  id_token TEXT,
  scope TEXT,
  session_state TEXT,
  token_type TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires TIMESTAMPTZ NOT NULL,
  "sessionToken" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS verification_token (
  identifier TEXT,
  expires TIMESTAMPTZ NOT NULL,
  token TEXT,
  PRIMARY KEY (identifier, token)
);

-- ------------------------------------------------------------------ Marks ---
-- One row per (person, kind, list, item). The primary key is the whole tuple,
-- so a double-click or a replayed request can't create a duplicate — ticking
-- something twice is the same as ticking it once, which is what a person would
-- expect and what makes the sync safe to retry.
--
-- kind: 'done'  — I've read / seen / eaten at this
--       'want'  — it's on my list
--       'fav'   — one of my favourites
-- They are separate rows on purpose: wanting to reread a book you've read is a
-- normal thing to want, and a favourite is not the same claim as either. done
-- is a fact, want is an intention, fav is a judgement.
CREATE TABLE IF NOT EXISTS marks (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind    TEXT NOT NULL CHECK (kind IN ('done', 'want', 'fav')),
  list_id TEXT NOT NULL,
  item_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, kind, list_id, item_key)
);

CREATE INDEX IF NOT EXISTS marks_user_idx ON marks (user_id);

-- --------------------------------------------------------------- Usernames ---
-- Password accounts. Nullable because a GitHub account has none of this, and a
-- username account has no email — the two paths meet at users.id and nowhere
-- else.
--
-- There is deliberately no email column for password accounts. It would be the
-- obvious way to offer password resets, and it is exactly the piece of personal
-- data this site has no other use for. The recovery code is the trade: one
-- string, shown once at signup, hashed here the same way the password is.
ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS recovery_hash TEXT;

-- Case-insensitive uniqueness: "Isabel" and "isabel" must not be two people.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (lower(username));

-- Per-account throttling. Guessing a password should get slower for the account
-- being guessed at, without telling the guesser whether it exists.
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_logins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

-- ----------------------------------------------------------- Own entries ---
-- Things a person added themselves: a favourite that no crowd in this site's
-- content ever named.
--
-- These are NOT marks. A mark points at a row that already exists in
-- content/shelves.json, so the content stays the single source of truth and a
-- mark is just four short strings. An entry has no row to point at — it *is*
-- the content — so it carries its own text and its own id.
--
-- The id is generated by the client (a uuid) rather than by a sequence here,
-- because an entry has to exist and be editable in a browser that has never
-- signed in, and then keep the same identity when that browser is claimed. A
-- serial would only be assigned at the moment of claiming, which is too late.
CREATE TABLE IF NOT EXISTS entries (
  user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  id       TEXT NOT NULL,
  shelf    TEXT NOT NULL,
  pri      TEXT NOT NULL,          -- the thing itself
  sec      TEXT NOT NULL DEFAULT '',  -- author / artist / director / what it is
  note     TEXT NOT NULL DEFAULT '',  -- why, in your own words
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id)
);

CREATE INDEX IF NOT EXISTS entries_user_shelf_idx ON entries (user_id, shelf);

-- 'fav' arrived after the table did, so an existing database needs its CHECK
-- constraint widened. Dropping and re-adding is safe here: the new set is a
-- superset of the old one, so no existing row can fail it.
ALTER TABLE marks DROP CONSTRAINT IF EXISTS marks_kind_check;
ALTER TABLE marks ADD CONSTRAINT marks_kind_check CHECK (kind IN ('done', 'want', 'fav'));
